<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Completing &amp; Submitting Lab Assignments | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Completing &amp; Submitting Lab Assignments | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Completing &amp; Submitting Lab Assignments | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2021-09-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preparing-and-formatting-assignments.html"/>
<link rel="next" href="visual-markdown-editor.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li class="part"><span><b>Preface</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>Author</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
</ul></li>
<li class="part"><span><b>Getting started with R, RStudio &amp; R Markdown</b></span></li>
<li class="chapter" data-level="1" data-path="what-is-R.html"><a href="what-is-R.html"><i class="fa fa-check"></i><b>1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="2" data-path="install-R-Rstudio.html"><a href="install-R-Rstudio.html"><i class="fa fa-check"></i><b>2</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="3" data-path="start-r.html"><a href="start-r.html"><i class="fa fa-check"></i><b>3</b> Start using R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Rstudio-interface.html"><a href="Rstudio-interface.html"><i class="fa fa-check"></i><b>3.1</b> The RStudio Interface</a></li>
<li class="chapter" data-level="3.2" data-path="coding-basics.html"><a href="coding-basics.html"><i class="fa fa-check"></i><b>3.2</b> Coding basics</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>4</b> R packages</a>
<ul>
<li class="chapter" data-level="4.1" data-path="package-install.html"><a href="package-install.html"><i class="fa fa-check"></i><b>4.1</b> Package installation</a></li>
<li class="chapter" data-level="4.2" data-path="package-load.html"><a href="package-load.html"><i class="fa fa-check"></i><b>4.2</b> Package loading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="intro-markdown.html"><a href="intro-markdown.html"><i class="fa fa-check"></i><b>5</b> Intro to R Markdown</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lit-programming.html"><a href="lit-programming.html"><i class="fa fa-check"></i><b>5.1</b> Literate programming with R Markdown</a></li>
<li class="chapter" data-level="5.2" data-path="veryify-knit.html"><a href="veryify-knit.html"><i class="fa fa-check"></i><b>5.2</b> Making sure R Markdown knits to PDF</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-resources.html"><a href="r-resources.html"><i class="fa fa-check"></i><b>6</b> Extra online resources</a>
<ul>
<li class="chapter" data-level="6.1" data-path="online-resources.html"><a href="online-resources.html"><i class="fa fa-check"></i><b>6.1</b> R Resources Online</a></li>
</ul></li>
<li class="part"><span><b>Reproducible Workflows</b></span></li>
<li class="chapter" data-level="7" data-path="repro-research.html"><a href="repro-research.html"><i class="fa fa-check"></i><b>7</b> Reproducible Research</a>
<ul>
<li class="chapter" data-level="7.1" data-path="comp-repro.html"><a href="comp-repro.html"><i class="fa fa-check"></i><b>7.1</b> Computational reproducibility</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="biol202-workflow.html"><a href="biol202-workflow.html"><i class="fa fa-check"></i><b>8</b> An example BIOL202 workflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="onedrive.html"><a href="onedrive.html"><i class="fa fa-check"></i><b>8.1</b> Microsoft OneDrive</a></li>
<li class="chapter" data-level="8.2" data-path="dir-structure.html"><a href="dir-structure.html"><i class="fa fa-check"></i><b>8.2</b> Directory structure</a></li>
<li class="chapter" data-level="8.3" data-path="setup-dirs.html"><a href="setup-dirs.html"><i class="fa fa-check"></i><b>8.3</b> Steps to set up directories</a></li>
<li class="chapter" data-level="8.4" data-path="lecture-workflow.html"><a href="lecture-workflow.html"><i class="fa fa-check"></i><b>8.4</b> Lecture workflow</a></li>
<li class="chapter" data-level="8.5" data-path="tutorial-workflow.html"><a href="tutorial-workflow.html"><i class="fa fa-check"></i><b>8.5</b> Tutorial workflow</a></li>
<li class="chapter" data-level="8.6" data-path="create-project.html"><a href="create-project.html"><i class="fa fa-check"></i><b>8.6</b> Create an RStudio Project</a></li>
<li class="chapter" data-level="8.7" data-path="create-subdirs.html"><a href="create-subdirs.html"><i class="fa fa-check"></i><b>8.7</b> Create subdirectories</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="create-subdirs.html"><a href="create-subdirs.html#here_package"><i class="fa fa-check"></i><b>8.7.1</b> The <code>here</code> package</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="edit-markdown.html"><a href="edit-markdown.html"><i class="fa fa-check"></i><b>8.8</b> Edit an R markdown file</a></li>
<li class="chapter" data-level="8.9" data-path="md-components.html"><a href="md-components.html"><i class="fa fa-check"></i><b>8.9</b> Components of an R Markdown file</a></li>
<li class="chapter" data-level="8.10" data-path="interact-tutorial.html"><a href="interact-tutorial.html"><i class="fa fa-check"></i><b>8.10</b> Interacting with Tutorial material</a></li>
<li class="chapter" data-level="8.11" data-path="assign-workflow.html"><a href="assign-workflow.html"><i class="fa fa-check"></i><b>8.11</b> Lab assignments workflow</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preparing-and-formatting-assignments.html"><a href="preparing-and-formatting-assignments.html"><i class="fa fa-check"></i>Preparing and formatting assignments</a>
<ul>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html"><i class="fa fa-check"></i>Completing &amp; Submitting Lab Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#open_assign_project1"><i class="fa fa-check"></i>Open your assignment RStudio project</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#download_assign_rmd"><i class="fa fa-check"></i>Download the assignment Rmd file</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#open_rmd_file"><i class="fa fa-check"></i>Open the assignment Rmd file</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#what_include_answer"><i class="fa fa-check"></i>What to include in your answers</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#example_answer"><i class="fa fa-check"></i>Example question / answer</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#knit_assign"><i class="fa fa-check"></i>Knitting your assignment to PDF</a></li>
<li class="chapter" data-level="" data-path="completing-submitting-lab-assignments.html"><a href="completing-submitting-lab-assignments.html#rmd_graphing"><i class="fa fa-check"></i>Setting up R Markdown for graphing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="visual-markdown-editor.html"><a href="visual-markdown-editor.html"><i class="fa fa-check"></i>Visual Markdown Editor</a>
<ul>
<li class="chapter" data-level="" data-path="a-more-familiar-editing-environment.html"><a href="a-more-familiar-editing-environment.html"><i class="fa fa-check"></i>A more familiar editing environment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="common-errors-and-their-solutions.html"><a href="common-errors-and-their-solutions.html"><i class="fa fa-check"></i>Common errors and their solutions</a>
<ul>
<li class="chapter" data-level="" data-path="google-can-help.html"><a href="google-can-help.html"><i class="fa fa-check"></i>Google can help</a></li>
<li class="chapter" data-level="" data-path="rtools-required-during-install.html"><a href="rtools-required-during-install.html"><i class="fa fa-check"></i>Rtools required during install</a></li>
<li class="chapter" data-level="" data-path="could-not-find-function.html"><a href="could-not-find-function.html"><i class="fa fa-check"></i>Could not find function</a></li>
<li class="chapter" data-level="" data-path="there-is-no-package.html"><a href="there-is-no-package.html"><i class="fa fa-check"></i>There is no package</a></li>
<li class="chapter" data-level="" data-path="trying-to-use-cran-without-setting-a-mirror.html"><a href="trying-to-use-cran-without-setting-a-mirror.html"><i class="fa fa-check"></i>Trying to use CRAN without setting a mirror</a></li>
<li class="chapter" data-level="" data-path="pdf-latex-is-not-found.html"><a href="pdf-latex-is-not-found.html"><i class="fa fa-check"></i>PDF Latex is not found</a></li>
<li class="chapter" data-level="" data-path="error-in-parse.html"><a href="error-in-parse.html"><i class="fa fa-check"></i>Error in parse</a></li>
<li class="chapter" data-level="" data-path="no-such-file-or-directory-exists.html"><a href="no-such-file-or-directory-exists.html"><i class="fa fa-check"></i>No such file or directory exists</a></li>
<li class="chapter" data-level="" data-path="messy-output-when-loading-packages.html"><a href="messy-output-when-loading-packages.html"><i class="fa fa-check"></i>Messy output when loading packages</a></li>
<li class="chapter" data-level="" data-path="unused-argument.html"><a href="unused-argument.html"><i class="fa fa-check"></i>Unused argument</a></li>
<li class="chapter" data-level="" data-path="object-not-found.html"><a href="object-not-found.html"><i class="fa fa-check"></i>Object not found</a></li>
<li class="chapter" data-level="" data-path="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><i class="fa fa-check"></i>Figure caption doesn’t show up below figure in knitted document</a></li>
<li class="chapter" data-level="" data-path="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><i class="fa fa-check"></i>Filename, directory name, or volume label syntax is incorrect</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="completing-submitting-lab-assignments" class="section level2 unnumbered">
<h2>Completing &amp; Submitting Lab Assignments</h2>
<div id="open_assign_project1" class="section level3 unnumbered">
<h3>Open your assignment RStudio project</h3>
<p>In a previous <a href="assign-workflow.html#assign_workflow">tutorial</a> it was suggested you set up a working root directory called “BIOL202_assignments” to host all your assignment work. You may have also created sub-directories, one for each of the three assignments. Regardless, in your root “BIOL202_assignments” directory locate the RStudio project file (it has a “Rproj” extension in the filename), and open it by double-clicking it.</p>
</div>
<div id="download_assign_rmd" class="section level3 unnumbered">
<h3>Download the assignment Rmd file</h3>
<p>The assignment file will be available to you for download from Canvas. Locate the assignment there. The file is actually an R Markdown file, and therefore has an “Rmd” extension. It is simply a text document (meaning it contains only text), but the syntax used therein is “markdown” syntax, and the file extension (Rmd) specifies it as an R Markdown file. You might recall reading about Markdown in the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/markdown-1.html">Biology Procedures and Guidelines document</a>.</p>
<p>Make sure you save the Rmd file into your root “BIOL202_assignments” directory, or alternatively into the appropriate sub-directory.</p>
<p>A practice assignment has been set up on Canvas, so that you can get used to this procedure. It is located under “Lab_materials” module. Download the file, and make sure it’s saved into your root directory (where your RStudio project is).</p>
</div>
<div id="open_rmd_file" class="section level3 unnumbered">
<h3>Open the assignment Rmd file</h3>
<p>In RStudio, look in the “files” pane (bottom right) and locate your downloaded assignment Rmd file. Then click it to open.</p>
<p>This Markdown document includes the assignment questions, and serves as a starter document for your assignment.</p>
<p>Once you have opened the document, you’ll see the following text at the top:</p>
<div class="figure">
<img src="more/assign_header.png" alt="" />
<p class="caption">Assignment header</p>
</div>
<p>Do the following steps:</p>
<ul>
<li>keeping the quotation marks, replace the “Practice assignment” text with the current assignment name (e.g. “Assignment 1”)</li>
<li>keeping the quotation marks, replace the “Firstname Lastname, Section YY” with your own Firstname Lastname and section number (e.g. " Jason Pither, Section 04")</li>
<li>keeping the quotation marks, replace the “Due date” with the due date of the current assignment, e.g. “October 12, 2021”</li>
</ul>
<div class="note">
<p><strong>NOTE</strong>
Don’t alter anything else at the top of the document, including the R Chunk that you see below the header.</p>
</div>
<ul>
<li>save the Rmd file using a new name (so select file &gt; “save as”), according to appropriate <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/file-and-data-management.html">file naming conventions</a>, such as “Pither_BIOL202_Assign01.Rmd.” Recall that if you’re saving this on OneDrive, or in your local directory that is synced to OneDrive, then your file will be <a href="onedrive.html#onedrive">version controlled</a>.</li>
</ul>
<p>You’re now ready to start working on your assignment, and doing <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary.html">literate programming</a> using R Markdown.</p>
<div class="note">
<p><strong>REMINDER</strong>
In RStudio, under the “Help” menu, you’ll find “Cheat Sheets” &gt; R Markdown Cheat Sheet and R Markdown Reference Guide. Have a look at those!</p>
</div>
</div>
<div id="what_include_answer" class="section level3 unnumbered">
<h3>What to include in your answers</h3>
<p>The general approach is to enter your text answers and associated R chunks with code underneath each question.</p>
<div class="note">
<p><strong>Tip</strong>
It is almost always the case that you’ll need to load the <code>tidyverse</code> package, so it’s advisable to include an R chunk right at the beginning of your document that does this.</p>
</div>
<div class="note">
<p><strong>Tip</strong>
To insert a new code chunk, you can either: * Use the shortcut: Mac = <code>Command+Option+I</code>; Windows = <code>Ctrl+Alt+I</code>. * Click on the <strong>Insert a new code chunk</strong> icon. You can also change specify the coding language of the chunk using the drop-down menu.</p>
</div>
<div id="chunk_headers" class="section level4 unnumbered">
<h4>Code chunk headers</h4>
<p>Here’s an example code chunk in which the <code>tidyverse</code> package is being loaded. You’ll notice some extra text in the header of the chunk.</p>
<div class="figure">
<img src="more/install_package_header.png" alt="" />
<p class="caption">Install packges R Chunk header</p>
</div>
<p>The “load_packages” text is simply giving a name or “tag” to this R chunk. It is good practice to provide a unique name to each R chunk.</p>
<p>After the comma is <code>message = F</code>. This tells R markdown to NOT display any messages associated with the R commands in this chunk when knitting the R Markdown document. For example, when loading some libraries R will provide a long list of messages in the process. When you “knit” the R Markdown document, R will run each R chunk in your document. By including the <code>message = F</code> heading argument, you can avoid including this extra output in your knitted document.</p>
<p>For some packages, such as the <code>tidyverse</code> package, the preceding approach doesn’t suppress all the messages that occur when loading the package. The</p>
<p>There will be routine steps to take for each question.</p>
<p><strong>Import data</strong></p>
<p>Each assignment question will indicate which dataset(s) you’ll need to answer the question, and where to locate / download these. In many instances multiple questions will use the same dataset, in which case you don’t need to load data for each question; just load it once.</p>
<p>Here’s an example of code for importing data. It uses the <code>read_csv</code> function from the <code>readr</code> package, which is bundled with the <code>tidyverse</code> package:</p>
<pre><code>example_data &lt;- read_csv(&quot;https://raw.githubusercontent.com/ubco-biology/BIOL202/main/data/example_data.csv&quot;)</code></pre>
<p><strong>Load packages</strong></p>
<p>Once you’ve loaded the data, you’ll now need to figure out how to answer the question by looking through the tutorials for the answer. And typically, to answer the question you’ll need to make sure you’ve loaded some packages.</p>
<p>If you’ve forgotten what “packages” are, refresh your memory at this <a href="packages.html#packages">tutorial</a>.</p>
<p>For example, it’s likely you’ve already loaded the <code>tidyverse</code> package (as advised above), but if a tutorial indicates you need another package, say the <code>janitor</code> package, then insert a code chunk with the following:</p>
<pre><code>library(janitor)</code></pre>
<div class="note">
<p><strong>REMINDER</strong>
When working on your own computer, you only need to install a package once (unless you want to update an already installed package to the latest version, which is a rare event). If you’re working on a school computer (in a computer lab), you may need to install packages each time you log on to a computer, because the school computers delete local files daily. If you’re unsure what packages are already installed, consult the “packages” tab in the lower-right RStudio pane when you start up RStudio; installed packages are listed there.</p>
</div>
<p><strong>Answer the questions</strong></p>
<p>After you’ve imported the required data and loaded required packages, it’s time to answer the questions!</p>
<p>You simply insert any required text and R code (in R Chunks) after each question. The tutorials will provide the information required to answer the questions.</p>
<div class="note">
<p><strong>TIP</strong>
The way to test out your code once it’s inserted in the R chunk is to press the green play button at the top right of the code chunk. This will run what’s in the chunk. You’ll be provided error statements if something goes wrong. If it works, it will provide you the output (and hopefully the answer!), and this is what you use to inform your written (typed) answer.</p>
</div>
<p>Here’s what you need to include in your answers:</p>
<ul>
<li><p>You <strong>must</strong> answer each question clearly and in full sentences. Make sure you answer specifically the question asked.</p></li>
<li><p>Verify that the code you used to answer the question is included in an R chunk and appears in the knitted document (this should happen automatically)</p></li>
<li><p>Verify that the output from each R chunk is included in your knitted document (this should happen automatically)</p></li>
<li><p>For any figures (graphs) that you produce, you must include a figure caption. A future tutorial will show you how.</p></li>
<li><p>If you use a graph to answer a question, refer to that graph in your answer</p></li>
</ul>
<div class="note">
<p><strong>REMINDER</strong>
As you work on your document, save frequently, and also knit your document frequently.</p>
</div>
<div class="note">
<p><strong>TIP</strong>
You will often need/want to preview the document you are working on to ensure that everything is being formatted as you expected in the knitting process. The default setting is for the preview to open in a new pop-up window outside of RStudio, although you may find it useful to have it open in the Viewer panel within RStudio itself (particularly if you’re only working with one screen!). To change the preview location, click the <strong>Settings</strong> icon in the toolbar and select the option to “Preview in Viewer Pane.”</p>
</div>
</div>
</div>
<div id="example_answer" class="section level3 unnumbered">
<h3>Example question / answer</h3>
<p>Below is an example of how to answer a question.</p>
<div class="note">
<p><strong>NOTE</strong>
There are almost <em>always</em> multiple coding approaches to get the right answer, some better than others. As long as your code and answer are accurate and make sense, you’ll get the marks!</p>
</div>
<p><strong>Question 1.</strong> What are the minimum and maximum heights (variable name is “height_cm”) of students in the “students” dataset, which is available at this URL:</p>
<pre><code>https://raw.githubusercontent.com/ubco-biology/BIOL202/main/data/students2.csv</code></pre>
<p><strong>Example Answer 1</strong></p>
<p>I’ll first download and import the dataset:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="completing-submitting-lab-assignments.html#cb11-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/ubco-biology/BIOL202/main/data/students2.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   height_cm = col_double(),
##   head_circum_cm = col_double(),
##   Sex = col_character(),
##   Number_of_siblings = col_double(),
##   Dominant_hand = col_character(),
##   Dominant_foot = col_character(),
##   Dominant_eye = col_character()
## )</code></pre>
<p>As we learned in the [fictitious] “importing and exploring data” tutorial, we can use the <code>summary</code> function to get some basic descriptive statistics, including the minimum and maximum of numeric variables. The <code>summary</code> function is part of the base R package, so no additional packages need to be loaded.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="completing-submitting-lab-assignments.html#cb13-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="completing-submitting-lab-assignments.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  summary</span></code></pre></div>
<pre><code>##    height_cm     head_circum_cm      Sex            Number_of_siblings Dominant_hand      Dominant_foot     
##  Min.   :150.0   Min.   :21.00   Length:154         Min.   :0.000      Length:154         Length:154        
##  1st Qu.:165.0   1st Qu.:55.52   Class :character   1st Qu.:1.000      Class :character   Class :character  
##  Median :171.5   Median :57.00   Mode  :character   Median :2.000      Mode  :character   Mode  :character  
##  Mean   :172.0   Mean   :56.04                      Mean   :1.708                                           
##  3rd Qu.:180.0   3rd Qu.:58.50                      3rd Qu.:2.000                                           
##  Max.   :210.8   Max.   :63.00                      Max.   :6.000                                           
##  Dominant_eye      
##  Length:154        
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
<p>As shown in the output above, the minimum height was 150.0 cm and the maximum student height was 210.8 cm.</p>
<p><strong>Example Answer 2</strong></p>
<p>I’ll first download and import the dataset:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="completing-submitting-lab-assignments.html#cb15-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/ubco-biology/BIOL202/main/data/students2.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   height_cm = col_double(),
##   head_circum_cm = col_double(),
##   Sex = col_character(),
##   Number_of_siblings = col_double(),
##   Dominant_hand = col_character(),
##   Dominant_foot = col_character(),
##   Dominant_eye = col_character()
## )</code></pre>
<p>As we learned in the [fictitious] “describing data” tutorial, we can use the <code>summarise</code> function from the <code>dplyr</code> package (which comes with the <code>tidyverse</code> package) to get basic descriptive statistics for numeric variables in a dataset.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="completing-submitting-lab-assignments.html#cb17-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="completing-submitting-lab-assignments.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">min.height=</span> <span class="fu">min</span>(height_cm, <span class="at">na.rm =</span> T), </span>
<span id="cb17-3"><a href="completing-submitting-lab-assignments.html#cb17-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">max.height =</span> <span class="fu">max</span>(height_cm, <span class="at">na.rm =</span> T))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   min.height max.height
##        &lt;dbl&gt;      &lt;dbl&gt;
## 1        150       211.</code></pre>
<p>As shown in the output above, the minimum height was 150.0 cm and the maximum student height was 210.8 cm.</p>
</div>
<div id="knit_assign" class="section level3 unnumbered">
<h3>Knitting your assignment to PDF</h3>
<p>All assignments are to be submitted to Canvas as <strong>PDF documents</strong>.</p>
<p>As you learned in a previous <a href="veryify-knit.html#veryify_knit">tutorial</a>, simply click on the “knit” button and select PDF. Your PDF file will adopt the same name as your markdown file, but it will have a “pdf” extension rather than an “Rmd” extension.</p>
<p>Once you have knitted your assignment to PDF, open up the PDF document, and verify that it looks correct, and be sure to check all your spelling, and that figures / tables are appropriately formatted etc…</p>
<p>If you need to fix something, close your PDF file, go back to your R Markdown document and do the edits there. Save, then knit again!</p>
<p>Submit your PDF document to the appropriate place in Canvas.</p>
<p>Verify afterwards that your PDF document did indeed upload correctly.</p>
</div>
<div id="rmd_graphing" class="section level3 unnumbered">
<h3>Setting up R Markdown for graphing</h3>
<p>There are some special code chunk header arguments that need to be set in your Markdown document in order to:</p>
<ul>
<li>include proper <strong>Figure captions</strong> with your figures (a necessity!)</li>
<li>set the dimensions of your figures</li>
</ul>
<p>In each code chunk that includes code to construct a graph, your chunk header options should look like this in the top of the chunk, and there should be one blank line underneath before the main code starts. The following chunk produced the figure below. And recall that in the example below, the “bill_fig” text is simply the name I’ve given to this code chunk.</p>
<pre><code>{r bill_fig, fig.cap = &quot;Histogram of bill depth among 151 Adelie penguins&quot;, fig.width = 4, fig.height = 4}

penguins %&gt;% 
  filter(species == &quot;Adelie&quot;) %&gt;%
  ggplot(aes(bill_depth_mm)) +
  geom_histogram(color = &quot;lightgrey&quot;)</code></pre>
<div class="figure">
<img src="BIOL202-github_files/figure-html/bill_fig-1.png" alt="Histogram of bill depth among 151 Adelie penguins" width="384" />
<p class="caption">
(#fig:bill_fig)Histogram of bill depth among 151 Adelie penguins
</p>
</div>
<p>The key parts are the “fig.cap =” argument, to which you provide the text you want to use as the figure caption. Then there’s the “fig.width =” and “fig.height =” arguments, which indicate the size of the figure when knitted. This will likely require some trial-and-error to get a good size, but start with the values in this example (4 for each).</p>
<p><strong>Automated figure numbering</strong></p>
<p>When you knit the document to PDF, you’ll see the “Figure 1:” text was appended at the beginning of the caption phrase that was included in the chunk header, “Histogram of bill depth among 151 Adelie penguins.”</p>
<p>This feature - automatic figure numbering - was set within the header of the assignment markdown document:</p>
<div class="figure">
<img src="more/assign_header.png" alt="" />
<p class="caption">Assignment header</p>
</div>
<p>The line “fig_caption = TRUE” tells R Markdown and the knitting process to automatically include this part of a figure caption, “Figure X,” underneath each figure you produce. Where “X” will automatically be replaced with the appropriate number. For example, it will use “Figure 1:” for your first figure, “Figure 2” for your second, and so on.</p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="preparing-and-formatting-assignments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visual-markdown-editor.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202-github.pdf", "BIOL202-github.epub"],
"toc": {
"collapse": "section",
"scroll_highight": true,
"download": ["pdf", "epub"]
}
});
});
</script>

</body>

</html>
