<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>17.2 Analysis of variance | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="17.2 Analysis of variance | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="17.2 Analysis of variance | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2022-09-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="anova-packages-data.html"/>
<link rel="next" href="assumpbad-anova.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li><a href="#part-preface" id="toc-part-preface">(PART*) Preface</a></li>
<li><a href="index.html#welcome" id="toc-welcome">Welcome</a>
<ul>
<li><a href="author.html#author" id="toc-author">Author</a></li>
<li><a href="acknowledgments.html#acknowledgments" id="toc-acknowledgments">Acknowledgments</a></li>
<li><a href="copyright.html#copyright" id="toc-copyright">Copyright</a></li>
<li><a href="ubco-biology-open-materials.html#ubco-biology-open-materials" id="toc-ubco-biology-open-materials">UBCO Biology open materials</a></li>
</ul></li>
<li><a href="#part-getting-started-with-r-rstudio-r-markdown" id="toc-part-getting-started-with-r-rstudio-r-markdown">(PART*) Getting started with R, RStudio &amp; R Markdown</a></li>
<li><a href="what-is-R.html#what_is_R" id="toc-what_is_R"><span class="toc-section-number">1</span> What are R and RStudio?</a></li>
<li><a href="install-R-Rstudio.html#install_R_Rstudio" id="toc-install_R_Rstudio"><span class="toc-section-number">2</span> Installing R and RStudio</a></li>
<li><a href="start-r.html#start_r" id="toc-start_r"><span class="toc-section-number">3</span> Start using R &amp; RStudio</a>
<ul>
<li><a href="Rstudio-interface.html#Rstudio_interface" id="toc-Rstudio_interface"><span class="toc-section-number">3.1</span> The RStudio Interface</a></li>
<li><a href="coding-basics.html#coding_basics" id="toc-coding_basics"><span class="toc-section-number">3.2</span> Coding basics</a></li>
</ul></li>
<li><a href="packages.html#packages" id="toc-packages"><span class="toc-section-number">4</span> R packages</a>
<ul>
<li><a href="package-install.html#package_install" id="toc-package_install"><span class="toc-section-number">4.1</span> Package installation</a></li>
<li><a href="package-load.html#package_load" id="toc-package_load"><span class="toc-section-number">4.2</span> Package loading</a></li>
</ul></li>
<li><a href="intro-markdown.html#intro_markdown" id="toc-intro_markdown"><span class="toc-section-number">5</span> Intro to R Markdown</a>
<ul>
<li><a href="lit-programming.html#lit_programming" id="toc-lit_programming"><span class="toc-section-number">5.1</span> Literate programming with R Markdown</a></li>
<li><a href="veryify-knit.html#veryify_knit" id="toc-veryify_knit"><span class="toc-section-number">5.2</span> Making sure R Markdown knits to PDF</a></li>
</ul></li>
<li><a href="r-resources.html#r_resources" id="toc-r_resources"><span class="toc-section-number">6</span> Extra resources</a>
<ul>
<li><a href="online-resources.html#online_resources" id="toc-online_resources"><span class="toc-section-number">6.1</span> R Resources Online</a></li>
<li><a href="rmd-graphing.html#rmd_graphing" id="toc-rmd_graphing"><span class="toc-section-number">6.2</span> Setting up R Markdown for graphing</a></li>
<li><a href="example-answer.html#example_answer" id="toc-example_answer"><span class="toc-section-number">6.3</span> Example question / answer</a></li>
<li><a href="knit-assign.html#knit_assign" id="toc-knit_assign"><span class="toc-section-number">6.4</span> Knitting your assignment to PDF</a></li>
<li><a href="submit-rmd.html#submit_rmd" id="toc-submit_rmd"><span class="toc-section-number">6.5</span> Submit your assignment</a></li>
</ul></li>
<li><a href="data-import.html#data_import" id="toc-data_import"><span class="toc-section-number">7</span> Preparing and importing Tidy Data</a>
<ul>
<li><a href="tidy-data.html#tidy_data" id="toc-tidy_data"><span class="toc-section-number">7.1</span> Tidy data</a></li>
<li><a href="import-csv-url.html#import_csv_url" id="toc-import_csv_url"><span class="toc-section-number">7.2</span> Import a CSV file from a website</a></li>
<li><a href="create-csv-local.html#create_csv_local" id="toc-create_csv_local"><span class="toc-section-number">7.3</span> Create a CSV file</a></li>
<li><a href="import-csv-local.html#import_csv_local" id="toc-import_csv_local"><span class="toc-section-number">7.4</span> Import a local CSV file</a></li>
<li><a href="data-overview.html#data_overview" id="toc-data_overview"><span class="toc-section-number">7.5</span> Get an overview of a dataset</a></li>
<li><a href="tutorial-practice-activities.html#tutorial-practice-activities" id="toc-tutorial-practice-activities"><span class="toc-section-number">7.6</span> Tutorial practice activities</a></li>
</ul></li>
<li><a href="#part-visualizing-and-describing-data" id="toc-part-visualizing-and-describing-data">(PART*) Visualizing and Describing Data</a></li>
<li><a href="vis-variable.html#vis_variable" id="toc-vis_variable"><span class="toc-section-number">8</span> Visualizing a single variable</a>
<ul>
<li><a href="vis-packages-data.html#vis_packages_data" id="toc-vis_packages_data"><span class="toc-section-number">8.1</span> Load packages and import data</a></li>
<li><a href="vis-data-overview.html#vis_data_overview" id="toc-vis_data_overview"><span class="toc-section-number">8.2</span> Get an overview of the data</a></li>
<li><a href="vis-cat-freq-table.html#vis_cat_freq_table" id="toc-vis_cat_freq_table"><span class="toc-section-number">8.3</span> Create a frequency table</a></li>
<li><a href="vis-cat-barchart.html#vis_cat_barchart" id="toc-vis_cat_barchart"><span class="toc-section-number">8.4</span> Create a bar graph</a></li>
<li><a href="vis-histogram.html#vis_histogram" id="toc-vis_histogram"><span class="toc-section-number">8.5</span> Create a histogram</a></li>
<li><a href="vis-describe-hist.html#vis_describe_hist" id="toc-vis_describe_hist"><span class="toc-section-number">8.6</span> Describing a histogram</a></li>
</ul></li>
<li><a href="vis-describe.html#vis_describe" id="toc-vis_describe"><span class="toc-section-number">9</span> Describing a single variable</a>
<ul>
<li><a href="desc-packages-data.html#desc_packages_data" id="toc-desc_packages_data"><span class="toc-section-number">9.1</span> Load packages and import data</a></li>
<li><a href="desc-cat-Var.html#desc_cat_Var" id="toc-desc_cat_Var"><span class="toc-section-number">9.2</span> Describing a categorical variable</a></li>
<li><a href="desc-numeric-var.html#desc_numeric_var" id="toc-desc_numeric_var"><span class="toc-section-number">9.3</span> Describing a numerical variable</a>
<ul>
<li><a href="desc-numeric-var.html#median_IQR" id="toc-median_IQR"><span class="toc-section-number">9.3.1</span> Calculating the median &amp; IQR</a></li>
<li><a href="desc-numeric-var.html#mean_sd" id="toc-mean_sd"><span class="toc-section-number">9.3.2</span> Calculating the mean &amp; standard deviation</a></li>
</ul></li>
<li><a href="desc-numeric-var-cat.html#desc_numeric_var_cat" id="toc-desc_numeric_var_cat"><span class="toc-section-number">9.4</span> Describing a numerical variable grouped by a categorical variable</a></li>
</ul></li>
<li><a href="vis-twovar.html#vis_twovar" id="toc-vis_twovar"><span class="toc-section-number">10</span> Visualizing associations between two variables</a>
<ul>
<li><a href="vis2-packages-data.html#vis2_packages_data" id="toc-vis2_packages_data"><span class="toc-section-number">10.1</span> Load packages and import data</a></li>
<li><a href="vis2-2cat.html#vis2_2cat" id="toc-vis2_2cat"><span class="toc-section-number">10.2</span> Visualizing association between two categorical variables</a>
<ul>
<li><a href="vis2-2cat.html#vis2_cont_table" id="toc-vis2_cont_table"><span class="toc-section-number">10.2.1</span> Constructing a contingency table</a></li>
<li><a href="vis2-2cat.html#grouped_bar_graphs" id="toc-grouped_bar_graphs"><span class="toc-section-number">10.2.2</span> Constructing a grouped bar graph</a></li>
<li><a href="vis2-2cat.html#mosaic_plot" id="toc-mosaic_plot"><span class="toc-section-number">10.2.3</span> Constructing a mosaic plot</a></li>
<li><a href="vis2-2cat.html#interpret_mosaic" id="toc-interpret_mosaic"><span class="toc-section-number">10.2.4</span> Interpreting mosaic plots</a></li>
</ul></li>
<li><a href="two-numeric.html#two_numeric" id="toc-two_numeric"><span class="toc-section-number">10.3</span> Visualizing association between two numeric variables</a>
<ul>
<li><a href="two-numeric.html#interpret_scatter" id="toc-interpret_scatter"><span class="toc-section-number">10.3.1</span> Interpreting and describing a scatterplot</a></li>
</ul></li>
<li><a href="numeric-vs-cat.html#numeric_vs_cat" id="toc-numeric_vs_cat"><span class="toc-section-number">10.4</span> Visualizing association between a numeric and a categorical variable</a>
<ul>
<li><a href="numeric-vs-cat.html#stripchart" id="toc-stripchart"><span class="toc-section-number">10.4.1</span> Create a stripchart</a></li>
<li><a href="numeric-vs-cat.html#violinplot" id="toc-violinplot"><span class="toc-section-number">10.4.2</span> Create a violin plot</a></li>
<li><a href="numeric-vs-cat.html#boxplots" id="toc-boxplots"><span class="toc-section-number">10.4.3</span> Creating a boxplot</a></li>
<li><a href="numeric-vs-cat.html#bestplot" id="toc-bestplot"><span class="toc-section-number">10.4.4</span> Combining violin and boxplots</a></li>
<li><a href="numeric-vs-cat.html#interp_violin" id="toc-interp_violin"><span class="toc-section-number">10.4.5</span> Interpreting stripcharts and boxplots</a></li>
</ul></li>
</ul></li>
<li><a href="#part-inferential-statistics" id="toc-part-inferential-statistics">(PART*) Inferential Statistics</a></li>
<li><a href="estimation.html#estimation" id="toc-estimation"><span class="toc-section-number">11</span> Sampling, Estimation, &amp; Uncertainty</a>
<ul>
<li><a href="estimation-packages-data.html#estimation_packages_data" id="toc-estimation_packages_data"><span class="toc-section-number">11.1</span> Load packages and import data</a></li>
<li><a href="sampling-functions.html#sampling_functions" id="toc-sampling_functions"><span class="toc-section-number">11.2</span> Functions for sampling</a>
<ul>
<li><a href="sampling-functions.html#setseed" id="toc-setseed"><span class="toc-section-number">11.2.1</span> Setting the “seed” for random sampling</a></li>
</ul></li>
<li><a href="sampling-error.html#sampling_error" id="toc-sampling_error"><span class="toc-section-number">11.3</span> Sampling error</a></li>
<li><a href="sampdistmean.html#sampdistmean" id="toc-sampdistmean"><span class="toc-section-number">11.4</span> Sampling distribution of the mean</a>
<ul>
<li><a href="sampdistmean.html#hist_samdist" id="toc-hist_samdist"><span class="toc-section-number">11.4.1</span> Visualize the sampling distribution</a></li>
</ul></li>
<li><a href="sem-page.html#sem_page" id="toc-sem_page"><span class="toc-section-number">11.5</span> Standard error of the mean</a></li>
<li><a href="confint-rough.html#confint_rough" id="toc-confint_rough"><span class="toc-section-number">11.6</span> Rule of thumb 95% confidence interval</a></li>
</ul></li>
<li><a href="hypothesis.html#hypothesis" id="toc-hypothesis"><span class="toc-section-number">12</span> Hypothesis testing</a>
<ul>
<li><a href="hyp-packages-data.html#hyp_packages_data" id="toc-hyp_packages_data"><span class="toc-section-number">12.1</span> Load packages and import data</a></li>
<li><a href="hyp-steps.html#hyp_steps" id="toc-hyp_steps"><span class="toc-section-number">12.2</span> Steps to hypothesis testing</a></li>
<li><a href="hyp-example.html#hyp_example" id="toc-hyp_example"><span class="toc-section-number">12.3</span> An hypothesis test example</a>
<ul>
<li><a href="hyp-example.html#follow_hyp_steps" id="toc-follow_hyp_steps"><span class="toc-section-number">12.3.1</span> Following the steps to hypothesis testing</a></li>
<li><a href="hyp-example.html#sim_null" id="toc-sim_null"><span class="toc-section-number">12.3.2</span> Simulating a “null distribution”</a></li>
<li><a href="hyp-example.html#calc_p" id="toc-calc_p"><span class="toc-section-number">12.3.3</span> Calculating the <em>P</em>-value</a></li>
<li><a href="hyp-example.html#concluding_statement" id="toc-concluding_statement"><span class="toc-section-number">12.3.4</span> Writing a concluding statement</a></li>
</ul></li>
</ul></li>
<li><a href="single-cat.html#single_cat" id="toc-single_cat"><span class="toc-section-number">13</span> Analyzing a single categorical variable</a>
<ul>
<li><a href="singcat-packages-data.html#singcat_packages_data" id="toc-singcat_packages_data"><span class="toc-section-number">13.1</span> Load packages and import data</a></li>
<li><a href="estproportions.html#estproportions" id="toc-estproportions"><span class="toc-section-number">13.2</span> Estimating proportions</a>
<ul>
<li><a href="estproportions.html#sterr_prop" id="toc-sterr_prop"><span class="toc-section-number">13.2.1</span> Standard error for a proportion</a></li>
<li><a href="estproportions.html#confint_prop" id="toc-confint_prop"><span class="toc-section-number">13.2.2</span> Confidence interval for a proportion</a></li>
</ul></li>
<li><a href="binomdist.html#binomdist" id="toc-binomdist"><span class="toc-section-number">13.3</span> Binomial distribution</a></li>
<li><a href="binom-test.html#binom_test" id="toc-binom_test"><span class="toc-section-number">13.4</span> Binomial test</a></li>
<li><a href="prophypconf.html#prophypconf" id="toc-prophypconf"><span class="toc-section-number">13.5</span> Confidence interval approach to hypothesis testing</a></li>
<li><a href="GOF-test.html#GOF_test" id="toc-GOF_test"><span class="toc-section-number">13.6</span> Goodness-of-fit tests</a></li>
</ul></li>
<li><a href="two-cat.html#two_cat" id="toc-two_cat"><span class="toc-section-number">14</span> Analyzing associations between two categorical variables</a>
<ul>
<li><a href="twocat-packages-data.html#twocat_packages_data" id="toc-twocat_packages_data"><span class="toc-section-number">14.1</span> Load packages and import data</a></li>
<li><a href="fishertest.html#fishertest" id="toc-fishertest"><span class="toc-section-number">14.2</span> Fisher’s Exact Test</a>
<ul>
<li><a href="fishertest.html#fisher_hyp" id="toc-fisher_hyp"><span class="toc-section-number">14.2.1</span> Hypothesis statement</a></li>
<li><a href="fishertest.html#show_cont_table" id="toc-show_cont_table"><span class="toc-section-number">14.2.2</span> Display a contingency table</a></li>
<li><a href="fishertest.html#show_mosaic" id="toc-show_mosaic"><span class="toc-section-number">14.2.3</span> Display a mosaic plot</a></li>
<li><a href="fishertest.html#do_fisher" id="toc-do_fisher"><span class="toc-section-number">14.2.4</span> Conduct the Fisher’s Exact Test</a></li>
</ul></li>
<li><a href="odds.html#odds" id="toc-odds"><span class="toc-section-number">14.3</span> Estimate the Odds of getting sick</a></li>
<li><a href="oddsratio.html#oddsratio" id="toc-oddsratio"><span class="toc-section-number">14.4</span> Estimate the odds ratio</a></li>
<li><a href="chisquare.html#chisquare" id="toc-chisquare"><span class="toc-section-number">14.5</span> <span class="math inline">\(\chi\)</span><sup>2</sup> Contingency Test</a>
<ul>
<li><a href="chisquare.html#chihyp" id="toc-chihyp"><span class="toc-section-number">14.5.1</span> Hypothesis statement</a></li>
<li><a href="chisquare.html#showwormcont" id="toc-showwormcont"><span class="toc-section-number">14.5.2</span> Display the contingency table</a></li>
<li><a href="chisquare.html#mosaicworm" id="toc-mosaicworm"><span class="toc-section-number">14.5.3</span> Visualize a mosaic plot</a></li>
<li><a href="chisquare.html#checkchiassum" id="toc-checkchiassum"><span class="toc-section-number">14.5.4</span> Check the assumptions</a></li>
<li><a href="chisquare.html#chiresults" id="toc-chiresults"><span class="toc-section-number">14.5.5</span> Get the results of the test</a></li>
</ul></li>
</ul></li>
<li><a href="single-numeric.html#single_numeric" id="toc-single_numeric"><span class="toc-section-number">15</span> Analyzing a single numerical variable</a>
<ul>
<li><a href="singlenum-packages-data.html#singlenum_packages_data" id="toc-singlenum_packages_data"><span class="toc-section-number">15.1</span> Load packages and import data</a></li>
<li><a href="onesamp-t-test.html#onesamp_t_test" id="toc-onesamp_t_test"><span class="toc-section-number">15.2</span> One-sample <em>t</em>-test</a>
<ul>
<li><a href="onesamp-t-test.html#onesamp_hyp" id="toc-onesamp_hyp"><span class="toc-section-number">15.2.1</span> Hypothesis statement</a></li>
<li><a href="onesamp-t-test.html#onesamp_assumptions" id="toc-onesamp_assumptions"><span class="toc-section-number">15.2.2</span> Assumptions of one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_graph" id="toc-onesamp_graph"><span class="toc-section-number">15.2.3</span> A graph to accompany a one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_test" id="toc-onesamp_test"><span class="toc-section-number">15.2.4</span> Conduct the one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_conclude" id="toc-onesamp_conclude"><span class="toc-section-number">15.2.5</span> Concluding statement for the one-sample <em>t</em>-test</a></li>
</ul></li>
<li><a href="t-confidence.html#t_confidence" id="toc-t_confidence"><span class="toc-section-number">15.3</span> Confidence intervals for <span class="math inline">\(\mu\)</span></a>
<ul>
<li><a href="t-confidence.html#conf_precision" id="toc-conf_precision"><span class="toc-section-number">15.3.1</span> Confidence interval as a measure of precision for an estimate</a></li>
<li><a href="t-confidence.html#conf_hyp" id="toc-conf_hyp"><span class="toc-section-number">15.3.2</span> Confidence interval approach to hypothesis testing</a></li>
</ul></li>
</ul></li>
<li><a href="compare-two-means.html#compare_two_means" id="toc-compare_two_means"><span class="toc-section-number">16</span> Comparing means among two groups</a>
<ul>
<li><a href="twomean-packages-data.html#twomean_packages_data" id="toc-twomean_packages_data"><span class="toc-section-number">16.1</span> Load packages and import data</a></li>
<li><a href="paired-t-test.html#paired-t-test" id="toc-paired-t-test"><span class="toc-section-number">16.2</span> Paired <em>t</em>-test</a>
<ul>
<li><a href="paired-t-test.html#calc_diffs" id="toc-calc_diffs"><span class="toc-section-number">16.2.1</span> Calculate differences</a></li>
<li><a href="paired-t-test.html#paired_Htest" id="toc-paired_Htest"><span class="toc-section-number">16.2.2</span> Hypothesis statement</a></li>
<li><a href="paired-t-test.html#graph_paried" id="toc-graph_paried"><span class="toc-section-number">16.2.3</span> A graph to accompany a paired <em>t</em>-test</a></li>
<li><a href="paired-t-test.html#assump_paried" id="toc-assump_paried"><span class="toc-section-number">16.2.4</span> Assumptions of the paired <em>t</em>-test</a></li>
<li><a href="paired-t-test.html#conduct_paired" id="toc-conduct_paired"><span class="toc-section-number">16.2.5</span> Conduct the test</a></li>
<li><a href="paired-t-test.html#concl_paired" id="toc-concl_paired"><span class="toc-section-number">16.2.6</span> Concluding statement</a></li>
</ul></li>
<li><a href="twosamp-ttest.html#twosamp_ttest" id="toc-twosamp_ttest"><span class="toc-section-number">16.3</span> Two sample <em>t</em>-test</a>
<ul>
<li><a href="twosamp-ttest.html#twosamp_hyp" id="toc-twosamp_hyp"><span class="toc-section-number">16.3.1</span> Hypothesis statement</a></li>
<li><a href="twosamp-ttest.html#stats_2samp" id="toc-stats_2samp"><span class="toc-section-number">16.3.2</span> A table of descriptive statistics</a></li>
<li><a href="twosamp-ttest.html#graph_2samp" id="toc-graph_2samp"><span class="toc-section-number">16.3.3</span> A graph to accompany a 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#twosamp_assump" id="toc-twosamp_assump"><span class="toc-section-number">16.3.4</span> Assumptions of the 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#conduct_2samptest" id="toc-conduct_2samptest"><span class="toc-section-number">16.3.5</span> Conduct the 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#concl_2samp" id="toc-concl_2samp"><span class="toc-section-number">16.3.6</span> Concluding statement</a></li>
</ul></li>
<li><a href="assumpbad-2samp.html#assumpbad_2samp" id="toc-assumpbad_2samp"><span class="toc-section-number">16.4</span> When assumptions aren’t met</a></li>
</ul></li>
<li><a href="compare-three-more-means.html#compare_three_more_means" id="toc-compare_three_more_means"><span class="toc-section-number">17</span> Comparing means among more than two groups</a>
<ul>
<li><a href="anova-packages-data.html#anova_packages_data" id="toc-anova_packages_data"><span class="toc-section-number">17.1</span> Load packages and import data</a></li>
<li><a href="do-the-anova.html#do_the_anova" id="toc-do_the_anova"><span class="toc-section-number">17.2</span> Analysis of variance</a>
<ul>
<li><a href="do-the-anova.html#anova_hyps" id="toc-anova_hyps"><span class="toc-section-number">17.2.1</span> Hypothesis statements</a></li>
<li><a href="do-the-anova.html#stats_anova" id="toc-stats_anova"><span class="toc-section-number">17.2.2</span> A table of descriptive statistics</a></li>
<li><a href="do-the-anova.html#anova_graph1" id="toc-anova_graph1"><span class="toc-section-number">17.2.3</span> Visualize the data</a></li>
<li><a href="do-the-anova.html#assump_anova" id="toc-assump_anova"><span class="toc-section-number">17.2.4</span> Assumptions of ANOVA</a></li>
<li><a href="do-the-anova.html#do_anova1" id="toc-do_anova1"><span class="toc-section-number">17.2.5</span> Conduct the ANOVA test</a></li>
<li><a href="do-the-anova.html#createanovatable" id="toc-createanovatable"><span class="toc-section-number">17.2.6</span> Generate nice ANOVA table</a></li>
<li><a href="do-the-anova.html#calculate-r2-for-the-anova" id="toc-calculate-r2-for-the-anova"><span class="toc-section-number">17.2.7</span> Calculate <span class="math inline">\(R^2\)</span> for the ANOVA</a></li>
<li><a href="do-the-anova.html#tukey" id="toc-tukey"><span class="toc-section-number">17.2.8</span> Tukey-Kramer post-hoc test</a></li>
<li><a href="do-the-anova.html#vis_tukey" id="toc-vis_tukey"><span class="toc-section-number">17.2.9</span> Visualizing post-hoc test results</a></li>
<li><a href="do-the-anova.html#anova_conclusion" id="toc-anova_conclusion"><span class="toc-section-number">17.2.10</span> Concluding statement</a></li>
</ul></li>
<li><a href="assumpbad-anova.html#assumpbad_anova" id="toc-assumpbad_anova"><span class="toc-section-number">17.3</span> When assumptions aren’t met</a></li>
</ul></li>
<li><a href="two-num.html#two_num" id="toc-two_num"><span class="toc-section-number">18</span> Analyzing associations between two numerical variables</a>
<ul>
<li><a href="twonum-packages-data.html#twonum_packages_data" id="toc-twonum_packages_data"><span class="toc-section-number">18.1</span> Load packages and import data</a></li>
<li><a href="pearson.html#pearson" id="toc-pearson"><span class="toc-section-number">18.2</span> Pearson correlation analysis</a>
<ul>
<li><a href="pearson.html#pearson_hyp" id="toc-pearson_hyp"><span class="toc-section-number">18.2.1</span> Hypothesis statements</a></li>
<li><a href="pearson.html#see_corr" id="toc-see_corr"><span class="toc-section-number">18.2.2</span> Visualize the data</a></li>
<li><a href="pearson.html#corr_assumptions" id="toc-corr_assumptions"><span class="toc-section-number">18.2.3</span> Assumptions of correlation analysis</a></li>
<li><a href="pearson.html#do_corr" id="toc-do_corr"><span class="toc-section-number">18.2.4</span> Conduct the correlation analysis</a></li>
<li><a href="pearson.html#concl_corr" id="toc-concl_corr"><span class="toc-section-number">18.2.5</span> Concluding statement</a></li>
</ul></li>
<li><a href="rankcorr.html#rankcorr" id="toc-rankcorr"><span class="toc-section-number">18.3</span> Rank correlation (Spearman’s correlation)</a>
<ul>
<li><a href="rankcorr.html#hypothesis-statements" id="toc-hypothesis-statements"><span class="toc-section-number">18.3.1</span> Hypothesis statements</a></li>
<li><a href="rankcorr.html#spearman_hyp" id="toc-spearman_hyp"><span class="toc-section-number">18.3.2</span> Visualize the data</a></li>
<li><a href="rankcorr.html#assum_spear" id="toc-assum_spear"><span class="toc-section-number">18.3.3</span> Assumptions of Spearman rank correlation</a></li>
<li><a href="rankcorr.html#conduct_spearman" id="toc-conduct_spearman"><span class="toc-section-number">18.3.4</span> Conduct the test</a></li>
<li><a href="rankcorr.html#spear_conclude" id="toc-spear_conclude"><span class="toc-section-number">18.3.5</span> Concluding statement</a></li>
</ul></li>
</ul></li>
<li><a href="creating-tables-in-r-markdown.html#creating-tables-in-r-markdown" id="toc-creating-tables-in-r-markdown">Creating tables in R Markdown</a>
<ul>
<li><a href="tables-packages.html#tables_packages" id="toc-tables_packages"><span class="toc-section-number">18.4</span> Load packages and import data</a>
<ul>
<li><a href="tables-packages.html#skim_tables" id="toc-skim_tables"><span class="toc-section-number">18.4.1</span> Formatting output from the <code>skimr</code> package</a></li>
<li><a href="tables-packages.html#stats_nicetable" id="toc-stats_nicetable"><span class="toc-section-number">18.4.2</span> A nicely formatted table of descriptive statistics</a></li>
</ul></li>
</ul></li>
<li><a href="checking-assumptions-and-data-transformations.html#checking-assumptions-and-data-transformations" id="toc-checking-assumptions-and-data-transformations">Checking assumptions and data transformations</a>
<ul>
<li><a href="assumptions-packages-data.html#assumptions_packages_data" id="toc-assumptions_packages_data"><span class="toc-section-number">18.5</span> Load packages and import data</a></li>
<li><a href="checknorm-assum.html#checknorm_assum" id="toc-checknorm_assum"><span class="toc-section-number">18.6</span> Checking the normality assumption</a>
<ul>
<li><a href="checknorm-assum.html#quantile_plots" id="toc-quantile_plots"><span class="toc-section-number">18.6.1</span> Normal quantile plots</a></li>
<li><a href="checknorm-assum.html#shapirottest" id="toc-shapirottest"><span class="toc-section-number">18.6.2</span> Shapiro-Wilk test for normality</a></li>
</ul></li>
<li><a href="levenetest.html#levenetest" id="toc-levenetest"><span class="toc-section-number">18.7</span> Checking the equal-variance assumption</a></li>
<li><a href="transform.html#transform" id="toc-transform"><span class="toc-section-number">18.8</span> Data transformations</a>
<ul>
<li><a href="transform.html#log_transform" id="toc-log_transform"><span class="toc-section-number">18.8.1</span> Log-transform</a></li>
<li><a href="transform.html#zeroes" id="toc-zeroes"><span class="toc-section-number">18.8.2</span> Dealing with zeroes</a></li>
<li><a href="transform.html#logbases" id="toc-logbases"><span class="toc-section-number">18.8.3</span> Log bases</a></li>
<li><a href="transform.html#back_transform" id="toc-back_transform"><span class="toc-section-number">18.8.4</span> Back-transforming log data</a></li>
<li><a href="transform.html#logit_transform" id="toc-logit_transform"><span class="toc-section-number">18.8.5</span> Logit transform</a></li>
<li><a href="transform.html#logit_back" id="toc-logit_back"><span class="toc-section-number">18.8.6</span> Back-transforming logit data</a></li>
<li><a href="transform.html#when_back" id="toc-when_back"><span class="toc-section-number">18.8.7</span> When to back-transform?</a></li>
</ul></li>
</ul></li>
<li><a href="visual-markdown-editor.html#visual-markdown-editor" id="toc-visual-markdown-editor">Visual Markdown Editor</a>
<ul>
<li><a href="a-more-familiar-editing-environment.html#a-more-familiar-editing-environment" id="toc-a-more-familiar-editing-environment">A more familiar editing environment</a></li>
</ul></li>
<li><a href="common-errors-and-their-solutions.html#common-errors-and-their-solutions" id="toc-common-errors-and-their-solutions">Common errors and their solutions</a>
<ul>
<li><a href="google-can-help.html#google-can-help" id="toc-google-can-help">Google can help</a></li>
<li><a href="rtools-required-during-install.html#rtools-required-during-install" id="toc-rtools-required-during-install">Rtools required during install</a></li>
<li><a href="could-not-find-function.html#could-not-find-function" id="toc-could-not-find-function">Could not find function</a></li>
<li><a href="there-is-no-package.html#there-is-no-package" id="toc-there-is-no-package">There is no package</a></li>
<li><a href="trying-to-use-cran-without-setting-a-mirror.html#trying-to-use-cran-without-setting-a-mirror" id="toc-trying-to-use-cran-without-setting-a-mirror">Trying to use CRAN without setting a mirror</a></li>
<li><a href="pdf-latex-is-not-found.html#pdf-latex-is-not-found" id="toc-pdf-latex-is-not-found">PDF Latex is not found</a></li>
<li><a href="error-in-parse.html#error-in-parse" id="toc-error-in-parse">Error in parse</a></li>
<li><a href="no-such-file-or-directory-exists.html#no-such-file-or-directory-exists" id="toc-no-such-file-or-directory-exists">No such file or directory exists</a></li>
<li><a href="messy-output-when-loading-packages.html#messy-output-when-loading-packages" id="toc-messy-output-when-loading-packages">Messy output when loading packages</a></li>
<li><a href="unused-argument.html#unused-argument" id="toc-unused-argument">Unused argument</a></li>
<li><a href="object-not-found.html#object-not-found" id="toc-object-not-found">Object not found</a></li>
<li><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html#figure-caption-doesnt-show-up-below-figure-in-knitted-document" id="toc-figure-caption-doesnt-show-up-below-figure-in-knitted-document">Figure caption doesn’t show up below figure in knitted document</a></li>
<li><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html#filename-directory-name-or-volume-label-syntax-is-incorrect" id="toc-filename-directory-name-or-volume-label-syntax-is-incorrect">Filename, directory name, or volume label syntax is incorrect</a></li>
<li><a href="installing-packages-there-is-a-binary-version-available.html#installing-packages-there-is-a-binary-version-available" id="toc-installing-packages-there-is-a-binary-version-available">Installing packages: there is a binary version available</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="do_the_anova" class="section level2" number="17.2">
<h2><span class="header-section-number">17.2</span> Analysis of variance</h2>
<p><strong>Follow these steps when conducting a <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Hypothesis-testing">hypothesis test</a>:</strong></p>
<ul>
<li>State the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Null-hypothesis">null</a> and <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Alternative-hypothesis">alternative</a> hypotheses<br />
</li>
<li>Set an <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Significance-level-($\alpha$)"><span class="math inline">\(\alpha\)</span> level </a></li>
<li>Identify the appropriate test &amp; provide rationale</li>
<li>Prepare an appropriately formatted table of descriptive statistics for the response variable grouped by the categories of the explanatory variable.<br />
</li>
<li>Visualize the data with a good graph and interpret the graph</li>
<li>Assumptions
<ul>
<li>state the assumptions of the test<br />
</li>
<li>use appropriate figures and / or tests to check whether the assumptions of the statistical test are met</li>
<li>transform data to meet assumptions if required</li>
<li>if assumptions can’t be met (e.g. after <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Data-transformation">transformation</a>), use non-parametric test and repeat steps 1 through 4</li>
</ul></li>
<li>Conduct the test, and report the test statistic and associated <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#P-value"><em>P</em>-value</a><br />
</li>
<li>Calculate and include a <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Confidence-interval">confidence interval</a> (e.g. for <em>t</em>-tests) or <span class="math inline">\(R^2\)</span> value (e.g. for ANOVA) when appropriate<br />
</li>
<li>Optionally, for ANOVA, conduct a “post-hoc” comparison of <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Mean">means</a> using “Tukey-Kramer post-hoc test”</li>
<li>Draw the appropriate conclusion and communicate it clearly</li>
</ul>
<p><strong>Additional steps are required for ANOVA tests</strong></p>
<ul>
<li>An appropriately formatted ANOVA results table</li>
<li>A good figure with results of <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Post-hoc-test"><strong>post-hoc tests</strong></a> included (if these tests were conducted)<br />
</li>
<li>Your concluding statement should refer to the ANOVA table, the new figure, and the <span class="math inline">\(R^2\)</span> value</li>
</ul>
<div id="anova_hyps" class="section level3" number="17.2.1">
<h3><span class="header-section-number">17.2.1</span> Hypothesis statements</h3>
<p>The null hypothesis of ANOVA is that the population means <span class="math inline">\(\mu_i\)</span> are the same for all treatments. Thus, for our current example in which melatonin production was measured among treatment groups:</p>
<p>H<sub>0</sub>: Mean melatonin production is equal among all treatment groups (<span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span>).<br />
H<sub>A</sub>: At least one treatment group’s mean is different from the others</p>
<p><strong>OR</strong></p>
<p>H<sub>A</sub>: Mean melatonin production is not equal among all treatment groups.</p>
<p>We’ll set <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>We’ll use a fixed-effects ANOVA, which uses the <span class="math inline">\(F\)</span> test statistic.</p>
</div>
<div id="stats_anova" class="section level3" number="17.2.2">
<h3><span class="header-section-number">17.2.2</span> A table of descriptive statistics</h3>
<p>In a previous <a href="desc-numeric-var-cat.html#desc_numeric_var_cat">tutorial</a> we learned how to calculate descriptive statistics for a numeric variable grouped by a categorical variable. In the <a href="twosamp-ttest.html#stats_2samp">comparing 2 means tutorial</a> we also learned how to use the <code>t.test</code> function to calculate confidence intervals for a numeric variable.</p>
<p>Let’s use all these skills to generate a table of summary statistics for the “shift” variable, grouped by “treatment”:</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="do-the-anova.html#cb339-1" aria-hidden="true" tabindex="-1"></a>circadian.stats <span class="ot">&lt;-</span> circadian <span class="sc">%&gt;%</span></span>
<span id="cb339-2"><a href="do-the-anova.html#cb339-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span></span>
<span id="cb339-3"><a href="do-the-anova.html#cb339-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb339-4"><a href="do-the-anova.html#cb339-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count =</span> <span class="fu">n</span>() <span class="sc">-</span> naniar<span class="sc">::</span><span class="fu">n_miss</span>(shift),</span>
<span id="cb339-5"><a href="do-the-anova.html#cb339-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count_NA =</span> naniar<span class="sc">::</span><span class="fu">n_miss</span>(shift), </span>
<span id="cb339-6"><a href="do-the-anova.html#cb339-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(shift, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb339-7"><a href="do-the-anova.html#cb339-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(shift, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb339-8"><a href="do-the-anova.html#cb339-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">SEM =</span> SD<span class="sc">/</span><span class="fu">sqrt</span>(Count),</span>
<span id="cb339-9"><a href="do-the-anova.html#cb339-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Low_95_CL =</span> <span class="fu">t.test</span>(shift, <span class="at">conf.level =</span> <span class="fl">0.95</span>)<span class="sc">$</span>conf.int[<span class="dv">1</span>],</span>
<span id="cb339-10"><a href="do-the-anova.html#cb339-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Up_95_CL =</span> <span class="fu">t.test</span>(shift, <span class="at">conf.level =</span> <span class="fl">0.95</span>)<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb339-11"><a href="do-the-anova.html#cb339-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="note">
<p><strong>NOTE: </strong>
Here we’ll use what we learned in the <a href="https://ubco-biology.github.io/BIOL202/creating-tables-in-r-markdown.html">Tables in markdown tutorial</a> on creating nicely formatted tables, including <strong>table headings</strong>.</p>
</div>
<p>Please consult the <a href="https://ubco-biology.github.io/BIOL202/creating-tables-in-r-markdown.html">Tables in Markdown</a> tutorial for more details.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="do-the-anova.html#cb340-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(circadian.stats, <span class="at">caption =</span> <span class="st">&quot;Descriptive statistics for the circadian rythm experiment data&quot;</span>, </span>
<span id="cb340-2"><a href="do-the-anova.html#cb340-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb340-3"><a href="do-the-anova.html#cb340-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;scale_down&quot;</span>, <span class="st">&quot;hold_position&quot;</span>), <span class="at">position =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:givenicepdftable2">Table 17.1: </span>Descriptive statistics for the circadian rythm experiment data
</caption>
<thead>
<tr>
<th style="text-align:left;">
treatment
</th>
<th style="text-align:right;">
Count
</th>
<th style="text-align:right;">
Count_NA
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
SEM
</th>
<th style="text-align:right;">
Low_95_CL
</th>
<th style="text-align:right;">
Up_95_CL
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Control
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
0.618
</td>
<td style="text-align:right;">
0.218
</td>
<td style="text-align:right;">
-0.825
</td>
<td style="text-align:right;">
0.208
</td>
</tr>
<tr>
<td style="text-align:left;">
Knees
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.34
</td>
<td style="text-align:right;">
0.791
</td>
<td style="text-align:right;">
0.299
</td>
<td style="text-align:right;">
-1.067
</td>
<td style="text-align:right;">
0.396
</td>
</tr>
<tr>
<td style="text-align:left;">
Eyes
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-1.55
</td>
<td style="text-align:right;">
0.706
</td>
<td style="text-align:right;">
0.267
</td>
<td style="text-align:right;">
-2.205
</td>
<td style="text-align:right;">
-0.898
</td>
</tr>
</tbody>
</table>
<div class="note">
<p><strong>IMPORTANT: </strong>
Notice that, unlike figure captions, which must be provided in the chunk header, the caption for a table is provided as an argument to the <code>kbl</code> function within the actual code!</p>
</div>
<p>Notice also that the ordering of the categories (also called the factor levels) is correct!</p>
</div>
<div id="anova_graph1" class="section level3" number="17.2.3">
<h3><span class="header-section-number">17.2.3</span> Visualize the data</h3>
<p>We are interested in visualizing a numeric response variable in relation to a categorical explanatory variable.</p>
<p>We learned in an earlier <a href="numeric-vs-cat.html#numeric_vs_cat">tutorial</a> that we can use a stripchart, violin plot, or boxplot to visualize a numerical response variable in relation to a categorical variable.</p>
<p>It is commonplace to use a stripchart for small sample sizes in each group.</p>
<p>We’ll use code we learned in an <a href="numeric-vs-cat.html#numeric_vs_cat">earlier tutorial</a>.</p>
<p>However, because we’re now not only describing and visualizing data, but also testing a hypothesis about differences in group means, it is best to add group means and error bars to our stripchart.</p>
<p>The <code>stat_summary</code> function from the <code>ggplot2</code> package is what provides the error bars and group means:</p>
<pre><code>?stat_summary</code></pre>
<p>Here’s the code:</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="do-the-anova.html#cb342-1" aria-hidden="true" tabindex="-1"></a>circadian <span class="sc">%&gt;%</span></span>
<span id="cb342-2"><a href="do-the-anova.html#cb342-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> shift)) <span class="sc">+</span></span>
<span id="cb342-3"><a href="do-the-anova.html#cb342-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb342-4"><a href="do-the-anova.html#cb342-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb342-5"><a href="do-the-anova.html#cb342-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">width =</span> <span class="fl">0.1</span>, </span>
<span id="cb342-6"><a href="do-the-anova.html#cb342-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb342-7"><a href="do-the-anova.html#cb342-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, </span>
<span id="cb342-8"><a href="do-the-anova.html#cb342-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, </span>
<span id="cb342-9"><a href="do-the-anova.html#cb342-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">position=</span><span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb342-10"><a href="do-the-anova.html#cb342-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Light treatment&quot;</span>) <span class="sc">+</span> </span>
<span id="cb342-11"><a href="do-the-anova.html#cb342-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Shift in circadian rhythm (h)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb342-12"><a href="do-the-anova.html#cb342-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span id="fig:stripanova"></span>
<img src="BIOL202-github_files/figure-html/stripanova-1.png" alt="Stripchart of phase shifts in the circadian rhythm of melatonin production in 22 participants of an experiment. Solid circles denote group means, and bars +/- one standard error" width="384" />
<p class="caption">
Figure 17.1: Stripchart of phase shifts in the circadian rhythm of melatonin production in 22 participants of an experiment. Solid circles denote group means, and bars +/- one standard error
</p>
</div>
<p>We’ve added two sets of <code>stat_summary</code> functions, one for adding the group mean, and one for adding the error bars.</p>
<ul>
<li>The argument “fun = mean_se” adds the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Standard-error">standard error</a> of the group means</li>
<li>the “geom = ‘errorbar’” tells ggplot to use an error bar format</li>
<li>the “position = position_nudge(x = 0.15)” tells ggplot to nudge the error bar off to the side a bit, so it doesn’t obscure the data points</li>
<li>the next <code>stat_summary</code> function is the same, but this time for the group means.</li>
</ul>
<p>Clearly there is no difference between the control and knee treatment groups, but we’ll have to await the results of the ANOVA to see whether the mean of the “eyes” group is different.</p>
<div id="visualizing-the-data-when-group-sample-sizes-are-large" class="section level4" number="17.2.3.1">
<h4><span class="header-section-number">17.2.3.1</span> Visualizing the data when group sample sizes are large</h4>
<p>Recall that we are focusing here on <strong>Fixed-effects ANOVA</strong> which generally apply to experiments. Experiments often don’t have very large sample sizes per group, but if they do, we can use a different graph to visualize the data.</p>
<p>We’ll use the “students” dataset to illustrate, but note that these data are NOT from an experiment.</p>
<p>We’ll create a violin plot, and superimpose the means and standard error bars:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="do-the-anova.html#cb343-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span> </span>
<span id="cb343-2"><a href="do-the-anova.html#cb343-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Dominant_eye, <span class="at">y =</span> height_cm)) <span class="sc">+</span></span>
<span id="cb343-3"><a href="do-the-anova.html#cb343-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb343-4"><a href="do-the-anova.html#cb343-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">width =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb343-5"><a href="do-the-anova.html#cb343-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb343-6"><a href="do-the-anova.html#cb343-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb343-7"><a href="do-the-anova.html#cb343-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, </span>
<span id="cb343-8"><a href="do-the-anova.html#cb343-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb343-9"><a href="do-the-anova.html#cb343-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Dominant eye&quot;</span>) <span class="sc">+</span></span>
<span id="cb343-10"><a href="do-the-anova.html#cb343-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Height (cm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb343-11"><a href="do-the-anova.html#cb343-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-94"></span>
<img src="BIOL202-github_files/figure-html/unnamed-chunk-94-1.png" alt="Violin plot of heights of students with right (n = 106) and left (n = 48) dominant eyes. Solid circles denote group means, and bars +/- one standard error." width="288" />
<p class="caption">
Figure 17.2: Violin plot of heights of students with right (n = 106) and left (n = 48) dominant eyes. Solid circles denote group means, and bars +/- one standard error.
</p>
</div>
<p>In this case we don’t need to nudge the means and error bars to the side.</p>
</div>
</div>
<div id="assump_anova" class="section level3" number="17.2.4">
<h3><span class="header-section-number">17.2.4</span> Assumptions of ANOVA</h3>
<p>The <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Assumptions">assumptions</a> of ANOVA are:</p>
<ul>
<li>The measurements in every group represent a random sample from the corresponding population (<strong>NOTE</strong>: for an experimental study, the assumption is that subjects are randomly assigned to treatments)<br />
</li>
<li>The response variable has a normal distribution in each population</li>
<li>The <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Variance">variance</a> of the response variable is the same in all populations (called the “homogeneity of variance” assumption)</li>
</ul>
<hr />
<p><strong>Test for normality</strong></p>
<p>The sample sizes per group are rather small, so graphical aids such as histograms or normal quantile plots will not be particularly helpful.</p>
<p>Instead, let’s rely on the fact that (i) the strip chart in Figure 2 does not show any obvious outliers in any of the groups, and (ii) the central limit theorem makes ANOVAs quite robust to deviations in normality, especially with larger sample sizes, but even with relatively small sample sizes such as these. So, we’ll proceed under the assumption that the measurements are normally distributed within the three populations.</p>
<hr />
<p><strong>Test for equal variances</strong></p>
<p>Now we need to test the assumption of equal variance among the groups, using Levene’s Test as we learned in the <a href="https://ubco-biology.github.io/BIOL202/checking-assumptions-and-data-transformations.html">checking assumptions</a> tutorial.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="do-the-anova.html#cb344-1" aria-hidden="true" tabindex="-1"></a>variance.check <span class="ot">&lt;-</span> <span class="fu">leveneTest</span>(shift <span class="sc">~</span> treatment, <span class="at">data =</span> circadian)</span>
<span id="cb344-2"><a href="do-the-anova.html#cb344-2" aria-hidden="true" tabindex="-1"></a>variance.check</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.1586 0.8545
##       19</code></pre>
<p>We see that the <em>P</em>-value for the test is much greater than 0.05, so the null hypothesis of equal variance is not rejected. There is no evidence against the assumption that the variances are equal.</p>
<p>A reasonable statement:</p>
<p>“A Levene’s test showed no evidence against the assumption of equal variance (<em>F</em> = 0.16; <em>P</em>-value = 0.854).”</p>
<p><strong>IF assumptions are not met</strong></p>
<p>A later <a href="assumpbad-anova.html#assumpbad_anova">section</a> discusses what to do if assumptions are NOT met.</p>
</div>
<div id="do_anova1" class="section level3" number="17.2.5">
<h3><span class="header-section-number">17.2.5</span> Conduct the ANOVA test</h3>
<p>There are two steps to conducting an ANOVA in R:</p>
<ul>
<li><p>Use the <code>lm</code> function (from the base package) (it stands for “linear model”) to create an object that holds the key output from the test</p></li>
<li><p>Use the <code>anova</code> function (from the base package) on the preceding <code>lm</code> output object to generate the appropriate output for interpreting the results.</p></li>
</ul>
<p>The <code>lm</code> function uses the syntax: Y ~ X.</p>
<p>Let’s do this step first:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="do-the-anova.html#cb346-1" aria-hidden="true" tabindex="-1"></a>circadian.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(shift <span class="sc">~</span> treatment, <span class="at">data =</span> circadian) </span></code></pre></div>
<p>Next the <code>anova</code> step:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="do-the-anova.html#cb347-1" aria-hidden="true" tabindex="-1"></a>circadian.lm.anova <span class="ot">&lt;-</span> <span class="fu">anova</span>(circadian.lm)</span></code></pre></div>
<p>Let’s have a look at what this produced:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="do-the-anova.html#cb348-1" aria-hidden="true" tabindex="-1"></a>circadian.lm.anova</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: shift
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## treatment  2 7.2245  3.6122  7.2894 0.004472 **
## Residuals 19 9.4153  0.4955                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This is not in the format of a traditional ANOVA table (as described in Chapter 15 of the text): it is missing the “Total” row, and it puts the degrees of freedom (df) column before the Sums of Squares. Also, the column headers could be more informative.</p>
<p>Below we create our own function that takes the preceding object and generates an appropriately formatted ANOVA table .</p>
<p><strong>NOTE</strong>: These instructions are for a so-called <strong>one-way ANOVA</strong>, in which there is only one categorical variable against which a numerical variable is being analyzed. In the present case, we are analyzing a response variable in relation to the “treatment” categorical variable, which has 3 categories or “levels”.</p>
</div>
<div id="createanovatable" class="section level3" number="17.2.6">
<h3><span class="header-section-number">17.2.6</span> Generate nice ANOVA table</h3>
<p>Let’s look again at the raw output from the <code>anova</code> function:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="do-the-anova.html#cb350-1" aria-hidden="true" tabindex="-1"></a>circadian.lm.anova</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: shift
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## treatment  2 7.2245  3.6122  7.2894 0.004472 **
## Residuals 19 9.4153  0.4955                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the code chunk below we create a new function called “create.anova.table”, which we can use to convert an “anova” object (like the one above) to an appropriately formatted ANOVA table.</p>
<p>When you run this code chunk, it creates the function in your workspace. Once it is created, you can use it.</p>
<div class="note">
<p><strong>NOTE:</strong>
You will need to run this chunk to create the function each time you start a new R session.</p>
</div>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="do-the-anova.html#cb352-1" aria-hidden="true" tabindex="-1"></a>create.anova.table <span class="ot">&lt;-</span> <span class="cf">function</span>(intable){</span>
<span id="cb352-2"><a href="do-the-anova.html#cb352-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># first check that input table is of class &quot;anova&quot;</span></span>
<span id="cb352-3"><a href="do-the-anova.html#cb352-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">class</span>(intable)[<span class="dv">1</span>] <span class="sc">!=</span> <span class="st">&quot;anova&quot;</span>) <span class="fu">stop</span>(<span class="st">&quot;Input object not of class &#39;anova&#39;&quot;</span>)</span>
<span id="cb352-4"><a href="do-the-anova.html#cb352-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(tidyverse) <span class="co"># ensure tidyverse is loaded</span></span>
<span id="cb352-5"><a href="do-the-anova.html#cb352-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(broom) <span class="co"># ensures broom is loaded</span></span>
<span id="cb352-6"><a href="do-the-anova.html#cb352-6" aria-hidden="true" tabindex="-1"></a>  tidy.intable <span class="ot">&lt;-</span> <span class="fu">tidy</span>(intable)</span>
<span id="cb352-7"><a href="do-the-anova.html#cb352-7" aria-hidden="true" tabindex="-1"></a><span class="co"># &quot;intable&quot; is a the object from the `anova` output</span></span>
<span id="cb352-8"><a href="do-the-anova.html#cb352-8" aria-hidden="true" tabindex="-1"></a>  temp.anova <span class="ot">&lt;-</span> tidy.intable <span class="sc">%&gt;%</span></span>
<span id="cb352-9"><a href="do-the-anova.html#cb352-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;sumsq&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;meansq&quot;</span>, <span class="st">&quot;statistic&quot;</span>, <span class="st">&quot;p.value&quot;</span>)  <span class="co"># reorder columns</span></span>
<span id="cb352-10"><a href="do-the-anova.html#cb352-10" aria-hidden="true" tabindex="-1"></a>  temp.anova <span class="ot">&lt;-</span> temp.anova <span class="sc">%&gt;%</span></span>
<span id="cb352-11"><a href="do-the-anova.html#cb352-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">Source =</span> term, <span class="at">SS =</span> sumsq, <span class="at">MS =</span> meansq, <span class="at">F =</span> statistic, <span class="at">P_val =</span> p.value) <span class="co"># rename columns</span></span>
<span id="cb352-12"><a href="do-the-anova.html#cb352-12" aria-hidden="true" tabindex="-1"></a>totals <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb352-13"><a href="do-the-anova.html#cb352-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Source =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb352-14"><a href="do-the-anova.html#cb352-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> <span class="fu">sum</span>(temp.anova<span class="sc">$</span>df),</span>
<span id="cb352-15"><a href="do-the-anova.html#cb352-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">SS =</span> <span class="fu">sum</span>(temp.anova<span class="sc">$</span>SS),</span>
<span id="cb352-16"><a href="do-the-anova.html#cb352-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">MS =</span> <span class="cn">NA</span>,</span>
<span id="cb352-17"><a href="do-the-anova.html#cb352-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">F =</span> <span class="cn">NA</span>,</span>
<span id="cb352-18"><a href="do-the-anova.html#cb352-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_val =</span> <span class="cn">NA</span></span>
<span id="cb352-19"><a href="do-the-anova.html#cb352-19" aria-hidden="true" tabindex="-1"></a>)  <span class="co"># calculate totals</span></span>
<span id="cb352-20"><a href="do-the-anova.html#cb352-20" aria-hidden="true" tabindex="-1"></a>  nice.anova.table <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">rbind</span>(temp.anova, totals)) <span class="co"># generate table</span></span>
<span id="cb352-21"><a href="do-the-anova.html#cb352-21" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(nice.anova.table)</span>
<span id="cb352-22"><a href="do-the-anova.html#cb352-22" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><strong>NOTE</strong>: this is a quick-and-dirty function that does <strong>NOT</strong> follow all the best practices in coding!</p>
<p>Let’s try out the function, using our original anova table:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="do-the-anova.html#cb353-1" aria-hidden="true" tabindex="-1"></a>nice.anova.table <span class="ot">&lt;-</span> <span class="fu">create.anova.table</span>(circadian.lm.anova)</span>
<span id="cb353-2"><a href="do-the-anova.html#cb353-2" aria-hidden="true" tabindex="-1"></a>nice.anova.table</span></code></pre></div>
<pre><code>## # A tibble: 3 × 6
##   Source        SS    df      MS      F     P_val
##   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 treatment  7.224     2  3.612   7.289  0.004472
## 2 Residuals  9.415    19  0.4955 NA     NA       
## 3 Total     16.64     21 NA      NA     NA</code></pre>
<p>It worked!</p>
<p><strong>Generate nice output using <code>kable</code></strong></p>
<p>To generate a nice table that will export to PDF properly, we’ll follow what we learned in the <a href="https://ubco-biology.github.io/BIOL202/creating-tables-in-r-markdown.html">Tables in markdown tutorial</a> on creating nicely formatted tables, including <strong>table headings</strong>.</p>
<p>Here’s the required code.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="do-the-anova.html#cb355-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">knitr.kable.NA =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb355-2"><a href="do-the-anova.html#cb355-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(nice.anova.table, <span class="at">caption =</span> <span class="st">&quot;ANOVA table for the circadian rythm experiment.&quot;</span>, </span>
<span id="cb355-3"><a href="do-the-anova.html#cb355-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>), <span class="at">align =</span> <span class="st">&quot;r&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb355-4"><a href="do-the-anova.html#cb355-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:niceanovapdf">Table 17.2: </span>ANOVA table for the circadian rythm experiment.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Source
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
P_val
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
treatment
</td>
<td style="text-align:right;">
7.2245
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3.6122
</td>
<td style="text-align:right;">
7.2894
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:right;">
Residuals
</td>
<td style="text-align:right;">
9.4153
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0.4955
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
Total
</td>
<td style="text-align:right;">
16.6398
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<p>We have two new pieces of code:</p>
<ul>
<li>the first line of code [options(knitr.kable.NA = ’’)] tells the <code>kbl</code> function to hide any “NA” values; we need this because parts of our table have NAs</li>
<li>the argument “align = ‘r’” in the <code>kbl</code> function tells it to align the text right</li>
</ul>
<p>We can now refer to this nice table in our concluding statement, and if the table is appropriately formatted like this one, you can simply refer to the Table rather than including all the additional details in your concluding statement (see below).</p>
</div>
<div id="calculate-r2-for-the-anova" class="section level3" number="17.2.7">
<h3><span class="header-section-number">17.2.7</span> Calculate <span class="math inline">\(R^2\)</span> for the ANOVA</h3>
<p>One measure that is typically reported with any “linear model” like ANOVA is the “variance explained” or <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Coefficient-of-determination-(R<sup>2</sup>)"><strong>coefficient of determination</strong></a>, denoted <span class="math inline">\(R^2\)</span>.</p>
<p>This value indicates the fraction of the variation in <em>Y</em> that is explained by groups.</p>
<p>The remainder of the variation (<span class="math inline">\(1 - R^2\)</span>) is “error”, or variation that is left unexplained by the groups.</p>
<p>To calculate this we use two steps, and we go back to our original “lm” object we created earlier:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="do-the-anova.html#cb356-1" aria-hidden="true" tabindex="-1"></a>circadian.lm.summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(circadian.lm)</span>
<span id="cb356-2"><a href="do-the-anova.html#cb356-2" aria-hidden="true" tabindex="-1"></a>circadian.lm.summary<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.4341684</code></pre>
<p>We’ll refer to this value in our concluding statement.</p>
<p>Before we get there, we need to figure out <strong>which group mean(s) differ??</strong>.</p>
</div>
<div id="tukey" class="section level3" number="17.2.8">
<h3><span class="header-section-number">17.2.8</span> Tukey-Kramer post-hoc test</h3>
<p>As described in Chapter 15 in the text, <strong>planned comparisons</strong> (aka planned contrasts) are ideal and most powerful, but unfortunately we often need to conduct <strong>unplanned comparisons</strong> to assess which groups differ in our ANOVA test. This is what we’ll learn here.</p>
<p>We can guess from our stripchart (Figure <a href="do-the-anova.html#fig:stripanova">17.1</a>) that it’s the “Eyes” treatment group that differs from the others, but we need a formal test.</p>
<p>We could simply conduct three 2-sample <em>t</em>-tests on each of the three pair-wise comparisons, but then we would inflate our <strong>Type-I error rate</strong>, due to multiple-testing.</p>
<p>The Tukey-Kramer “post-hoc” (unplanned) test adjusts our <em>P</em>-values correctly to account for multiple tests.</p>
<p>For this test we use the <code>TukeyHSD</code> function in the base stats package (HSD stands for “Honestly Significant Difference”).</p>
<pre><code>?TukeyHSD</code></pre>
<p>The one catch in using this function is that we need to re-do our ANOVA analysis using a different function… the <code>aov</code> function in lieu of the <code>lm</code> function. This is necessary because the <code>TukeyHSD</code> function is expecting a particular object format, which only the <code>aov</code> function provides.</p>
<p>First, let’s re-do the ANOVA analysis using the <code>aov</code> function, creating a new object. <strong>NOTE</strong> This is only necessary if you are wishing to conduct the post-hoc Tukey HSD analysis (which we often are).</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="do-the-anova.html#cb359-1" aria-hidden="true" tabindex="-1"></a>circadian.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(shift <span class="sc">~</span> treatment, <span class="at">data =</span> circadian)</span></code></pre></div>
<p>Now we can pass this object to the <code>TukeyHSD</code> function, and use the appropriate confidence level (corresponding to 1 minus alpha):</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="do-the-anova.html#cb360-1" aria-hidden="true" tabindex="-1"></a>circadianTukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(circadian.aov, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<p>And let’s make the output <code>tidy</code>:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="do-the-anova.html#cb361-1" aria-hidden="true" tabindex="-1"></a>circadianTukey.tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(circadianTukey)</span></code></pre></div>
<p>Have a look a the output:</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="do-the-anova.html#cb362-1" aria-hidden="true" tabindex="-1"></a>circadianTukey.tidy</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   term      contrast      null.value estimate conf.low conf.high adj.p.value
##   &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 treatment Knees-Control          0 -0.02696  -0.9525    0.8986    0.9970  
## 2 treatment Eyes-Control           0 -1.243    -2.168    -0.3171    0.007866
## 3 treatment Eyes-Knees             0 -1.216    -2.172    -0.2598    0.01168</code></pre>
<p>Now let’s reformat this table for producing a nice output.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="do-the-anova.html#cb364-1" aria-hidden="true" tabindex="-1"></a>circadianTukey.tidy.table <span class="ot">&lt;-</span> circadianTukey.tidy <span class="sc">%&gt;%</span></span>
<span id="cb364-2"><a href="do-the-anova.html#cb364-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(term, null.value)) <span class="sc">%&gt;%</span>  <span class="co"># take away these two columns</span></span>
<span id="cb364-3"><a href="do-the-anova.html#cb364-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Contrast =</span> <span class="st">&quot;contrast&quot;</span>, <span class="at">Difference =</span> <span class="st">&quot;estimate&quot;</span>, </span>
<span id="cb364-4"><a href="do-the-anova.html#cb364-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Conf_low =</span> <span class="st">&quot;conf.low&quot;</span>, <span class="at">Conf_high =</span> <span class="st">&quot;conf.high&quot;</span>, </span>
<span id="cb364-5"><a href="do-the-anova.html#cb364-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Adj_Pval =</span> <span class="st">&quot;adj.p.value&quot;</span>)</span></code></pre></div>
<p>Now we can produce a nice output, which <strong>is entirely optional</strong>:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="do-the-anova.html#cb365-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(circadianTukey.tidy.table, </span>
<span id="cb365-2"><a href="do-the-anova.html#cb365-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Results of a Tukey-Kramer post-hoc test for the circadian rythm experiment.&quot;</span>, </span>
<span id="cb365-3"><a href="do-the-anova.html#cb365-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>), <span class="at">align =</span> <span class="st">&quot;r&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb365-4"><a href="do-the-anova.html#cb365-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:niceTukeytable">Table 17.3: </span>Results of a Tukey-Kramer post-hoc test for the circadian rythm experiment.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Contrast
</th>
<th style="text-align:right;">
Difference
</th>
<th style="text-align:right;">
Conf_low
</th>
<th style="text-align:right;">
Conf_high
</th>
<th style="text-align:right;">
Adj_Pval
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
Knees-Control
</td>
<td style="text-align:right;">
-0.027
</td>
<td style="text-align:right;">
-0.9525
</td>
<td style="text-align:right;">
0.8986
</td>
<td style="text-align:right;">
0.997
</td>
</tr>
<tr>
<td style="text-align:right;">
Eyes-Control
</td>
<td style="text-align:right;">
-1.243
</td>
<td style="text-align:right;">
-2.1682
</td>
<td style="text-align:right;">
-0.3171
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:right;">
Eyes-Knees
</td>
<td style="text-align:right;">
-1.216
</td>
<td style="text-align:right;">
-2.1716
</td>
<td style="text-align:right;">
-0.2598
</td>
<td style="text-align:right;">
0.012
</td>
</tr>
</tbody>
</table>
<p>The output clearly shows the pairwise comparisons and associated <em>P</em>-values, <strong>adjusted</strong> for multiple comparisons. It also shows the difference in means, and the lower and upper 95% confidence interval for the differences.</p>
<p>We can see that the mean for the “Eyes” treatment group differs significantly (at <span class="math inline">\(\alpha= 0.05\)</span>) from each of the other group means.</p>
<p>One typically shows these results visually on the same figure used to display the data (here, Figure <a href="do-the-anova.html#fig:stripanova">17.1</a>).</p>
</div>
<div id="vis_tukey" class="section level3" number="17.2.9">
<h3><span class="header-section-number">17.2.9</span> Visualizing post-hoc test results</h3>
<p>Here is our original figure, to which we’ll add the results of the post-hoc test:</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="do-the-anova.html#cb366-1" aria-hidden="true" tabindex="-1"></a>circadian <span class="sc">%&gt;%</span></span>
<span id="cb366-2"><a href="do-the-anova.html#cb366-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> shift)) <span class="sc">+</span></span>
<span id="cb366-3"><a href="do-the-anova.html#cb366-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb366-4"><a href="do-the-anova.html#cb366-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb366-5"><a href="do-the-anova.html#cb366-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">width =</span> <span class="fl">0.1</span>, </span>
<span id="cb366-6"><a href="do-the-anova.html#cb366-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb366-7"><a href="do-the-anova.html#cb366-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, </span>
<span id="cb366-8"><a href="do-the-anova.html#cb366-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, </span>
<span id="cb366-9"><a href="do-the-anova.html#cb366-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">position=</span><span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb366-10"><a href="do-the-anova.html#cb366-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Light treatment&quot;</span>) <span class="sc">+</span> </span>
<span id="cb366-11"><a href="do-the-anova.html#cb366-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Shift in circadian rhythm (h)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb366-12"><a href="do-the-anova.html#cb366-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span id="fig:stripanova2"></span>
<img src="BIOL202-github_files/figure-html/stripanova2-1.png" alt="Stripchart of phase shifts in the circadian rhythm of melatonin production in 22 participants of an experiment. Solid circles denote group means, and bars +/- one standard error" width="384" />
<p class="caption">
Figure 17.3: Stripchart of phase shifts in the circadian rhythm of melatonin production in 22 participants of an experiment. Solid circles denote group means, and bars +/- one standard error
</p>
</div>
<p>To visualize the outcomes of the Tukey-Kramer post-hoc test, we superimpose a text letter alongside (or above) each group in the figure, such that groups sharing the same letter are not significantly different according to the Tukey-Kramer post-hoc test.</p>
<p>For this we use the <code>annotate</code> function, and this requires that we know the coordinates on the graph where we wish to place our annotations.</p>
<p>Based on our stripchart above, it looks like we need to use Y-value coordinates of around 1.1 to place our letters above each group. <strong>It may take some trial-and-error</strong> to figure this out.</p>
<p>Here’s the code, with the <code>annotate</code> function added:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="do-the-anova.html#cb367-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(circadian, <span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> shift)) <span class="sc">+</span></span>
<span id="cb367-2"><a href="do-the-anova.html#cb367-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb367-3"><a href="do-the-anova.html#cb367-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb367-4"><a href="do-the-anova.html#cb367-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">width =</span> <span class="fl">0.1</span>, </span>
<span id="cb367-5"><a href="do-the-anova.html#cb367-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">position=</span><span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb367-6"><a href="do-the-anova.html#cb367-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, </span>
<span id="cb367-7"><a href="do-the-anova.html#cb367-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, </span>
<span id="cb367-8"><a href="do-the-anova.html#cb367-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">position=</span><span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.15</span>)) <span class="sc">+</span></span>
<span id="cb367-9"><a href="do-the-anova.html#cb367-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.1</span>, <span class="fl">1.2</span>)) <span class="sc">+</span></span>
<span id="cb367-10"><a href="do-the-anova.html#cb367-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">y =</span> <span class="fl">1.1</span>, <span class="at">label =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>)) <span class="sc">+</span></span>
<span id="cb367-11"><a href="do-the-anova.html#cb367-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Light treatment&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Shift in circadian rhythm (h)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb367-12"><a href="do-the-anova.html#cb367-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span id="fig:stripanovatukey"></span>
<img src="BIOL202-github_files/figure-html/stripanovatukey-1.png" alt="Stripchart showing the phase shift in the circadian rhythm of melatonin production in 22 experimental participants given alternative light treatments. Solid circles represent group means, and bars represent +/- one SE. Group means sharing the same letter are not significantly different according to the Tukey-Kramer post-hoc test (family-wise $\alpha$ = 0.05)." width="384" />
<p class="caption">
Figure 17.4: Stripchart showing the phase shift in the circadian rhythm of melatonin production in 22 experimental participants given alternative light treatments. Solid circles represent group means, and bars represent +/- one SE. Group means sharing the same letter are not significantly different according to the Tukey-Kramer post-hoc test (family-wise <span class="math inline">\(\alpha\)</span> = 0.05).
</p>
</div>
<p>Notice that we have added a line including the <code>ylim</code> function, so that we can specify the min and max y-axis limits, ensuring that our annotation letters fit on the graph.</p>
<p><strong>NOTE</strong>: The chunk option I included to get the figure heading shown above is as follows:</p>
<pre><code>{r fig.cap = &quot;Stripchart showing the phase shift in the circadian rhythm of melatonin production in 22 experimental participants given alternative light treatments. Solid circles represent group means, and bars represent +/- one SE. Group means sharing the same letter are not significantly different according to the Tukey-Kramer post-hoc test (family-wise $\\alpha$ = 0.05).&quot;, fig.width = 4, fig.height = 4.5}</code></pre>
<p>The “family-wise” <span class="math inline">\(\alpha\)</span> statement means that the Tukey-Kramer test uses our initial <span class="math inline">\(\alpha\)</span> level, but ensures that the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Probability">probability</a> of making at least one Type-1 error throughout the course of testing all pairs of means is no greater than the originally stated <span class="math inline">\(\alpha\)</span> level.</p>
<div class="note">
<p><strong>TIP:</strong>
Figure <a href="do-the-anova.html#fig:stripanovatukey">17.4</a> is the kind of figure that should be referenced, along with ANOVA table <a href="do-the-anova.html#tab:niceanovapdf">17.2</a>, when communicating your results of an ANOVA. For instance, with the results of the Tukey-Kramer post-hoc tests superimposed on the figure, you can not only state that the null hypothesis is rejected, but you can also state which group(s) differ from which others.</p>
</div>
<p>We are now able to write our truly final concluding statement, below.</p>
<hr />
<ol style="list-style-type: decimal">
<li>Annotating stripcharts</li>
</ol>
<p>Pretend that our post-hoc test showed that the “Knee” group was not different from either the control or the Eyes group. Re-do the figure above, but this time place an “ab” above the Knee group on the figure. This is how you would indicate that the control and eyes grouped differed significantly from one-another, but neither differed significantly from the Knee group.</p>
</div>
<div id="anova_conclusion" class="section level3" number="17.2.10">
<h3><span class="header-section-number">17.2.10</span> Concluding statement</h3>
<p>With out ANOVA table and final figure in hand, we are ready for the concluding statement:</p>
<blockquote>
<p>Shifts in circadian rhythm differ significantly among treatment groups (ANOVA; Table <a href="do-the-anova.html#tab:niceanovapdf">17.2</a>; <em>R</em><sup>2</sup> = 0.43). As shown in Figure <a href="do-the-anova.html#fig:stripanovatukey">17.4</a>, the mean shift among the “Eyes” subjects was significantly lower than both of the other treatment groups.</p>
</blockquote>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="anova-packages-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="assumpbad-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202-github.pdf", "BIOL202-github.epub"],
"toc": {
"collapse": "section",
"scroll_highight": true,
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
