<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>17.2 Fisher’s Exact Test | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="17.2 Fisher’s Exact Test | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="17.2 Fisher’s Exact Test | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2021-10-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="twocat-packages-data.html"/>
<link rel="next" href="odds.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li class="part"><span><b>Preface</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>Author</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
</ul></li>
<li class="part"><span><b>Getting started with R, RStudio &amp; R Markdown</b></span></li>
<li class="chapter" data-level="1" data-path="what-is-R.html"><a href="what-is-R.html"><i class="fa fa-check"></i><b>1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="2" data-path="install-R-Rstudio.html"><a href="install-R-Rstudio.html"><i class="fa fa-check"></i><b>2</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="3" data-path="start-r.html"><a href="start-r.html"><i class="fa fa-check"></i><b>3</b> Start using R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Rstudio-interface.html"><a href="Rstudio-interface.html"><i class="fa fa-check"></i><b>3.1</b> The RStudio Interface</a></li>
<li class="chapter" data-level="3.2" data-path="coding-basics.html"><a href="coding-basics.html"><i class="fa fa-check"></i><b>3.2</b> Coding basics</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>4</b> R packages</a>
<ul>
<li class="chapter" data-level="4.1" data-path="package-install.html"><a href="package-install.html"><i class="fa fa-check"></i><b>4.1</b> Package installation</a></li>
<li class="chapter" data-level="4.2" data-path="package-load.html"><a href="package-load.html"><i class="fa fa-check"></i><b>4.2</b> Package loading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="intro-markdown.html"><a href="intro-markdown.html"><i class="fa fa-check"></i><b>5</b> Intro to R Markdown</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lit-programming.html"><a href="lit-programming.html"><i class="fa fa-check"></i><b>5.1</b> Literate programming with R Markdown</a></li>
<li class="chapter" data-level="5.2" data-path="veryify-knit.html"><a href="veryify-knit.html"><i class="fa fa-check"></i><b>5.2</b> Making sure R Markdown knits to PDF</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-resources.html"><a href="r-resources.html"><i class="fa fa-check"></i><b>6</b> Extra online resources</a>
<ul>
<li class="chapter" data-level="6.1" data-path="online-resources.html"><a href="online-resources.html"><i class="fa fa-check"></i><b>6.1</b> R Resources Online</a></li>
</ul></li>
<li class="part"><span><b>Reproducible Workflows</b></span></li>
<li class="chapter" data-level="7" data-path="repro-research.html"><a href="repro-research.html"><i class="fa fa-check"></i><b>7</b> Reproducible Research</a>
<ul>
<li class="chapter" data-level="7.1" data-path="comp-repro.html"><a href="comp-repro.html"><i class="fa fa-check"></i><b>7.1</b> Computational reproducibility</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="biol202-workflow.html"><a href="biol202-workflow.html"><i class="fa fa-check"></i><b>8</b> An example BIOL202 workflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="onedrive.html"><a href="onedrive.html"><i class="fa fa-check"></i><b>8.1</b> Microsoft OneDrive</a></li>
<li class="chapter" data-level="8.2" data-path="dir-structure.html"><a href="dir-structure.html"><i class="fa fa-check"></i><b>8.2</b> Directory structure</a></li>
<li class="chapter" data-level="8.3" data-path="setup-dirs.html"><a href="setup-dirs.html"><i class="fa fa-check"></i><b>8.3</b> Steps to set up directories</a></li>
<li class="chapter" data-level="8.4" data-path="lecture-workflow.html"><a href="lecture-workflow.html"><i class="fa fa-check"></i><b>8.4</b> Lecture workflow</a></li>
<li class="chapter" data-level="8.5" data-path="tutorial-workflow.html"><a href="tutorial-workflow.html"><i class="fa fa-check"></i><b>8.5</b> Tutorial workflow</a></li>
<li class="chapter" data-level="8.6" data-path="create-project.html"><a href="create-project.html"><i class="fa fa-check"></i><b>8.6</b> Create an RStudio Project</a></li>
<li class="chapter" data-level="8.7" data-path="create-subdirs.html"><a href="create-subdirs.html"><i class="fa fa-check"></i><b>8.7</b> Create subdirectories</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="create-subdirs.html"><a href="create-subdirs.html#here_package"><i class="fa fa-check"></i><b>8.7.1</b> The <code>here</code> package</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="edit-markdown.html"><a href="edit-markdown.html"><i class="fa fa-check"></i><b>8.8</b> Edit an R markdown file</a></li>
<li class="chapter" data-level="8.9" data-path="md-components.html"><a href="md-components.html"><i class="fa fa-check"></i><b>8.9</b> Components of an R Markdown file</a></li>
<li class="chapter" data-level="8.10" data-path="interact-tutorial.html"><a href="interact-tutorial.html"><i class="fa fa-check"></i><b>8.10</b> Interacting with Tutorial material</a></li>
<li class="chapter" data-level="8.11" data-path="assign-workflow.html"><a href="assign-workflow.html"><i class="fa fa-check"></i><b>8.11</b> Lab assignments workflow</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="prepare-assignments.html"><a href="prepare-assignments.html"><i class="fa fa-check"></i><b>9</b> Preparing and formatting assignments</a>
<ul>
<li class="chapter" data-level="9.1" data-path="open-assign-project1.html"><a href="open-assign-project1.html"><i class="fa fa-check"></i><b>9.1</b> Open your assignment RStudio project</a></li>
<li class="chapter" data-level="9.2" data-path="download-assign-rmd.html"><a href="download-assign-rmd.html"><i class="fa fa-check"></i><b>9.2</b> Download the assignment Rmd file</a></li>
<li class="chapter" data-level="9.3" data-path="open-rmd-file.html"><a href="open-rmd-file.html"><i class="fa fa-check"></i><b>9.3</b> Open the assignment Rmd file</a></li>
<li class="chapter" data-level="9.4" data-path="what-include-answer.html"><a href="what-include-answer.html"><i class="fa fa-check"></i><b>9.4</b> What to include in your answers</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="what-include-answer.html"><a href="what-include-answer.html#chunk_headers"><i class="fa fa-check"></i><b>9.4.1</b> Code chunk headers</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="rmd-graphing.html"><a href="rmd-graphing.html"><i class="fa fa-check"></i><b>9.5</b> Setting up R Markdown for graphing</a></li>
<li class="chapter" data-level="9.6" data-path="example-answer.html"><a href="example-answer.html"><i class="fa fa-check"></i><b>9.6</b> Example question / answer</a></li>
<li class="chapter" data-level="9.7" data-path="knit-assign.html"><a href="knit-assign.html"><i class="fa fa-check"></i><b>9.7</b> Knitting your assignment to PDF</a></li>
<li class="chapter" data-level="9.8" data-path="submit-rmd.html"><a href="submit-rmd.html"><i class="fa fa-check"></i><b>9.8</b> Submit your assignment</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="data-import.html"><a href="data-import.html"><i class="fa fa-check"></i><b>10</b> Preparing and importing Tidy Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tidy-data.html"><a href="tidy-data.html"><i class="fa fa-check"></i><b>10.1</b> Tidy data</a></li>
<li class="chapter" data-level="10.2" data-path="import-csv-url.html"><a href="import-csv-url.html"><i class="fa fa-check"></i><b>10.2</b> Import a CSV file from a website</a></li>
<li class="chapter" data-level="10.3" data-path="create-csv-local.html"><a href="create-csv-local.html"><i class="fa fa-check"></i><b>10.3</b> Create a CSV file</a></li>
<li class="chapter" data-level="10.4" data-path="import-csv-local.html"><a href="import-csv-local.html"><i class="fa fa-check"></i><b>10.4</b> Import a local CSV file</a></li>
<li class="chapter" data-level="10.5" data-path="data-overview.html"><a href="data-overview.html"><i class="fa fa-check"></i><b>10.5</b> Get an overview of a dataset</a></li>
<li class="chapter" data-level="10.6" data-path="tutorial-practice-activities.html"><a href="tutorial-practice-activities.html"><i class="fa fa-check"></i><b>10.6</b> Tutorial practice activities</a></li>
</ul></li>
<li class="part"><span><b>Visualizing and Describing Data</b></span></li>
<li class="chapter" data-level="11" data-path="vis-variable.html"><a href="vis-variable.html"><i class="fa fa-check"></i><b>11</b> Visualizing a single variable</a>
<ul>
<li class="chapter" data-level="11.1" data-path="vis-packages-data.html"><a href="vis-packages-data.html"><i class="fa fa-check"></i><b>11.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="11.2" data-path="vis-data-overview.html"><a href="vis-data-overview.html"><i class="fa fa-check"></i><b>11.2</b> Get an overview of the data</a></li>
<li class="chapter" data-level="11.3" data-path="vis-cat-freq-table.html"><a href="vis-cat-freq-table.html"><i class="fa fa-check"></i><b>11.3</b> Create a frequency table</a></li>
<li class="chapter" data-level="11.4" data-path="vis-cat-barchart.html"><a href="vis-cat-barchart.html"><i class="fa fa-check"></i><b>11.4</b> Create a bar graph</a></li>
<li class="chapter" data-level="11.5" data-path="vis-histogram.html"><a href="vis-histogram.html"><i class="fa fa-check"></i><b>11.5</b> Create a histogram</a></li>
<li class="chapter" data-level="11.6" data-path="vis-describe-hist.html"><a href="vis-describe-hist.html"><i class="fa fa-check"></i><b>11.6</b> Describing a histogram</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="vis-describe.html"><a href="vis-describe.html"><i class="fa fa-check"></i><b>12</b> Describing a single variable</a>
<ul>
<li class="chapter" data-level="12.1" data-path="desc-packages-data.html"><a href="desc-packages-data.html"><i class="fa fa-check"></i><b>12.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="12.2" data-path="desc-cat-Var.html"><a href="desc-cat-Var.html"><i class="fa fa-check"></i><b>12.2</b> Describing a categorical variable</a></li>
<li class="chapter" data-level="12.3" data-path="desc-numeric-var.html"><a href="desc-numeric-var.html"><i class="fa fa-check"></i><b>12.3</b> Describing a numerical variable</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="desc-numeric-var.html"><a href="desc-numeric-var.html#median_IQR"><i class="fa fa-check"></i><b>12.3.1</b> Calculating the median &amp; IQR</a></li>
<li class="chapter" data-level="12.3.2" data-path="desc-numeric-var.html"><a href="desc-numeric-var.html#mean_sd"><i class="fa fa-check"></i><b>12.3.2</b> Calculating the mean &amp; standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="desc-numeric-var-cat.html"><a href="desc-numeric-var-cat.html"><i class="fa fa-check"></i><b>12.4</b> Describing a numerical variable grouped by a categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="vis-twovar.html"><a href="vis-twovar.html"><i class="fa fa-check"></i><b>13</b> Visualizing associations between two variables</a>
<ul>
<li class="chapter" data-level="13.1" data-path="vis2-packages-data.html"><a href="vis2-packages-data.html"><i class="fa fa-check"></i><b>13.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="13.2" data-path="vis2-2cat.html"><a href="vis2-2cat.html"><i class="fa fa-check"></i><b>13.2</b> Visualizing association between two categorical variables</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="vis2-2cat.html"><a href="vis2-2cat.html#vis2_cont_table"><i class="fa fa-check"></i><b>13.2.1</b> Constructing a contingency table</a></li>
<li class="chapter" data-level="13.2.2" data-path="vis2-2cat.html"><a href="vis2-2cat.html#grouped_bar_graphs"><i class="fa fa-check"></i><b>13.2.2</b> Constructing a grouped bar graph</a></li>
<li class="chapter" data-level="13.2.3" data-path="vis2-2cat.html"><a href="vis2-2cat.html#mosaic_plot"><i class="fa fa-check"></i><b>13.2.3</b> Constructing a mosaic plot</a></li>
<li class="chapter" data-level="13.2.4" data-path="vis2-2cat.html"><a href="vis2-2cat.html#interpret_mosaic"><i class="fa fa-check"></i><b>13.2.4</b> Interpreting mosaic plots</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="two-numeric.html"><a href="two-numeric.html"><i class="fa fa-check"></i><b>13.3</b> Visualizing association between two numeric variables</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="two-numeric.html"><a href="two-numeric.html#interpret_scatter"><i class="fa fa-check"></i><b>13.3.1</b> Interpreting and describing a scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html"><i class="fa fa-check"></i><b>13.4</b> Visualizing association between a numeric and a categorical variable</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html#stripchart"><i class="fa fa-check"></i><b>13.4.1</b> Create a stripchart</a></li>
<li class="chapter" data-level="13.4.2" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html#violinplot"><i class="fa fa-check"></i><b>13.4.2</b> Create a violin plot</a></li>
<li class="chapter" data-level="13.4.3" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html#boxplots"><i class="fa fa-check"></i><b>13.4.3</b> Creating a boxplot</a></li>
<li class="chapter" data-level="13.4.4" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html#bestplot"><i class="fa fa-check"></i><b>13.4.4</b> Combining violin and boxplots</a></li>
<li class="chapter" data-level="13.4.5" data-path="numeric-vs-cat.html"><a href="numeric-vs-cat.html#interp_violin"><i class="fa fa-check"></i><b>13.4.5</b> Interpreting stripcharts and boxplots</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Inferential Statistics</b></span></li>
<li class="chapter" data-level="14" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>14</b> Sampling, Estimation, &amp; Uncertainty</a>
<ul>
<li class="chapter" data-level="14.1" data-path="estimation-packages-data.html"><a href="estimation-packages-data.html"><i class="fa fa-check"></i><b>14.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="14.2" data-path="sampling-functions.html"><a href="sampling-functions.html"><i class="fa fa-check"></i><b>14.2</b> Functions for sampling</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="sampling-functions.html"><a href="sampling-functions.html#setseed"><i class="fa fa-check"></i><b>14.2.1</b> Setting the “seed” for random sampling</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="sampling-error.html"><a href="sampling-error.html"><i class="fa fa-check"></i><b>14.3</b> Sampling error</a></li>
<li class="chapter" data-level="14.4" data-path="sampdistmean.html"><a href="sampdistmean.html"><i class="fa fa-check"></i><b>14.4</b> Sampling distribution of the mean</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="sampdistmean.html"><a href="sampdistmean.html#hist_samdist"><i class="fa fa-check"></i><b>14.4.1</b> Visualize the sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="sem-page.html"><a href="sem-page.html"><i class="fa fa-check"></i><b>14.5</b> Standard error of the mean</a></li>
<li class="chapter" data-level="14.6" data-path="confint-rough.html"><a href="confint-rough.html"><i class="fa fa-check"></i><b>14.6</b> Rule of thumb 95% confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="hypothesis.html"><a href="hypothesis.html"><i class="fa fa-check"></i><b>15</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="15.1" data-path="hyp-packages-data.html"><a href="hyp-packages-data.html"><i class="fa fa-check"></i><b>15.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="15.2" data-path="hyp-steps.html"><a href="hyp-steps.html"><i class="fa fa-check"></i><b>15.2</b> Steps to hypothesis testing</a></li>
<li class="chapter" data-level="15.3" data-path="hyp-example.html"><a href="hyp-example.html"><i class="fa fa-check"></i><b>15.3</b> An hypothesis test example</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="hyp-example.html"><a href="hyp-example.html#follow_hyp_steps"><i class="fa fa-check"></i><b>15.3.1</b> Following the steps to hypothesis testing</a></li>
<li class="chapter" data-level="15.3.2" data-path="hyp-example.html"><a href="hyp-example.html#sim_null"><i class="fa fa-check"></i><b>15.3.2</b> Simulating a “null distribution”</a></li>
<li class="chapter" data-level="15.3.3" data-path="hyp-example.html"><a href="hyp-example.html#calc_p"><i class="fa fa-check"></i><b>15.3.3</b> Calculating the <em>P</em>-value</a></li>
<li class="chapter" data-level="15.3.4" data-path="hyp-example.html"><a href="hyp-example.html#concluding_statement"><i class="fa fa-check"></i><b>15.3.4</b> Writing a concluding statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="single-cat.html"><a href="single-cat.html"><i class="fa fa-check"></i><b>16</b> Analyzing a single categorical variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="singcat-packages-data.html"><a href="singcat-packages-data.html"><i class="fa fa-check"></i><b>16.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="16.2" data-path="estproportions.html"><a href="estproportions.html"><i class="fa fa-check"></i><b>16.2</b> Estimating proportions</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="estproportions.html"><a href="estproportions.html#sterr_prop"><i class="fa fa-check"></i><b>16.2.1</b> Standard error for a proportion</a></li>
<li class="chapter" data-level="16.2.2" data-path="estproportions.html"><a href="estproportions.html#confint_prop"><i class="fa fa-check"></i><b>16.2.2</b> Confidence interval for a proportion</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="binomdist.html"><a href="binomdist.html"><i class="fa fa-check"></i><b>16.3</b> Binomial distribution</a></li>
<li class="chapter" data-level="16.4" data-path="binom-test.html"><a href="binom-test.html"><i class="fa fa-check"></i><b>16.4</b> Binomial test</a></li>
<li class="chapter" data-level="16.5" data-path="prophypconf.html"><a href="prophypconf.html"><i class="fa fa-check"></i><b>16.5</b> Confidence interval approach to hypothesis testing</a></li>
<li class="chapter" data-level="16.6" data-path="GOF-test.html"><a href="GOF-test.html"><i class="fa fa-check"></i><b>16.6</b> Goodness-of-fit tests</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two-cat.html"><a href="two-cat.html"><i class="fa fa-check"></i><b>17</b> Analyzing associations between two categorical variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="twocat-packages-data.html"><a href="twocat-packages-data.html"><i class="fa fa-check"></i><b>17.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="17.2" data-path="fishertest.html"><a href="fishertest.html"><i class="fa fa-check"></i><b>17.2</b> Fisher’s Exact Test</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="fishertest.html"><a href="fishertest.html#fisher_hyp"><i class="fa fa-check"></i><b>17.2.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="17.2.2" data-path="fishertest.html"><a href="fishertest.html#show_cont_table"><i class="fa fa-check"></i><b>17.2.2</b> Display a contingency table</a></li>
<li class="chapter" data-level="17.2.3" data-path="fishertest.html"><a href="fishertest.html#show_mosaic"><i class="fa fa-check"></i><b>17.2.3</b> Display a mosaic plot</a></li>
<li class="chapter" data-level="17.2.4" data-path="fishertest.html"><a href="fishertest.html#do_fisher"><i class="fa fa-check"></i><b>17.2.4</b> Conduct the Fisher’s Exact Test</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="odds.html"><a href="odds.html"><i class="fa fa-check"></i><b>17.3</b> Estimate the Odds of getting sick</a></li>
<li class="chapter" data-level="17.4" data-path="oddsratio.html"><a href="oddsratio.html"><i class="fa fa-check"></i><b>17.4</b> Estimate the odds ratio</a></li>
<li class="chapter" data-level="17.5" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>17.5</b> <span class="math inline">\(\chi\)</span><sup>2</sup> Contingency Test</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="chisquare.html"><a href="chisquare.html#chihyp"><i class="fa fa-check"></i><b>17.5.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="17.5.2" data-path="chisquare.html"><a href="chisquare.html#showwormcont"><i class="fa fa-check"></i><b>17.5.2</b> Display the contingency table</a></li>
<li class="chapter" data-level="17.5.3" data-path="chisquare.html"><a href="chisquare.html#mosaicworm"><i class="fa fa-check"></i><b>17.5.3</b> Visualize a mosaic plot</a></li>
<li class="chapter" data-level="17.5.4" data-path="chisquare.html"><a href="chisquare.html#checkchiassum"><i class="fa fa-check"></i><b>17.5.4</b> Check the assumptions</a></li>
<li class="chapter" data-level="17.5.5" data-path="chisquare.html"><a href="chisquare.html#chiresults"><i class="fa fa-check"></i><b>17.5.5</b> Get the results of the test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="single-numeric.html"><a href="single-numeric.html"><i class="fa fa-check"></i><b>18</b> Analyzing a single numerical variable</a>
<ul>
<li class="chapter" data-level="18.1" data-path="singlenum-packages-data.html"><a href="singlenum-packages-data.html"><i class="fa fa-check"></i><b>18.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="18.2" data-path="onesamp-t-test.html"><a href="onesamp-t-test.html"><i class="fa fa-check"></i><b>18.2</b> One-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="18.3" data-path="t-confidence.html"><a href="t-confidence.html"><i class="fa fa-check"></i><b>18.3</b> Confidence intervals for <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="t-confidence.html"><a href="t-confidence.html#conf_precision"><i class="fa fa-check"></i><b>18.3.1</b> Confidence interval as a measure of precision for an estimate</a></li>
<li class="chapter" data-level="18.3.2" data-path="t-confidence.html"><a href="t-confidence.html#conf_hyp"><i class="fa fa-check"></i><b>18.3.2</b> Confidence interval approach to hypothesis testing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="visual-markdown-editor.html"><a href="visual-markdown-editor.html"><i class="fa fa-check"></i>Visual Markdown Editor</a>
<ul>
<li class="chapter" data-level="" data-path="a-more-familiar-editing-environment.html"><a href="a-more-familiar-editing-environment.html"><i class="fa fa-check"></i>A more familiar editing environment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="common-errors-and-their-solutions.html"><a href="common-errors-and-their-solutions.html"><i class="fa fa-check"></i>Common errors and their solutions</a>
<ul>
<li class="chapter" data-level="" data-path="google-can-help.html"><a href="google-can-help.html"><i class="fa fa-check"></i>Google can help</a></li>
<li class="chapter" data-level="" data-path="rtools-required-during-install.html"><a href="rtools-required-during-install.html"><i class="fa fa-check"></i>Rtools required during install</a></li>
<li class="chapter" data-level="" data-path="could-not-find-function.html"><a href="could-not-find-function.html"><i class="fa fa-check"></i>Could not find function</a></li>
<li class="chapter" data-level="" data-path="there-is-no-package.html"><a href="there-is-no-package.html"><i class="fa fa-check"></i>There is no package</a></li>
<li class="chapter" data-level="" data-path="trying-to-use-cran-without-setting-a-mirror.html"><a href="trying-to-use-cran-without-setting-a-mirror.html"><i class="fa fa-check"></i>Trying to use CRAN without setting a mirror</a></li>
<li class="chapter" data-level="" data-path="pdf-latex-is-not-found.html"><a href="pdf-latex-is-not-found.html"><i class="fa fa-check"></i>PDF Latex is not found</a></li>
<li class="chapter" data-level="" data-path="error-in-parse.html"><a href="error-in-parse.html"><i class="fa fa-check"></i>Error in parse</a></li>
<li class="chapter" data-level="" data-path="no-such-file-or-directory-exists.html"><a href="no-such-file-or-directory-exists.html"><i class="fa fa-check"></i>No such file or directory exists</a></li>
<li class="chapter" data-level="" data-path="messy-output-when-loading-packages.html"><a href="messy-output-when-loading-packages.html"><i class="fa fa-check"></i>Messy output when loading packages</a></li>
<li class="chapter" data-level="" data-path="unused-argument.html"><a href="unused-argument.html"><i class="fa fa-check"></i>Unused argument</a></li>
<li class="chapter" data-level="" data-path="object-not-found.html"><a href="object-not-found.html"><i class="fa fa-check"></i>Object not found</a></li>
<li class="chapter" data-level="" data-path="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><i class="fa fa-check"></i>Figure caption doesn’t show up below figure in knitted document</a></li>
<li class="chapter" data-level="" data-path="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><i class="fa fa-check"></i>Filename, directory name, or volume label syntax is incorrect</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="fishertest" class="section level2" number="17.2">
<h2><span class="header-section-number">17.2</span> Fisher’s Exact Test</h2>
<p>When testing for an association between two categorical variables, the most common test that is used is the <span class="math inline">\(\chi\)</span><sup>2</sup> contingency test, which is described in the next section.</p>
<p>When the two categorical variables <em>have exactly 2 categories each</em>, and thus yield a 2 x 2 contingency table, the <strong>Fisher’s Exact test</strong> (a type of contingency test) provides an EXACT <em>P</em>-value, and is therefore preferred over the <span class="math inline">\(\chi\)</span><sup>2</sup> contingency test (below) when you have a computer to do the calculations.</p>
<p>Often, and especially when the 2 x 2 contingency table deals with a health-related study, one refers to the <strong>Odds Ratio</strong>, which we’ll learn about below.</p>
<p>In any case, the most powerful statistical test for a 2 x 2 contingency analysis is a <strong>Fisher’s Exact test</strong>.</p>
<div id="fisher_hyp" class="section level3" number="17.2.1">
<h3><span class="header-section-number">17.2.1</span> Hypothesis statement</h3>
<p>We’ll use the cancer study data again for this example, as described in example 9.2 (Page 235) in the text.</p>
<p>The hypotheses for this test:</p>
<p><strong>H<sub>0</sub></strong>: There is no association between the use of aspirin and the probability of developing cancer.<br />
<strong>H<sub>A</sub></strong>: There is an association between the use of aspirin and the probability of developing cancer.</p>
<ul>
<li>We’ll use an <span class="math inline">\(\alpha\)</span> level of 0.05.<br />
</li>
<li>It is a two-tailed alternative hypothesis<br />
</li>
<li>We’ll use a Fisher’s Exact test to test the null hypothesis, because this is the <strong>most powerful test</strong> when analyzing a 2 x 2 contingency table.<br />
</li>
<li>There is no test statistic for the Fisher’s Exact test, and nor does it use “degrees of freedom” (the latter you’ll learn about soon, and is only required when we use a theoretical distribution for a test statistic)</li>
</ul>
<blockquote>
<p><strong>HOWEVER</strong>: it is recommended that you report the “odds ratio” (which you’ll learn about below) in your concluding statement, along with its appropriate confidence interval; this is a useful stand-in test statistic for the Fisher’s Exact Test</p>
</blockquote>
<ul>
<li>We also don’t need to worry about assumptions for this test, because it is not relying on a theoretical probability distribution<br />
</li>
<li>It is always a good idea to present a figure to accompany your analysis; in the case of a Fisher’s Exact test, the figure heading will include information about the sample size / total number of observations, whereas the concluding statement typically does not</li>
</ul>
</div>
<div id="show_cont_table" class="section level3" number="17.2.2">
<h3><span class="header-section-number">17.2.2</span> Display a contingency table</h3>
<p>We’ll use the approach we learned in an earlier <a href="vis2-2cat.html#vis2_cont_table">tutorial</a> to construct a contingency table.</p>
<p>We’ll store the table in an object called “cancer.aspirin.table,” and we’ll make sure to include margin (row and column) totals:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="fishertest.html#cb227-1" aria-hidden="true" tabindex="-1"></a>cancer.aspirin.table <span class="ot">&lt;-</span> cancer <span class="sc">%&gt;%</span></span>
<span id="cb227-2"><a href="fishertest.html#cb227-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(response, aspirinTreatment) <span class="sc">%&gt;%</span></span>
<span id="cb227-3"><a href="fishertest.html#cb227-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">&quot;row&quot;</span>, <span class="st">&quot;col&quot;</span>))</span></code></pre></div>
<p>Let’s have a look at the result:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="fishertest.html#cb228-1" aria-hidden="true" tabindex="-1"></a>cancer.aspirin.table</span></code></pre></div>
<pre><code>##   response Aspirin Placebo Total
##     Cancer    1438    1427  2865
##  No cancer   18496   18515 37011
##      Total   19934   19942 39876</code></pre>
<p><strong>NOTE</strong>: When dealing with data from studies on human health (e.g. evaluating healthy versus sick subjects), it is convention to organize the contingency table as shown above, with (i) the outcome of interest (here, cancer) in the top row and the alternative outcome on the bottom row, and (ii) the treatment in the first column and placebo (control group) in the second column.</p>
<p>When the data are not related to health outcomes, you do not need to worry about the ordering of the rows of data.</p>
<p>Let’s use the <code>kable</code> function to display a nice looking contingency table:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="fishertest.html#cb230-1" aria-hidden="true" tabindex="-1"></a>cancer.aspirin.table <span class="sc">%&gt;%</span></span>
<span id="cb230-2"><a href="fishertest.html#cb230-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Contingency table showing the incidence of cancer in relation to experimental treatments&quot;</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<table>
<caption>
(#tab:cont_cancer_aspirin_table)Contingency table showing the incidence of cancer in relation to experimental treatments
</caption>
<thead>
<tr>
<th style="text-align:left;">
response
</th>
<th style="text-align:right;">
Aspirin
</th>
<th style="text-align:right;">
Placebo
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Cancer
</td>
<td style="text-align:right;">
1438
</td>
<td style="text-align:right;">
1427
</td>
<td style="text-align:right;">
2865
</td>
</tr>
<tr>
<td style="text-align:left;">
No cancer
</td>
<td style="text-align:right;">
18496
</td>
<td style="text-align:right;">
18515
</td>
<td style="text-align:right;">
37011
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
19934
</td>
<td style="text-align:right;">
19942
</td>
<td style="text-align:right;">
39876
</td>
</tr>
</tbody>
</table>
</div>
<div id="show_mosaic" class="section level3" number="17.2.3">
<h3><span class="header-section-number">17.2.3</span> Display a mosaic plot</h3>
<p>Let’s visualize the data using a mosaic plot, taking note of the frequency of observations falling in each category (from the contingency table produced previously).</p>
<p>Here we’ll add a bit of new code to make the mosaic plot more ideally formatted. When we first learned how to create a mosaic plot, we saw that the y-axis was lacking tick-marks and numbers. We’ll remedy that here, using the <code>scale_y_continuous</code>, which allows us to specify what breaks (ticks) we want on the y-axis.</p>
<p>Here we’re showing “relative frequency” on the y-axis, so this should range from 0 to 1. And we’ll add breaks at intervals of 0.2. Specifically, we use the base <code>seq</code> function to generate a sequence of numbers from 0 to 1, in intervals of 0.2:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="fishertest.html#cb231-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">%&gt;%</span></span>
<span id="cb231-2"><a href="fishertest.html#cb231-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb231-3"><a href="fishertest.html#cb231-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(aspirinTreatment), <span class="at">fill =</span> response)) <span class="sc">+</span></span>
<span id="cb231-4"><a href="fishertest.html#cb231-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.2</span>)) <span class="sc">+</span></span>
<span id="cb231-5"><a href="fishertest.html#cb231-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Treatment group&quot;</span>) <span class="sc">+</span></span>
<span id="cb231-6"><a href="fishertest.html#cb231-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb231-7"><a href="fishertest.html#cb231-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-68"></span>
<img src="BIOL202-github_files/figure-html/unnamed-chunk-68-1.png" alt="Relative frequency of cancer among women randomly assigned to control (n = 19942) and aspririn (n = 19934) treatment groups." width="384" />
<p class="caption">
Figure 17.1: Relative frequency of cancer among women randomly assigned to control (n = 19942) and aspririn (n = 19934) treatment groups.
</p>
</div>
<p>The mosaic plot shows that the incidence (or relative frequency) of cancer is almost identical in the treatment and control groups.</p>
<div class="note">
<p><strong>IMPORTANT </strong>
It is best practice to display the response variable as the “fill” variable in a mosaic plot.</p>
</div>
</div>
<div id="do_fisher" class="section level3" number="17.2.4">
<h3><span class="header-section-number">17.2.4</span> Conduct the Fisher’s Exact Test</h3>
<p>To do the Fisher’s exact test on the cancer data, it is straightforward, using the <code>fisher.test</code> function from the <code>janitor</code> package.</p>
<div class="note">
<p><strong>NOTE</strong>
There is also <code>fisher.test</code> function in the base R <code>stats</code> package, but it does not conform to <code>tidyverse</code> expectations. Hence our use of the <code>fisher.test</code> function from the <code>janitor</code> package. When there are multiple packages that use the same name for a function, we can specify the version we want by prefacing the function with the package name and two colons, like this: “janitor::fisher.test()”</p>
</div>
<p>See the help file for the <code>janitor</code> version of the <code>fisher.test</code> function:</p>
<pre><code>?janitor::fisher.test</code></pre>
<p>This function requires a two-way “tabyl” as the input, and we already know how to construct such a table.</p>
<p>We’ll put the results in an object called “cancer.fishertest”:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="fishertest.html#cb233-1" aria-hidden="true" tabindex="-1"></a>cancer.fishertest <span class="ot">&lt;-</span> cancer <span class="sc">%&gt;%</span></span>
<span id="cb233-2"><a href="fishertest.html#cb233-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tabyl</span>(aspirinTreatment, response) <span class="sc">%&gt;%</span></span>
<span id="cb233-3"><a href="fishertest.html#cb233-3" aria-hidden="true" tabindex="-1"></a>    janitor<span class="sc">::</span><span class="fu">fisher.test</span>()</span></code></pre></div>
<p>Let’s look at the results:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="fishertest.html#cb234-1" aria-hidden="true" tabindex="-1"></a>cancer.fishertest</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  .
## p-value = 0.8311
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.9342128 1.0892376
## sample estimates:
## odds ratio 
##   1.008744</code></pre>
<p>The <em>P</em>-value associated with the test is 0.831, which is clearly greater than our <span class="math inline">\(\alpha\)</span> of 0.05. We therefore FAIL to reject the null hypothesis.</p>
<p>You’ll notice that the output includes the <strong>odds ratio</strong> and its 95% confidence interval. The interval it provides is slightly different from the one we’ll learn about below, but <strong>when reporting the results of a Fisher’s Exact test it is OK to report the confidence interval provided by the <code>fisher.test</code> function</strong>. It is also OK to provide the slightly different one that we learn about below.</p>
<p><strong>Concluding statement</strong></p>
<blockquote>
<p>There is no evidence that the probability of developing cancer differs between the control group and the aspirin treatment group (Fisher’s Exact Test; <em>P</em>-value = 0.831; odds ratio = 1.01; 95% CI: 0.934 - 1.089).</p>
</blockquote>
<div class="note">
<p><strong>TIP</strong>
Report odds ratios to 2 decimal places, and associated measures of uncertainty to 3 decimal places</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="twocat-packages-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="odds.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202-github.pdf", "BIOL202-github.epub"],
"toc": {
"collapse": "section",
"scroll_highight": true,
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
