<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10.3 An hypothesis test example | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="10.3 An hypothesis test example | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10.3 An hypothesis test example | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2022-11-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hyp_steps.html"/>
<link rel="next" href="single_cat.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li class="part"><span><b>Preface</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>Author</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="ubco-biology-open-materials.html"><a href="ubco-biology-open-materials.html"><i class="fa fa-check"></i>UBCO Biology open materials</a></li>
</ul></li>
<li class="part"><span><b>Getting started with R, RStudio &amp; R Markdown</b></span></li>
<li class="chapter" data-level="1" data-path="what_is_R.html"><a href="what_is_R.html"><i class="fa fa-check"></i><b>1</b> What are R and RStudio?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install_R_Rstudio.html"><a href="install_R_Rstudio.html"><i class="fa fa-check"></i><b>1.1</b> Installing R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="start_r.html"><a href="start_r.html"><i class="fa fa-check"></i><b>2</b> Start using R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Rstudio_interface.html"><a href="Rstudio_interface.html"><i class="fa fa-check"></i><b>2.1</b> The RStudio Interface</a></li>
<li class="chapter" data-level="2.2" data-path="coding_basics.html"><a href="coding_basics.html"><i class="fa fa-check"></i><b>2.2</b> Coding basics</a></li>
<li class="chapter" data-level="2.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>2.3</b> R packages</a></li>
<li class="chapter" data-level="2.4" data-path="package_install.html"><a href="package_install.html"><i class="fa fa-check"></i><b>2.4</b> Package installation</a></li>
<li class="chapter" data-level="2.5" data-path="package_load.html"><a href="package_load.html"><i class="fa fa-check"></i><b>2.5</b> Package loading</a></li>
<li class="chapter" data-level="2.6" data-path="intro_markdown.html"><a href="intro_markdown.html"><i class="fa fa-check"></i><b>2.6</b> Intro to R Markdown</a></li>
<li class="chapter" data-level="2.7" data-path="lit_programming.html"><a href="lit_programming.html"><i class="fa fa-check"></i><b>2.7</b> Literate programming with R Markdown</a></li>
<li class="chapter" data-level="2.8" data-path="veryify_knit.html"><a href="veryify_knit.html"><i class="fa fa-check"></i><b>2.8</b> Making sure R Markdown knits to PDF</a></li>
<li class="chapter" data-level="2.9" data-path="r_resources.html"><a href="r_resources.html"><i class="fa fa-check"></i><b>2.9</b> Extra resources</a></li>
<li class="chapter" data-level="2.10" data-path="online_resources.html"><a href="online_resources.html"><i class="fa fa-check"></i><b>2.10</b> R Resources Online</a></li>
</ul></li>
<li class="part"><span><b>Reproducible Workflows</b></span></li>
<li class="chapter" data-level="3" data-path="repro_research.html"><a href="repro_research.html"><i class="fa fa-check"></i><b>3</b> Reproducible Research</a>
<ul>
<li class="chapter" data-level="3.1" data-path="comp_repro.html"><a href="comp_repro.html"><i class="fa fa-check"></i><b>3.1</b> Computational reproducibility</a></li>
<li class="chapter" data-level="3.2" data-path="biol202_workflow.html"><a href="biol202_workflow.html"><i class="fa fa-check"></i><b>3.2</b> An example BIOL202 workflow</a></li>
<li class="chapter" data-level="3.3" data-path="onedrive.html"><a href="onedrive.html"><i class="fa fa-check"></i><b>3.3</b> Microsoft OneDrive</a></li>
<li class="chapter" data-level="3.4" data-path="dir_structure.html"><a href="dir_structure.html"><i class="fa fa-check"></i><b>3.4</b> Directory structure</a></li>
<li class="chapter" data-level="3.5" data-path="setup_dirs.html"><a href="setup_dirs.html"><i class="fa fa-check"></i><b>3.5</b> Steps to set up directories</a></li>
<li class="chapter" data-level="3.6" data-path="lecture_workflow.html"><a href="lecture_workflow.html"><i class="fa fa-check"></i><b>3.6</b> Lecture workflow</a></li>
<li class="chapter" data-level="3.7" data-path="tutorial_workflow.html"><a href="tutorial_workflow.html"><i class="fa fa-check"></i><b>3.7</b> Tutorial workflow</a></li>
<li class="chapter" data-level="3.8" data-path="create_project.html"><a href="create_project.html"><i class="fa fa-check"></i><b>3.8</b> Create an RStudio Project</a></li>
<li class="chapter" data-level="3.9" data-path="create_subdirs.html"><a href="create_subdirs.html"><i class="fa fa-check"></i><b>3.9</b> Create subdirectories</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="create_subdirs.html"><a href="create_subdirs.html#here_package"><i class="fa fa-check"></i><b>3.9.1</b> The <code>here</code> package</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="edit_markdown.html"><a href="edit_markdown.html"><i class="fa fa-check"></i><b>3.10</b> Edit an R markdown file</a></li>
<li class="chapter" data-level="3.11" data-path="md_components.html"><a href="md_components.html"><i class="fa fa-check"></i><b>3.11</b> Components of an R Markdown file</a></li>
<li class="chapter" data-level="3.12" data-path="interact_tutorial.html"><a href="interact_tutorial.html"><i class="fa fa-check"></i><b>3.12</b> Interacting with Tutorial material</a></li>
<li class="chapter" data-level="3.13" data-path="assign_workflow.html"><a href="assign_workflow.html"><i class="fa fa-check"></i><b>3.13</b> Lab assignments workflow</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare_assignments.html"><a href="prepare_assignments.html"><i class="fa fa-check"></i><b>4</b> Preparing and formatting assignments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="open_assign_project1.html"><a href="open_assign_project1.html"><i class="fa fa-check"></i><b>4.1</b> Open your assignment RStudio project</a></li>
<li class="chapter" data-level="4.2" data-path="download_assign_rmd.html"><a href="download_assign_rmd.html"><i class="fa fa-check"></i><b>4.2</b> Download the assignment Rmd file</a></li>
<li class="chapter" data-level="4.3" data-path="open_rmd_file.html"><a href="open_rmd_file.html"><i class="fa fa-check"></i><b>4.3</b> Open the assignment Rmd file</a></li>
<li class="chapter" data-level="4.4" data-path="what_include_answer.html"><a href="what_include_answer.html"><i class="fa fa-check"></i><b>4.4</b> What to include in your answers</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="what_include_answer.html"><a href="what_include_answer.html#chunk_headers"><i class="fa fa-check"></i><b>4.4.1</b> Code chunk headers</a></li>
<li class="chapter" data-level="4.4.2" data-path="what_include_answer.html"><a href="what_include_answer.html#first_csv_import"><i class="fa fa-check"></i><b>4.4.2</b> Import data</a></li>
<li class="chapter" data-level="4.4.3" data-path="what_include_answer.html"><a href="what_include_answer.html#first_load_package"><i class="fa fa-check"></i><b>4.4.3</b> Load packages</a></li>
<li class="chapter" data-level="4.4.4" data-path="what_include_answer.html"><a href="what_include_answer.html#answer-the-questions"><i class="fa fa-check"></i><b>4.4.4</b> Answer the questions</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="rmd_graphing.html"><a href="rmd_graphing.html"><i class="fa fa-check"></i><b>4.5</b> Setting up R Markdown for graphing</a></li>
<li class="chapter" data-level="4.6" data-path="example_answer.html"><a href="example_answer.html"><i class="fa fa-check"></i><b>4.6</b> Example question / answer</a></li>
<li class="chapter" data-level="4.7" data-path="knit_assign.html"><a href="knit_assign.html"><i class="fa fa-check"></i><b>4.7</b> Knitting your assignment to PDF</a></li>
<li class="chapter" data-level="4.8" data-path="submit_rmd.html"><a href="submit_rmd.html"><i class="fa fa-check"></i><b>4.8</b> Submit your assignment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data_import.html"><a href="data_import.html"><i class="fa fa-check"></i><b>5</b> Preparing and importing Tidy Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tidy_data.html"><a href="tidy_data.html"><i class="fa fa-check"></i><b>5.1</b> Tidy data</a></li>
<li class="chapter" data-level="5.2" data-path="import_csv_url.html"><a href="import_csv_url.html"><i class="fa fa-check"></i><b>5.2</b> Import a CSV file from a website</a></li>
<li class="chapter" data-level="5.3" data-path="create_csv_local.html"><a href="create_csv_local.html"><i class="fa fa-check"></i><b>5.3</b> Create a CSV file</a></li>
<li class="chapter" data-level="5.4" data-path="import_csv_local.html"><a href="import_csv_local.html"><i class="fa fa-check"></i><b>5.4</b> Import a local CSV file</a></li>
<li class="chapter" data-level="5.5" data-path="data_overview.html"><a href="data_overview.html"><i class="fa fa-check"></i><b>5.5</b> Get an overview of a dataset</a></li>
<li class="chapter" data-level="5.6" data-path="tutorial-practice-activities.html"><a href="tutorial-practice-activities.html"><i class="fa fa-check"></i><b>5.6</b> Tutorial practice activities</a></li>
</ul></li>
<li class="part"><span><b>Visualizing and Describing Data</b></span></li>
<li class="chapter" data-level="6" data-path="vis_variable.html"><a href="vis_variable.html"><i class="fa fa-check"></i><b>6</b> Visualizing a single variable</a>
<ul>
<li class="chapter" data-level="6.1" data-path="vis_packages_data.html"><a href="vis_packages_data.html"><i class="fa fa-check"></i><b>6.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="6.2" data-path="vis_data_overview.html"><a href="vis_data_overview.html"><i class="fa fa-check"></i><b>6.2</b> Get an overview of the data</a></li>
<li class="chapter" data-level="6.3" data-path="vis_cat_freq_table.html"><a href="vis_cat_freq_table.html"><i class="fa fa-check"></i><b>6.3</b> Create a frequency table</a></li>
<li class="chapter" data-level="6.4" data-path="vis_cat_barchart.html"><a href="vis_cat_barchart.html"><i class="fa fa-check"></i><b>6.4</b> Create a bar graph</a></li>
<li class="chapter" data-level="6.5" data-path="vis_histogram.html"><a href="vis_histogram.html"><i class="fa fa-check"></i><b>6.5</b> Create a histogram</a></li>
<li class="chapter" data-level="6.6" data-path="vis_describe_hist.html"><a href="vis_describe_hist.html"><i class="fa fa-check"></i><b>6.6</b> Describing a histogram</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vis_describe.html"><a href="vis_describe.html"><i class="fa fa-check"></i><b>7</b> Describing a single variable</a>
<ul>
<li class="chapter" data-level="7.1" data-path="desc_packages_data.html"><a href="desc_packages_data.html"><i class="fa fa-check"></i><b>7.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="7.2" data-path="desc_cat_Var.html"><a href="desc_cat_Var.html"><i class="fa fa-check"></i><b>7.2</b> Describing a categorical variable</a></li>
<li class="chapter" data-level="7.3" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html"><i class="fa fa-check"></i><b>7.3</b> Describing a numerical variable</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html#median_IQR"><i class="fa fa-check"></i><b>7.3.1</b> Calculating the median &amp; IQR</a></li>
<li class="chapter" data-level="7.3.2" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html#mean_sd"><i class="fa fa-check"></i><b>7.3.2</b> Calculating the mean &amp; standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="desc_numeric_var_cat.html"><a href="desc_numeric_var_cat.html"><i class="fa fa-check"></i><b>7.4</b> Describing a numerical variable grouped by a categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="vis_twovar.html"><a href="vis_twovar.html"><i class="fa fa-check"></i><b>8</b> Visualizing associations between two variables</a>
<ul>
<li class="chapter" data-level="8.1" data-path="vis2_packages_data.html"><a href="vis2_packages_data.html"><i class="fa fa-check"></i><b>8.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="8.2" data-path="vis2_2cat.html"><a href="vis2_2cat.html"><i class="fa fa-check"></i><b>8.2</b> Visualizing association between two categorical variables</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="vis2_2cat.html"><a href="vis2_2cat.html#vis2_cont_table"><i class="fa fa-check"></i><b>8.2.1</b> Constructing a contingency table</a></li>
<li class="chapter" data-level="8.2.2" data-path="vis2_2cat.html"><a href="vis2_2cat.html#grouped_bar_graphs"><i class="fa fa-check"></i><b>8.2.2</b> Constructing a grouped bar graph</a></li>
<li class="chapter" data-level="8.2.3" data-path="vis2_2cat.html"><a href="vis2_2cat.html#mosaic_plot"><i class="fa fa-check"></i><b>8.2.3</b> Constructing a mosaic plot</a></li>
<li class="chapter" data-level="8.2.4" data-path="vis2_2cat.html"><a href="vis2_2cat.html#interpret_mosaic"><i class="fa fa-check"></i><b>8.2.4</b> Interpreting mosaic plots</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="two_numeric.html"><a href="two_numeric.html"><i class="fa fa-check"></i><b>8.3</b> Visualizing association between two numeric variables</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="two_numeric.html"><a href="two_numeric.html#interpret_scatter"><i class="fa fa-check"></i><b>8.3.1</b> Interpreting and describing a scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html"><i class="fa fa-check"></i><b>8.4</b> Visualizing association between a numeric and a categorical variable</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#stripchart"><i class="fa fa-check"></i><b>8.4.1</b> Create a stripchart</a></li>
<li class="chapter" data-level="8.4.2" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#violinplot"><i class="fa fa-check"></i><b>8.4.2</b> Create a violin plot</a></li>
<li class="chapter" data-level="8.4.3" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#boxplots"><i class="fa fa-check"></i><b>8.4.3</b> Creating a boxplot</a></li>
<li class="chapter" data-level="8.4.4" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#bestplot"><i class="fa fa-check"></i><b>8.4.4</b> Combining violin and boxplots</a></li>
<li class="chapter" data-level="8.4.5" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#interp_violin"><i class="fa fa-check"></i><b>8.4.5</b> Interpreting stripcharts, violin plots and boxplots</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Inferential Statistics</b></span></li>
<li class="chapter" data-level="9" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>9</b> Sampling, Estimation, &amp; Uncertainty</a>
<ul>
<li class="chapter" data-level="9.1" data-path="estimation_packages_data.html"><a href="estimation_packages_data.html"><i class="fa fa-check"></i><b>9.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="9.2" data-path="sampling_functions.html"><a href="sampling_functions.html"><i class="fa fa-check"></i><b>9.2</b> Functions for sampling</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sampling_functions.html"><a href="sampling_functions.html#setseed"><i class="fa fa-check"></i><b>9.2.1</b> Setting the “seed” for random sampling</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sampling_error.html"><a href="sampling_error.html"><i class="fa fa-check"></i><b>9.3</b> Sampling error</a></li>
<li class="chapter" data-level="9.4" data-path="sampdistmean.html"><a href="sampdistmean.html"><i class="fa fa-check"></i><b>9.4</b> Sampling distribution of the mean</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sampdistmean.html"><a href="sampdistmean.html#hist_samdist"><i class="fa fa-check"></i><b>9.4.1</b> Visualize the sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sem_page.html"><a href="sem_page.html"><i class="fa fa-check"></i><b>9.5</b> Standard error of the mean</a></li>
<li class="chapter" data-level="9.6" data-path="confint_rough.html"><a href="confint_rough.html"><i class="fa fa-check"></i><b>9.6</b> Rule of thumb 95% confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypothesis.html"><a href="hypothesis.html"><i class="fa fa-check"></i><b>10</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="10.1" data-path="hyp_packages_data.html"><a href="hyp_packages_data.html"><i class="fa fa-check"></i><b>10.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="10.2" data-path="hyp_steps.html"><a href="hyp_steps.html"><i class="fa fa-check"></i><b>10.2</b> Steps to hypothesis testing</a></li>
<li class="chapter" data-level="10.3" data-path="hyp_example.html"><a href="hyp_example.html"><i class="fa fa-check"></i><b>10.3</b> An hypothesis test example</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="hyp_example.html"><a href="hyp_example.html#follow_hyp_steps"><i class="fa fa-check"></i><b>10.3.1</b> Following the steps to hypothesis testing</a></li>
<li class="chapter" data-level="10.3.2" data-path="hyp_example.html"><a href="hyp_example.html#sim_null"><i class="fa fa-check"></i><b>10.3.2</b> Simulating a “null distribution”</a></li>
<li class="chapter" data-level="10.3.3" data-path="hyp_example.html"><a href="hyp_example.html#calc_p"><i class="fa fa-check"></i><b>10.3.3</b> Calculating the <em>P</em>-value</a></li>
<li class="chapter" data-level="10.3.4" data-path="hyp_example.html"><a href="hyp_example.html#concluding_statement"><i class="fa fa-check"></i><b>10.3.4</b> Writing a concluding statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="single_cat.html"><a href="single_cat.html"><i class="fa fa-check"></i><b>11</b> Analyzing a single categorical variable</a>
<ul>
<li class="chapter" data-level="11.1" data-path="singcat_packages_data.html"><a href="singcat_packages_data.html"><i class="fa fa-check"></i><b>11.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="11.2" data-path="estproportions.html"><a href="estproportions.html"><i class="fa fa-check"></i><b>11.2</b> Estimating proportions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="estproportions.html"><a href="estproportions.html#sterr_prop"><i class="fa fa-check"></i><b>11.2.1</b> Standard error for a proportion</a></li>
<li class="chapter" data-level="11.2.2" data-path="estproportions.html"><a href="estproportions.html#confint_prop"><i class="fa fa-check"></i><b>11.2.2</b> Confidence interval for a proportion</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="binomdist.html"><a href="binomdist.html"><i class="fa fa-check"></i><b>11.3</b> Binomial distribution</a></li>
<li class="chapter" data-level="11.4" data-path="binom_test.html"><a href="binom_test.html"><i class="fa fa-check"></i><b>11.4</b> Binomial test</a></li>
<li class="chapter" data-level="11.5" data-path="prophypconf.html"><a href="prophypconf.html"><i class="fa fa-check"></i><b>11.5</b> Confidence interval approach to hypothesis testing</a></li>
<li class="chapter" data-level="11.6" data-path="GOF_test.html"><a href="GOF_test.html"><i class="fa fa-check"></i><b>11.6</b> Goodness-of-fit tests</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="two_cat.html"><a href="two_cat.html"><i class="fa fa-check"></i><b>12</b> Analyzing associations between two categorical variables</a>
<ul>
<li class="chapter" data-level="12.1" data-path="twocat_packages_data.html"><a href="twocat_packages_data.html"><i class="fa fa-check"></i><b>12.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="12.2" data-path="fishertest.html"><a href="fishertest.html"><i class="fa fa-check"></i><b>12.2</b> Fisher’s Exact Test</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="fishertest.html"><a href="fishertest.html#fisher_hyp"><i class="fa fa-check"></i><b>12.2.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="12.2.2" data-path="fishertest.html"><a href="fishertest.html#show_cont_table"><i class="fa fa-check"></i><b>12.2.2</b> Display a contingency table</a></li>
<li class="chapter" data-level="12.2.3" data-path="fishertest.html"><a href="fishertest.html#show_mosaic"><i class="fa fa-check"></i><b>12.2.3</b> Display a mosaic plot</a></li>
<li class="chapter" data-level="12.2.4" data-path="fishertest.html"><a href="fishertest.html#do_fisher"><i class="fa fa-check"></i><b>12.2.4</b> Conduct the Fisher’s Exact Test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="odds.html"><a href="odds.html"><i class="fa fa-check"></i><b>12.3</b> Estimate the Odds of getting sick</a></li>
<li class="chapter" data-level="12.4" data-path="oddsratio.html"><a href="oddsratio.html"><i class="fa fa-check"></i><b>12.4</b> Estimate the odds ratio</a></li>
<li class="chapter" data-level="12.5" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>12.5</b> <span class="math inline">\(\chi\)</span><sup>2</sup> Contingency Test</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="chisquare.html"><a href="chisquare.html#chihyp"><i class="fa fa-check"></i><b>12.5.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="12.5.2" data-path="chisquare.html"><a href="chisquare.html#showwormcont"><i class="fa fa-check"></i><b>12.5.2</b> Display the contingency table</a></li>
<li class="chapter" data-level="12.5.3" data-path="chisquare.html"><a href="chisquare.html#mosaicworm"><i class="fa fa-check"></i><b>12.5.3</b> Visualize a mosaic plot</a></li>
<li class="chapter" data-level="12.5.4" data-path="chisquare.html"><a href="chisquare.html#checkchiassum"><i class="fa fa-check"></i><b>12.5.4</b> Check the assumptions</a></li>
<li class="chapter" data-level="12.5.5" data-path="chisquare.html"><a href="chisquare.html#chiresults"><i class="fa fa-check"></i><b>12.5.5</b> Get the results of the test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="single_numeric.html"><a href="single_numeric.html"><i class="fa fa-check"></i><b>13</b> Analyzing a single numerical variable</a>
<ul>
<li class="chapter" data-level="13.1" data-path="singlenum_packages_data.html"><a href="singlenum_packages_data.html"><i class="fa fa-check"></i><b>13.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="13.2" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html"><i class="fa fa-check"></i><b>13.2</b> One-sample <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_hyp"><i class="fa fa-check"></i><b>13.2.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="13.2.2" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_assumptions"><i class="fa fa-check"></i><b>13.2.2</b> Assumptions of one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="13.2.3" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_graph"><i class="fa fa-check"></i><b>13.2.3</b> A graph to accompany a one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="13.2.4" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_test"><i class="fa fa-check"></i><b>13.2.4</b> Conduct the one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="13.2.5" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_conclude"><i class="fa fa-check"></i><b>13.2.5</b> Concluding statement for the one-sample <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="t_confidence.html"><a href="t_confidence.html"><i class="fa fa-check"></i><b>13.3</b> Confidence intervals for <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="t_confidence.html"><a href="t_confidence.html#conf_precision"><i class="fa fa-check"></i><b>13.3.1</b> Confidence interval as a measure of precision for an estimate</a></li>
<li class="chapter" data-level="13.3.2" data-path="t_confidence.html"><a href="t_confidence.html#conf_hyp"><i class="fa fa-check"></i><b>13.3.2</b> Confidence interval approach to hypothesis testing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="compare_two_means.html"><a href="compare_two_means.html"><i class="fa fa-check"></i><b>14</b> Comparing means among two groups</a>
<ul>
<li class="chapter" data-level="14.1" data-path="twomean_packages_data.html"><a href="twomean_packages_data.html"><i class="fa fa-check"></i><b>14.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="14.2" data-path="paired-t-test.html"><a href="paired-t-test.html"><i class="fa fa-check"></i><b>14.2</b> Paired <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="paired-t-test.html"><a href="paired-t-test.html#calc_diffs"><i class="fa fa-check"></i><b>14.2.1</b> Calculate differences</a></li>
<li class="chapter" data-level="14.2.2" data-path="paired-t-test.html"><a href="paired-t-test.html#paired_Htest"><i class="fa fa-check"></i><b>14.2.2</b> Hypothesis statement</a></li>
<li class="chapter" data-level="14.2.3" data-path="paired-t-test.html"><a href="paired-t-test.html#graph_paried"><i class="fa fa-check"></i><b>14.2.3</b> A graph to accompany a paired <em>t</em>-test</a></li>
<li class="chapter" data-level="14.2.4" data-path="paired-t-test.html"><a href="paired-t-test.html#assump_paried"><i class="fa fa-check"></i><b>14.2.4</b> Assumptions of the paired <em>t</em>-test</a></li>
<li class="chapter" data-level="14.2.5" data-path="paired-t-test.html"><a href="paired-t-test.html#conduct_paired"><i class="fa fa-check"></i><b>14.2.5</b> Conduct the test</a></li>
<li class="chapter" data-level="14.2.6" data-path="paired-t-test.html"><a href="paired-t-test.html#concl_paired"><i class="fa fa-check"></i><b>14.2.6</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html"><i class="fa fa-check"></i><b>14.3</b> Two sample <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#twosamp_hyp"><i class="fa fa-check"></i><b>14.3.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="14.3.2" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#stats_2samp"><i class="fa fa-check"></i><b>14.3.2</b> A table of descriptive statistics</a></li>
<li class="chapter" data-level="14.3.3" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#graph_2samp"><i class="fa fa-check"></i><b>14.3.3</b> A graph to accompany a 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="14.3.4" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#twosamp_assump"><i class="fa fa-check"></i><b>14.3.4</b> Assumptions of the 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="14.3.5" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#conduct_2samptest"><i class="fa fa-check"></i><b>14.3.5</b> Conduct the 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="14.3.6" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#concl_2samp"><i class="fa fa-check"></i><b>14.3.6</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="assumpbad_2samp.html"><a href="assumpbad_2samp.html"><i class="fa fa-check"></i><b>14.4</b> When assumptions aren’t met</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="assumptions_trans.html"><a href="assumptions_trans.html"><i class="fa fa-check"></i><b>15</b> Checking assumptions and data transformations</a>
<ul>
<li class="chapter" data-level="15.1" data-path="assumptions_packages_data.html"><a href="assumptions_packages_data.html"><i class="fa fa-check"></i><b>15.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="15.2" data-path="checknorm_assum.html"><a href="checknorm_assum.html"><i class="fa fa-check"></i><b>15.2</b> Checking the normality assumption</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="checknorm_assum.html"><a href="checknorm_assum.html#quantile_plots"><i class="fa fa-check"></i><b>15.2.1</b> Normal quantile plots</a></li>
<li class="chapter" data-level="15.2.2" data-path="checknorm_assum.html"><a href="checknorm_assum.html#shapirottest"><i class="fa fa-check"></i><b>15.2.2</b> Shapiro-Wilk test for normality</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="levenetest.html"><a href="levenetest.html"><i class="fa fa-check"></i><b>15.3</b> Checking the equal-variance assumption</a></li>
<li class="chapter" data-level="15.4" data-path="transform.html"><a href="transform.html"><i class="fa fa-check"></i><b>15.4</b> Data transformations</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="transform.html"><a href="transform.html#log_transform"><i class="fa fa-check"></i><b>15.4.1</b> Log-transform</a></li>
<li class="chapter" data-level="15.4.2" data-path="transform.html"><a href="transform.html#zeroes"><i class="fa fa-check"></i><b>15.4.2</b> Dealing with zeroes</a></li>
<li class="chapter" data-level="15.4.3" data-path="transform.html"><a href="transform.html#logbases"><i class="fa fa-check"></i><b>15.4.3</b> Log bases</a></li>
<li class="chapter" data-level="15.4.4" data-path="transform.html"><a href="transform.html#back_transform"><i class="fa fa-check"></i><b>15.4.4</b> Back-transforming log data</a></li>
<li class="chapter" data-level="15.4.5" data-path="transform.html"><a href="transform.html#logit_transform"><i class="fa fa-check"></i><b>15.4.5</b> Logit transform</a></li>
<li class="chapter" data-level="15.4.6" data-path="transform.html"><a href="transform.html#logit_back"><i class="fa fa-check"></i><b>15.4.6</b> Back-transforming logit data</a></li>
<li class="chapter" data-level="15.4.7" data-path="transform.html"><a href="transform.html#when_back"><i class="fa fa-check"></i><b>15.4.7</b> When to back-transform?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="compare_three_more_means.html"><a href="compare_three_more_means.html"><i class="fa fa-check"></i><b>16</b> Comparing means among more than two groups</a>
<ul>
<li class="chapter" data-level="16.1" data-path="anova_packages_data.html"><a href="anova_packages_data.html"><i class="fa fa-check"></i><b>16.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="16.2" data-path="do_the_anova.html"><a href="do_the_anova.html"><i class="fa fa-check"></i><b>16.2</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_hyps"><i class="fa fa-check"></i><b>16.2.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="16.2.2" data-path="do_the_anova.html"><a href="do_the_anova.html#stats_anova"><i class="fa fa-check"></i><b>16.2.2</b> A table of descriptive statistics</a></li>
<li class="chapter" data-level="16.2.3" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_graph1"><i class="fa fa-check"></i><b>16.2.3</b> Visualize the data</a></li>
<li class="chapter" data-level="16.2.4" data-path="do_the_anova.html"><a href="do_the_anova.html#assump_anova"><i class="fa fa-check"></i><b>16.2.4</b> Assumptions of ANOVA</a></li>
<li class="chapter" data-level="16.2.5" data-path="do_the_anova.html"><a href="do_the_anova.html#do_anova1"><i class="fa fa-check"></i><b>16.2.5</b> Conduct the ANOVA test</a></li>
<li class="chapter" data-level="16.2.6" data-path="do_the_anova.html"><a href="do_the_anova.html#calculate-r2-for-the-anova"><i class="fa fa-check"></i><b>16.2.6</b> Calculate <span class="math inline">\(R^2\)</span> for the ANOVA</a></li>
<li class="chapter" data-level="16.2.7" data-path="do_the_anova.html"><a href="do_the_anova.html#tukey"><i class="fa fa-check"></i><b>16.2.7</b> Tukey-Kramer post-hoc test</a></li>
<li class="chapter" data-level="16.2.8" data-path="do_the_anova.html"><a href="do_the_anova.html#vis_tukey"><i class="fa fa-check"></i><b>16.2.8</b> Visualizing post-hoc test results</a></li>
<li class="chapter" data-level="16.2.9" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_conclusion"><i class="fa fa-check"></i><b>16.2.9</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="assumpbad_anova.html"><a href="assumpbad_anova.html"><i class="fa fa-check"></i><b>16.3</b> When assumptions aren’t met</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two_num.html"><a href="two_num.html"><i class="fa fa-check"></i><b>17</b> Analyzing associations between two numerical variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="twonum_packages_data.html"><a href="twonum_packages_data.html"><i class="fa fa-check"></i><b>17.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="17.2" data-path="pearson.html"><a href="pearson.html"><i class="fa fa-check"></i><b>17.2</b> Pearson correlation analysis</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="pearson.html"><a href="pearson.html#pearson_hyp"><i class="fa fa-check"></i><b>17.2.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="17.2.2" data-path="pearson.html"><a href="pearson.html#see_corr"><i class="fa fa-check"></i><b>17.2.2</b> Visualize the data</a></li>
<li class="chapter" data-level="17.2.3" data-path="pearson.html"><a href="pearson.html#corr_assumptions"><i class="fa fa-check"></i><b>17.2.3</b> Assumptions of correlation analysis</a></li>
<li class="chapter" data-level="17.2.4" data-path="pearson.html"><a href="pearson.html#do_corr"><i class="fa fa-check"></i><b>17.2.4</b> Conduct the correlation analysis</a></li>
<li class="chapter" data-level="17.2.5" data-path="pearson.html"><a href="pearson.html#concl_corr"><i class="fa fa-check"></i><b>17.2.5</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="rankcorr.html"><a href="rankcorr.html"><i class="fa fa-check"></i><b>17.3</b> Rank correlation (Spearman’s correlation)</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="rankcorr.html"><a href="rankcorr.html#hypothesis-statements"><i class="fa fa-check"></i><b>17.3.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="17.3.2" data-path="rankcorr.html"><a href="rankcorr.html#spearman_hyp"><i class="fa fa-check"></i><b>17.3.2</b> Visualize the data</a></li>
<li class="chapter" data-level="17.3.3" data-path="rankcorr.html"><a href="rankcorr.html#assum_spear"><i class="fa fa-check"></i><b>17.3.3</b> Assumptions of Spearman rank correlation</a></li>
<li class="chapter" data-level="17.3.4" data-path="rankcorr.html"><a href="rankcorr.html#conduct_spearman"><i class="fa fa-check"></i><b>17.3.4</b> Conduct the test</a></li>
<li class="chapter" data-level="17.3.5" data-path="rankcorr.html"><a href="rankcorr.html#spear_conclude"><i class="fa fa-check"></i><b>17.3.5</b> Concluding statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ls_regression.html"><a href="ls_regression.html"><i class="fa fa-check"></i><b>18</b> Least-squares linear regression</a>
<ul>
<li class="chapter" data-level="18.1" data-path="LSR_packages_data.html"><a href="LSR_packages_data.html"><i class="fa fa-check"></i><b>18.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="18.2" data-path="LSR.html"><a href="LSR.html"><i class="fa fa-check"></i><b>18.2</b> Least-squares regression analysis</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="LSR.html"><a href="LSR.html#LSR_line"><i class="fa fa-check"></i><b>18.2.1</b> Equation of a line and “least-squares line”</a></li>
<li class="chapter" data-level="18.2.2" data-path="LSR.html"><a href="LSR.html#LSR_hyp"><i class="fa fa-check"></i><b>18.2.2</b> Hypothesis testing or prediction?</a></li>
<li class="chapter" data-level="18.2.3" data-path="LSR.html"><a href="LSR.html#LSR_steps"><i class="fa fa-check"></i><b>18.2.3</b> Steps to conducting regression analysis</a></li>
<li class="chapter" data-level="18.2.4" data-path="LSR.html"><a href="LSR.html#LSR_alpha"><i class="fa fa-check"></i><b>18.2.4</b> State question and set the <span class="math inline">\(\alpha\)</span> level</a></li>
<li class="chapter" data-level="18.2.5" data-path="LSR.html"><a href="LSR.html#LSR_vis"><i class="fa fa-check"></i><b>18.2.5</b> Visualize the data</a></li>
<li class="chapter" data-level="18.2.6" data-path="LSR.html"><a href="LSR.html#LSR_scatter_interp"><i class="fa fa-check"></i><b>18.2.6</b> Interpreting a scatterplot</a></li>
<li class="chapter" data-level="18.2.7" data-path="LSR.html"><a href="LSR.html#LSR_assumptions"><i class="fa fa-check"></i><b>18.2.7</b> Checking assumptions of regression analysis</a></li>
<li class="chapter" data-level="18.2.8" data-path="LSR.html"><a href="LSR.html#residual-plots-when-you-have-missing-values"><i class="fa fa-check"></i><b>18.2.8</b> Residual plots when you have missing values</a></li>
<li class="chapter" data-level="18.2.9" data-path="LSR.html"><a href="LSR.html#transform-the-data"><i class="fa fa-check"></i><b>18.2.9</b> Transform the data</a></li>
<li class="chapter" data-level="18.2.10" data-path="LSR.html"><a href="LSR.html#conduct-the-regression-analysis"><i class="fa fa-check"></i><b>18.2.10</b> Conduct the regression analysis</a></li>
<li class="chapter" data-level="18.2.11" data-path="LSR.html"><a href="LSR.html#confidence-interval-for-the-slope"><i class="fa fa-check"></i><b>18.2.11</b> Confidence interval for the slope</a></li>
<li class="chapter" data-level="18.2.12" data-path="LSR.html"><a href="LSR.html#scatterplot-with-regression-confidence-bands"><i class="fa fa-check"></i><b>18.2.12</b> Scatterplot with regression confidence bands</a></li>
<li class="chapter" data-level="18.2.13" data-path="LSR.html"><a href="LSR.html#concluding-statement"><i class="fa fa-check"></i><b>18.2.13</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="making-predictions.html"><a href="making-predictions.html"><i class="fa fa-check"></i><b>18.3</b> Making predictions</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="making-predictions.html"><a href="making-predictions.html#back-transforming-regression-predictions"><i class="fa fa-check"></i><b>18.3.1</b> Back-transforming regression predictions</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="model-i-versus-model-ii-regression.html"><a href="model-i-versus-model-ii-regression.html"><i class="fa fa-check"></i><b>18.4</b> Model-I versus Model-II regression</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="model-i-versus-model-ii-regression.html"><a href="model-i-versus-model-ii-regression.html#definitions"><i class="fa fa-check"></i><b>18.4.1</b> Definitions</a></li>
<li class="chapter" data-level="18.4.2" data-path="model-i-versus-model-ii-regression.html"><a href="model-i-versus-model-ii-regression.html#which-one-do-i-use"><i class="fa fa-check"></i><b>18.4.2</b> Which one do I use?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="creating-tables-in-r-markdown.html"><a href="creating-tables-in-r-markdown.html"><i class="fa fa-check"></i>Creating tables in R Markdown</a>
<ul>
<li class="chapter" data-level="18.5" data-path="tables_packages.html"><a href="tables_packages.html"><i class="fa fa-check"></i><b>18.5</b> Load packages and import data</a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="tables_packages.html"><a href="tables_packages.html#skim_tables"><i class="fa fa-check"></i><b>18.5.1</b> Formatting output from the <code>skimr</code> package</a></li>
<li class="chapter" data-level="18.5.2" data-path="tables_packages.html"><a href="tables_packages.html#stats_nicetable"><i class="fa fa-check"></i><b>18.5.2</b> A nicely formatted table of descriptive statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="visual-markdown-editor.html"><a href="visual-markdown-editor.html"><i class="fa fa-check"></i>Visual Markdown Editor</a>
<ul>
<li class="chapter" data-level="" data-path="a-more-familiar-editing-environment.html"><a href="a-more-familiar-editing-environment.html"><i class="fa fa-check"></i>A more familiar editing environment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="common-errors-and-their-solutions.html"><a href="common-errors-and-their-solutions.html"><i class="fa fa-check"></i>Common errors and their solutions</a>
<ul>
<li class="chapter" data-level="" data-path="google-can-help.html"><a href="google-can-help.html"><i class="fa fa-check"></i>Google can help</a></li>
<li class="chapter" data-level="" data-path="rtools-required-during-install.html"><a href="rtools-required-during-install.html"><i class="fa fa-check"></i>Rtools required during install</a></li>
<li class="chapter" data-level="" data-path="could-not-find-function.html"><a href="could-not-find-function.html"><i class="fa fa-check"></i>Could not find function</a></li>
<li class="chapter" data-level="" data-path="there-is-no-package.html"><a href="there-is-no-package.html"><i class="fa fa-check"></i>There is no package</a></li>
<li class="chapter" data-level="" data-path="trying-to-use-cran-without-setting-a-mirror.html"><a href="trying-to-use-cran-without-setting-a-mirror.html"><i class="fa fa-check"></i>Trying to use CRAN without setting a mirror</a></li>
<li class="chapter" data-level="" data-path="pdf-latex-is-not-found.html"><a href="pdf-latex-is-not-found.html"><i class="fa fa-check"></i>PDF Latex is not found</a></li>
<li class="chapter" data-level="" data-path="error-in-parse.html"><a href="error-in-parse.html"><i class="fa fa-check"></i>Error in parse</a></li>
<li class="chapter" data-level="" data-path="no-such-file-or-directory-exists.html"><a href="no-such-file-or-directory-exists.html"><i class="fa fa-check"></i>No such file or directory exists</a></li>
<li class="chapter" data-level="" data-path="messy-output-when-loading-packages.html"><a href="messy-output-when-loading-packages.html"><i class="fa fa-check"></i>Messy output when loading packages</a></li>
<li class="chapter" data-level="" data-path="unused-argument.html"><a href="unused-argument.html"><i class="fa fa-check"></i>Unused argument</a></li>
<li class="chapter" data-level="" data-path="object-not-found.html"><a href="object-not-found.html"><i class="fa fa-check"></i>Object not found</a></li>
<li class="chapter" data-level="" data-path="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><i class="fa fa-check"></i>Figure caption doesn’t show up below figure in knitted document</a></li>
<li class="chapter" data-level="" data-path="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><i class="fa fa-check"></i>Filename, directory name, or volume label syntax is incorrect</a></li>
<li class="chapter" data-level="" data-path="installing-packages-there-is-a-binary-version-available.html"><a href="installing-packages-there-is-a-binary-version-available.html"><i class="fa fa-check"></i>Installing packages: there is a binary version available</a></li>
<li class="chapter" data-level="" data-path="unicode-knitting-error.html"><a href="unicode-knitting-error.html"><i class="fa fa-check"></i>Unicode knitting error</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hyp_example" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> An hypothesis test example<a href="hyp_example.html#hyp_example" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When defending territories along streams, males of the damselfly species <em>Calopteryx maculata</em> (pictured <a href="https://en.wikipedia.org/wiki/Ebony_jewelwing#/media/File:Ebony_Jewelwing,_male,_Gatineau_Park.jpg">here</a>) often battle intruders in the air, flying around and around in circles with their foe for minutes at a time. No one knows whether these battles are flown in a consistent direction, i.e. predominantly clockwise or counter-clockwise, as would be expected if the damselflies exhibited a form of “handedness”, like many animals do.</p>
<p>A researcher was curious about this because he had worked with these damselflies for years and witnessed many territorial bouts (see exmaple research <a href="http://www.nrcresearchpress.com/doi/abs/10.1139/z00-130#.WdFv0GKPKJU">here</a>).</p>
<p>The researcher conducted a study (fictional) in which he video-recorded 20 male damselflies defending territories (all randomly sampled from a population), and determined the predominant direction of flight during circular flight battles. One battle per damselfly was recorded, and each battle was known to involve a unique combattant.</p>
<p>He found that in 17 out of 20 bouts the damselflies flew in the counter-clockwise direction.</p>
<p>Should this result be considered evidence of handedness in this population?</p>
<hr />
<p>For this example, we’ll use the imported <code>damselfly</code> dataset, which includes the single categorical variable of interest “direction”, and there are two categories: “clockwise” and “counter_clockwise”.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="hyp_example.html#cb156-1" aria-hidden="true" tabindex="-1"></a>damselfly</span></code></pre></div>
<pre><code>## # A tibble: 20 × 1
##    direction        
##    &lt;chr&gt;            
##  1 clockwise        
##  2 counter_clockwise
##  3 counter_clockwise
##  4 clockwise        
##  5 counter_clockwise
##  6 counter_clockwise
##  7 counter_clockwise
##  8 counter_clockwise
##  9 counter_clockwise
## 10 counter_clockwise
## 11 counter_clockwise
## 12 clockwise        
## 13 counter_clockwise
## 14 counter_clockwise
## 15 counter_clockwise
## 16 counter_clockwise
## 17 counter_clockwise
## 18 counter_clockwise
## 19 counter_clockwise
## 20 counter_clockwise</code></pre>
<hr />
<div id="follow_hyp_steps" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Following the steps to hypothesis testing<a href="hyp_example.html#follow_hyp_steps" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the damselfly example, we have <em>n</em> = 20 <strong>random trials</strong>, each of which has two possible outcomes: clockwise battle or counter-clockwise battle. This conforms to the expectations of a <strong>binomial test</strong>, for which the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Binomial-distribution"><em>binomial distribution</em></a> is used to generate the appropriate <strong>null distribution</strong>. We’ll learn about the binomial test in a later tutorial.</p>
<p>For the present tutorial, we’re going to generate a null distribution via simulation.</p>
<p>To do this, we need to consider what our “null expectation” is, i.e. if there was truly no handedness among the damselflies.</p>
<p>Our null expectation is that clockwise and counter-clockwise battles would occur with equal frequency. In other words, if we focus on counter-clockwise battles as the category of interest, then on average - across many, many battles - we’d expect those to make up <span class="math inline">\(p_0 = 0.5\)</span> of the battles. This is just like flipping a fair coin: over the long run (i.e. over many, many coin flips), we’d expect heads to make up half the outcomes, i.e. <span class="math inline">\(p_0 = 0.5\)</span>.</p>
<p>We can now specify our <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>:</p>
<p><strong>H<sub>0</sub></strong>: The proportion of damselfly battles in the population flown in the counter-clockwise direction is 0.5 (<span class="math inline">\(p_0 = 0.5\)</span>)</p>
<p><strong>H<sub>A</sub></strong>: The proportion of damselfly battles in the population flown in the counter-clockwise direction is not 0.5 (<span class="math inline">\(p_0 \ne 0.5\)</span>)</p>
<p>We’ll set <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>Although our <span class="math inline">\(H_0\)</span> makes a specific statement about a <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Proportion">proportion</a> (<span class="math inline">\(p_0\)</span>), our <em>test statistic</em> will actually be the <strong>number of battles that occurred in a counter-clockwise direction</strong>. Of course, we can re-express this number as a proportion, but convention is that we use the number (frequency) instead.</p>
<p>As indicated by the <strong>H<sub>A</sub></strong> statement, we’ll use a 2-tailed <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Alternative-hypothesis">alternative hypothesis</a> because we have no reason to exclude the possibility that clockwise battles are in fact more predominant.</p>
<div class="note">
<p><strong>TIP</strong>:
The symbol for “not equal” can be done using this syntax: <code>$\ne$</code>. Simply type that as part of your regular markdown text. A subscript can be added by prefacing the character with a “_“. Thus, in the alternative hypothesis statement above, we used <code>$p_0 \ne 0.5$</code> to create the <span class="math inline">\(p_0 \ne 0.5\)</span>.</p>
</div>
</div>
<div id="sim_null" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Simulating a “null distribution”<a href="hyp_example.html#sim_null" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For our damselfly example, we can easily simulate the random trials (20 territorial flight battles, each yielding one of 2 outcomes) by using what we learned in the previous <a href="estimation.html#estimation">tutorial</a> about simulations in R.</p>
<p>First, we’ll create a tibble object called “null_options” that holds a categorical variable “direction” with two categories, “clockwise” and “counter_clockwise”:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="hyp_example.html#cb158-1" aria-hidden="true" tabindex="-1"></a>null_options <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">direction =</span> <span class="fu">c</span>(<span class="st">&quot;clockwise&quot;</span>, <span class="st">&quot;counter_clockwise&quot;</span>))</span></code></pre></div>
<p>Have a look at the resulting object:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="hyp_example.html#cb159-1" aria-hidden="true" tabindex="-1"></a>null_options</span></code></pre></div>
<pre><code>## # A tibble: 2 × 1
##   direction        
##   &lt;chr&gt;            
## 1 clockwise        
## 2 counter_clockwise</code></pre>
<p>Now we can use the <code>rep_slice_sample</code> function from the <code>infer</code> package (which we learned about in the last <a href="estimation.html#estimation">tutorial</a>) to simulate a large number of repetitions of our <em>n</em> = 20 random trials. The number of repetitions is governed by the <em>reps</em> argument.</p>
<p>We’ll set the seed first, to ensure everyone gets the same result for this initial demonstration repetition.</p>
<p>Let’s start with a single repetition of <em>n</em> = 20 random trials. We’ll explain the code after:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="hyp_example.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">199</span>)</span>
<span id="cb161-2"><a href="hyp_example.html#cb161-2" aria-hidden="true" tabindex="-1"></a>num.reps <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb161-3"><a href="hyp_example.html#cb161-3" aria-hidden="true" tabindex="-1"></a>null_options <span class="sc">%&gt;%</span></span>
<span id="cb161-4"><a href="hyp_example.html#cb161-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_slice_sample</span>(<span class="at">n =</span> <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">weight_by =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="at">reps =</span> num.reps) <span class="sc">%&gt;%</span></span>
<span id="cb161-5"><a href="hyp_example.html#cb161-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(direction)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
## # Groups:   replicate [1]
##   replicate direction             n
##       &lt;int&gt; &lt;chr&gt;             &lt;int&gt;
## 1         1 clockwise             9
## 2         1 counter_clockwise    11</code></pre>
<ul>
<li>We first set the seed (using integer 199 here; arbitrarily chosen)</li>
<li>Next we create an object “num.reps” that is simply one number: the number of replications we wish to run (here, 1)</li>
<li>We tell R we’re using the “null_options” object (created previously) for input into the subsequent lines, using the pipe (%&gt;%) to continue the code</li>
<li>We use the <code>rep_slice_sample</code> function, setting the number of trials <em>n</em> to 20, and ensuring that we use sampling with replacement here (“replace = T”) because our “null_options” object has only two observations to sample from, and we need 20 total;</li>
<li>You can think of the “weight_by” argument as a way to control the relative <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Probability">probability</a> of sampling each of the rows in the input tibble (here, the “null_options” tibble). Here we provide two values (0.5, 0.5), specifying that we want each of the two rows in the tibble to have equal likelihood of being sampled at random. This corresponds to what we want for our null expectation, and for the generation of the null distribution</li>
<li>The last argument to the <code>rep_slice_sample</code> function is “reps = num.reps”, using our created object to tell R that we want only one repetition of the 20 trials</li>
<li>In the last line of code we use the <code>count</code> function to tally the number of observations belonging to each of the two categories in the “direction” variable</li>
</ul>
<p>So you see that the output above is a tibble with 3 variables: “replicate”, “direction”, and “n”.</p>
<p>We’re specifically interested in the number of times (the frequency) out of the 20 trials that the damselfly battle was predominantly “counter_clockwise” (what we consider a “success”). So in our first repetition here, 11 of the trials were predominantly in the counter-clockwise direction.</p>
<p>Now what we need to do is run many thousands of repetitions (we’ll do 10^{5}), and each time tally the number of battles (out of the 20 trials) in which the direction was counter-clockwise.</p>
<p>This will generate a reasonable approximation of a <strong>null distribution</strong> for our study.</p>
<p>After the setting the seed, we create an object that simply holds the number of replications we wish to run.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="hyp_example.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">199</span>)</span>
<span id="cb163-2"><a href="hyp_example.html#cb163-2" aria-hidden="true" tabindex="-1"></a>num.reps <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb163-3"><a href="hyp_example.html#cb163-3" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="ot">&lt;-</span> null_options <span class="sc">%&gt;%</span></span>
<span id="cb163-4"><a href="hyp_example.html#cb163-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep_slice_sample</span>(<span class="at">n =</span> <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">weight_by =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="at">reps =</span> num.reps) <span class="sc">%&gt;%</span></span>
<span id="cb163-5"><a href="hyp_example.html#cb163-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(direction) <span class="sc">%&gt;%</span></span>
<span id="cb163-6"><a href="hyp_example.html#cb163-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(direction <span class="sc">==</span> <span class="st">&quot;counter_clockwise&quot;</span>)</span></code></pre></div>
<p>In the above code chunk, we:</p>
<ul>
<li>assign our output to a new object called “dull_distribution”</li>
<li>We changed the “reps” argument for the <code>rep_slice_sample</code> function to 10^{5} (all other arguments stay the same).</li>
<li>We use the <code>count</code> function to tally the number of observations belonging to each of the two categories in the “direction” variable</li>
<li>We then <code>filter</code> the output from our sampling to the rows with the “direction” variable equal to “counter_clockwise”</li>
</ul>
<p>Let’s look at the resulting object:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="hyp_example.html#cb164-1" aria-hidden="true" tabindex="-1"></a>null_distribution</span></code></pre></div>
<pre><code>## # A tibble: 100,000 × 3
## # Groups:   replicate [100,000]
##    replicate direction             n
##        &lt;int&gt; &lt;chr&gt;             &lt;int&gt;
##  1         1 counter_clockwise    11
##  2         2 counter_clockwise     9
##  3         3 counter_clockwise     8
##  4         4 counter_clockwise    11
##  5         5 counter_clockwise    13
##  6         6 counter_clockwise     9
##  7         7 counter_clockwise     9
##  8         8 counter_clockwise    12
##  9         9 counter_clockwise     6
## 10        10 counter_clockwise     9
## # … with 99,990 more rows</code></pre>
<p>We have a tibble with the number of rows equal to the number of replications we performed (100000), three variables (“replicate”, “direction”, and “n”), and the key information are the numbers in the “n” variable. These represent the number of battles (out of 20) that were predominantly in the counter-clockwise direction.</p>
<p>We can now create a histogram of these data, thus producing an approximation of a “null distribution”.</p>
<p>The only difference here, compared to previous times we’ve created histograms, is that we add the <code>after_stat(density)</code> argument to the <code>aes</code> part of the <code>ggplot</code> function. This tells R to display the relative frequency (= probability density) rather than the raw counts on the y-axis. Notice we also use “binwidth = 1”, because we want to see a bar for each potential outcome (0 through 20).</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="hyp_example.html#cb166-1" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="sc">%&gt;%</span></span>
<span id="cb166-2"><a href="hyp_example.html#cb166-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="fu">after_stat</span>(density))) <span class="sc">+</span></span>
<span id="cb166-3"><a href="hyp_example.html#cb166-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">&quot;lightgrey&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb166-4"><a href="hyp_example.html#cb166-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb166-5"><a href="hyp_example.html#cb166-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of counter-clockwise battles&quot;</span>) <span class="sc">+</span></span>
<span id="cb166-6"><a href="hyp_example.html#cb166-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb166-7"><a href="hyp_example.html#cb166-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-56"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-56-1.png" alt="Approximate null distribution for the damselfly study, with n = 20 trials, and probability of success = 0.5 in each trial. Data are from 100000 repetitions." width="480" />
<p class="caption">
Figure 10.1: Approximate null distribution for the damselfly study, with n = 20 trials, and probability of success = 0.5 in each trial. Data are from 100000 repetitions.
</p>
</div>
<p>The null distribution above shows us that if the null hypothesis was true, the most probable outcome would be 10 counter-clockwise battles out of 20. But other outcomes are of course possible, with decreasing probability towards zero and twenty.</p>
</div>
<div id="calc_p" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> Calculating the <em>P</em>-value<a href="hyp_example.html#calc_p" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#P-value"><strong><em>P</em>-value</strong></a> is defined as the probability of observing an outcome as extreme or more extreme as the observed value of the test statistic, if the null hypothesis were true.</p>
<p>In our damselfly study, we observed 17 out of 20 battles to be in the counter-clockwise direction.</p>
<p>We can calculate a <strong><em>P</em>-value</strong> as follows:</p>
<ul>
<li>first calculate the fraction of the 10^{5} values in our null distribution that are equal to or greater than our observed test statistic value (here, 17)</li>
<li>if we have a 2-tailed alternative hypothesis, then we also need to calculate the fraction of the 10^{5} values in our null distribution that are less than or equal to 3, which is the mirror number to 17 in the opposite side of the distribution.</li>
</ul>
<div class="note">
<p>Although our approximate null distribution that we created looks quite symmetrical, it’s best not to assume it is (because recall that we generated this via simulation). Therefore we don’t simply multiply the first value we calculate above by two. In future tutorials you’ll learn how to calculate <strong><em>P</em>-values</strong> using built-in R functions and theoretical probability distributions.</p>
</div>
<p>In the <a href="coding_basics.html#coding_basics">Introductory R Tutorials</a> you learned how to use <strong>logical comparison operators</strong> such as <code>&gt;</code> and <code>&lt;=</code>. We’ll use these here.</p>
<p>Let’s find out how many values within the variable <code>n</code> in our <code>null_distribution</code> tibble are less than or equal to 3, or greater than or equal to 17:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="hyp_example.html#cb167-1" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="sc">%&gt;%</span></span>
<span id="cb167-2"><a href="hyp_example.html#cb167-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">|</span> n <span class="sc">&gt;=</span> <span class="dv">17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb167-3"><a href="hyp_example.html#cb167-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>() </span></code></pre></div>
<pre><code>## [1] 254</code></pre>
<p>This code uses the <code>filter</code> function to return only the rows that meet the condition specified: the “n” variable value less than or equal to 3, OR (using the “|” symbol) greater than or equal to 17.</p>
<p>The <code>nrow</code> function then simply counts the number of rows in the resulting (filtered) tibble.</p>
<p>We see that among the 10^{5} replications we ran, 254 yielded outcomes in which 3 or fewer, or 17 or more out of 20 battles were in the counter-clockwise direction.</p>
<p>To calculate the <em>P</em>-value, we need to divide the 254 by the total number of reps that we conducted, here 10^{5}.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="hyp_example.html#cb169-1" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="sc">%&gt;%</span></span>
<span id="cb169-2"><a href="hyp_example.html#cb169-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">|</span> n <span class="sc">&gt;=</span> <span class="dv">17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb169-3"><a href="hyp_example.html#cb169-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>() <span class="sc">/</span> num.reps</span></code></pre></div>
<pre><code>## [1] 0.00254</code></pre>
<p>So the <strong><em>P</em>-value</strong> associated with our observed test statistic is 0.00254.</p>
</div>
<div id="concluding_statement" class="section level3 hasAnchor" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> Writing a concluding statement<a href="hyp_example.html#concluding_statement" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is important to write a concluding statement that talks about the actual findings of the study. For example:</p>
<p>In their territorial bouts, the damselflies flew in a counter-clockwise direction significantly more than expected (17 counter-clockwise flights out of <em>n</em> = 20 trials; <em>P</em>-value = 0.003). This is consistent with the idea that there is “handedness” in this population of <em>C. maculata</em>.</p>
<p>It is also crucial that you report the sample size (here, number of random trials), the value of the observed test statistic (here 17), and the associated <strong><em>P</em>-value</strong>. Note we rounded the <strong><em>P</em>-value</strong> to three decimal places.</p>
<p>When we learn new types of statistical test, we’ll adjust our concluding statements accordingly.</p>
<ol style="list-style-type: decimal">
<li>Using this tutorial as a guide, try to repeat all the steps of a hypothesis test for Example 6.2 in the text book (concerning handedness in toads).</li>
</ol>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="hyp_steps.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="single_cat.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202.pdf", "BIOL202.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
