<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12.2 Paired t-test | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="12.2 Paired t-test | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12.2 Paired t-test | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2022-09-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="twomean_packages_data.html"/>
<link rel="next" href="twosamp_ttest.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li class="part"><span><b>Preface</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>Author</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="ubco-biology-open-materials.html"><a href="ubco-biology-open-materials.html"><i class="fa fa-check"></i>UBCO Biology open materials</a></li>
</ul></li>
<li class="part"><span><b>Getting started with R, RStudio &amp; R Markdown</b></span></li>
<li class="chapter" data-level="1" data-path="what_is_R.html"><a href="what_is_R.html"><i class="fa fa-check"></i><b>1</b> What are R and RStudio?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install_R_Rstudio.html"><a href="install_R_Rstudio.html"><i class="fa fa-check"></i><b>1.1</b> Installing R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="start_r.html"><a href="start_r.html"><i class="fa fa-check"></i><b>2</b> Start using R &amp; RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Rstudio_interface.html"><a href="Rstudio_interface.html"><i class="fa fa-check"></i><b>2.1</b> The RStudio Interface</a></li>
<li class="chapter" data-level="2.2" data-path="coding_basics.html"><a href="coding_basics.html"><i class="fa fa-check"></i><b>2.2</b> Coding basics</a></li>
<li class="chapter" data-level="2.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>2.3</b> R packages</a></li>
<li class="chapter" data-level="2.4" data-path="package_install.html"><a href="package_install.html"><i class="fa fa-check"></i><b>2.4</b> Package installation</a></li>
<li class="chapter" data-level="2.5" data-path="package_load.html"><a href="package_load.html"><i class="fa fa-check"></i><b>2.5</b> Package loading</a></li>
<li class="chapter" data-level="2.6" data-path="intro_markdown.html"><a href="intro_markdown.html"><i class="fa fa-check"></i><b>2.6</b> Intro to R Markdown</a></li>
<li class="chapter" data-level="2.7" data-path="lit_programming.html"><a href="lit_programming.html"><i class="fa fa-check"></i><b>2.7</b> Literate programming with R Markdown</a></li>
<li class="chapter" data-level="2.8" data-path="veryify_knit.html"><a href="veryify_knit.html"><i class="fa fa-check"></i><b>2.8</b> Making sure R Markdown knits to PDF</a></li>
<li class="chapter" data-level="2.9" data-path="r_resources.html"><a href="r_resources.html"><i class="fa fa-check"></i><b>2.9</b> Extra resources</a></li>
<li class="chapter" data-level="2.10" data-path="online_resources.html"><a href="online_resources.html"><i class="fa fa-check"></i><b>2.10</b> R Resources Online</a></li>
<li class="chapter" data-level="2.11" data-path="rmd_graphing.html"><a href="rmd_graphing.html"><i class="fa fa-check"></i><b>2.11</b> Setting up R Markdown for graphing</a></li>
<li class="chapter" data-level="2.12" data-path="example_answer.html"><a href="example_answer.html"><i class="fa fa-check"></i><b>2.12</b> Example question / answer</a></li>
<li class="chapter" data-level="2.13" data-path="knit_assign.html"><a href="knit_assign.html"><i class="fa fa-check"></i><b>2.13</b> Knitting your assignment to PDF</a></li>
<li class="chapter" data-level="2.14" data-path="submit_rmd.html"><a href="submit_rmd.html"><i class="fa fa-check"></i><b>2.14</b> Submit your assignment</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data_import.html"><a href="data_import.html"><i class="fa fa-check"></i><b>3</b> Preparing and importing Tidy Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tidy_data.html"><a href="tidy_data.html"><i class="fa fa-check"></i><b>3.1</b> Tidy data</a></li>
<li class="chapter" data-level="3.2" data-path="import_csv_url.html"><a href="import_csv_url.html"><i class="fa fa-check"></i><b>3.2</b> Import a CSV file from a website</a></li>
<li class="chapter" data-level="3.3" data-path="create_csv_local.html"><a href="create_csv_local.html"><i class="fa fa-check"></i><b>3.3</b> Create a CSV file</a></li>
<li class="chapter" data-level="3.4" data-path="import_csv_local.html"><a href="import_csv_local.html"><i class="fa fa-check"></i><b>3.4</b> Import a local CSV file</a></li>
<li class="chapter" data-level="3.5" data-path="data_overview.html"><a href="data_overview.html"><i class="fa fa-check"></i><b>3.5</b> Get an overview of a dataset</a></li>
<li class="chapter" data-level="3.6" data-path="tutorial-practice-activities.html"><a href="tutorial-practice-activities.html"><i class="fa fa-check"></i><b>3.6</b> Tutorial practice activities</a></li>
</ul></li>
<li class="part"><span><b>Visualizing and Describing Data</b></span></li>
<li class="chapter" data-level="4" data-path="vis_variable.html"><a href="vis_variable.html"><i class="fa fa-check"></i><b>4</b> Visualizing a single variable</a>
<ul>
<li class="chapter" data-level="4.1" data-path="vis_packages_data.html"><a href="vis_packages_data.html"><i class="fa fa-check"></i><b>4.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="4.2" data-path="vis_data_overview.html"><a href="vis_data_overview.html"><i class="fa fa-check"></i><b>4.2</b> Get an overview of the data</a></li>
<li class="chapter" data-level="4.3" data-path="vis_cat_freq_table.html"><a href="vis_cat_freq_table.html"><i class="fa fa-check"></i><b>4.3</b> Create a frequency table</a></li>
<li class="chapter" data-level="4.4" data-path="vis_cat_barchart.html"><a href="vis_cat_barchart.html"><i class="fa fa-check"></i><b>4.4</b> Create a bar graph</a></li>
<li class="chapter" data-level="4.5" data-path="vis_histogram.html"><a href="vis_histogram.html"><i class="fa fa-check"></i><b>4.5</b> Create a histogram</a></li>
<li class="chapter" data-level="4.6" data-path="vis_describe_hist.html"><a href="vis_describe_hist.html"><i class="fa fa-check"></i><b>4.6</b> Describing a histogram</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="vis_describe.html"><a href="vis_describe.html"><i class="fa fa-check"></i><b>5</b> Describing a single variable</a>
<ul>
<li class="chapter" data-level="5.1" data-path="desc_packages_data.html"><a href="desc_packages_data.html"><i class="fa fa-check"></i><b>5.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="5.2" data-path="desc_cat_Var.html"><a href="desc_cat_Var.html"><i class="fa fa-check"></i><b>5.2</b> Describing a categorical variable</a></li>
<li class="chapter" data-level="5.3" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html"><i class="fa fa-check"></i><b>5.3</b> Describing a numerical variable</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html#median_IQR"><i class="fa fa-check"></i><b>5.3.1</b> Calculating the median &amp; IQR</a></li>
<li class="chapter" data-level="5.3.2" data-path="desc_numeric_var.html"><a href="desc_numeric_var.html#mean_sd"><i class="fa fa-check"></i><b>5.3.2</b> Calculating the mean &amp; standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="desc_numeric_var_cat.html"><a href="desc_numeric_var_cat.html"><i class="fa fa-check"></i><b>5.4</b> Describing a numerical variable grouped by a categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="vis_twovar.html"><a href="vis_twovar.html"><i class="fa fa-check"></i><b>6</b> Visualizing associations between two variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="vis2_packages_data.html"><a href="vis2_packages_data.html"><i class="fa fa-check"></i><b>6.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="6.2" data-path="vis2_2cat.html"><a href="vis2_2cat.html"><i class="fa fa-check"></i><b>6.2</b> Visualizing association between two categorical variables</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="vis2_2cat.html"><a href="vis2_2cat.html#vis2_cont_table"><i class="fa fa-check"></i><b>6.2.1</b> Constructing a contingency table</a></li>
<li class="chapter" data-level="6.2.2" data-path="vis2_2cat.html"><a href="vis2_2cat.html#grouped_bar_graphs"><i class="fa fa-check"></i><b>6.2.2</b> Constructing a grouped bar graph</a></li>
<li class="chapter" data-level="6.2.3" data-path="vis2_2cat.html"><a href="vis2_2cat.html#mosaic_plot"><i class="fa fa-check"></i><b>6.2.3</b> Constructing a mosaic plot</a></li>
<li class="chapter" data-level="6.2.4" data-path="vis2_2cat.html"><a href="vis2_2cat.html#interpret_mosaic"><i class="fa fa-check"></i><b>6.2.4</b> Interpreting mosaic plots</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="two_numeric.html"><a href="two_numeric.html"><i class="fa fa-check"></i><b>6.3</b> Visualizing association between two numeric variables</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="two_numeric.html"><a href="two_numeric.html#interpret_scatter"><i class="fa fa-check"></i><b>6.3.1</b> Interpreting and describing a scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html"><i class="fa fa-check"></i><b>6.4</b> Visualizing association between a numeric and a categorical variable</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#stripchart"><i class="fa fa-check"></i><b>6.4.1</b> Create a stripchart</a></li>
<li class="chapter" data-level="6.4.2" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#violinplot"><i class="fa fa-check"></i><b>6.4.2</b> Create a violin plot</a></li>
<li class="chapter" data-level="6.4.3" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#boxplots"><i class="fa fa-check"></i><b>6.4.3</b> Creating a boxplot</a></li>
<li class="chapter" data-level="6.4.4" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#bestplot"><i class="fa fa-check"></i><b>6.4.4</b> Combining violin and boxplots</a></li>
<li class="chapter" data-level="6.4.5" data-path="numeric_vs_cat.html"><a href="numeric_vs_cat.html#interp_violin"><i class="fa fa-check"></i><b>6.4.5</b> Interpreting stripcharts and boxplots</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Inferential Statistics</b></span></li>
<li class="chapter" data-level="7" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>7</b> Sampling, Estimation, &amp; Uncertainty</a>
<ul>
<li class="chapter" data-level="7.1" data-path="estimation_packages_data.html"><a href="estimation_packages_data.html"><i class="fa fa-check"></i><b>7.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="7.2" data-path="sampling_functions.html"><a href="sampling_functions.html"><i class="fa fa-check"></i><b>7.2</b> Functions for sampling</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sampling_functions.html"><a href="sampling_functions.html#setseed"><i class="fa fa-check"></i><b>7.2.1</b> Setting the “seed” for random sampling</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sampling_error.html"><a href="sampling_error.html"><i class="fa fa-check"></i><b>7.3</b> Sampling error</a></li>
<li class="chapter" data-level="7.4" data-path="sampdistmean.html"><a href="sampdistmean.html"><i class="fa fa-check"></i><b>7.4</b> Sampling distribution of the mean</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sampdistmean.html"><a href="sampdistmean.html#hist_samdist"><i class="fa fa-check"></i><b>7.4.1</b> Visualize the sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sem_page.html"><a href="sem_page.html"><i class="fa fa-check"></i><b>7.5</b> Standard error of the mean</a></li>
<li class="chapter" data-level="7.6" data-path="confint_rough.html"><a href="confint_rough.html"><i class="fa fa-check"></i><b>7.6</b> Rule of thumb 95% confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="hypothesis.html"><a href="hypothesis.html"><i class="fa fa-check"></i><b>8</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="hyp_packages_data.html"><a href="hyp_packages_data.html"><i class="fa fa-check"></i><b>8.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="8.2" data-path="hyp_steps.html"><a href="hyp_steps.html"><i class="fa fa-check"></i><b>8.2</b> Steps to hypothesis testing</a></li>
<li class="chapter" data-level="8.3" data-path="hyp_example.html"><a href="hyp_example.html"><i class="fa fa-check"></i><b>8.3</b> An hypothesis test example</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="hyp_example.html"><a href="hyp_example.html#follow_hyp_steps"><i class="fa fa-check"></i><b>8.3.1</b> Following the steps to hypothesis testing</a></li>
<li class="chapter" data-level="8.3.2" data-path="hyp_example.html"><a href="hyp_example.html#sim_null"><i class="fa fa-check"></i><b>8.3.2</b> Simulating a “null distribution”</a></li>
<li class="chapter" data-level="8.3.3" data-path="hyp_example.html"><a href="hyp_example.html#calc_p"><i class="fa fa-check"></i><b>8.3.3</b> Calculating the <em>P</em>-value</a></li>
<li class="chapter" data-level="8.3.4" data-path="hyp_example.html"><a href="hyp_example.html#concluding_statement"><i class="fa fa-check"></i><b>8.3.4</b> Writing a concluding statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="single_cat.html"><a href="single_cat.html"><i class="fa fa-check"></i><b>9</b> Analyzing a single categorical variable</a>
<ul>
<li class="chapter" data-level="9.1" data-path="singcat_packages_data.html"><a href="singcat_packages_data.html"><i class="fa fa-check"></i><b>9.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="9.2" data-path="estproportions.html"><a href="estproportions.html"><i class="fa fa-check"></i><b>9.2</b> Estimating proportions</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="estproportions.html"><a href="estproportions.html#sterr_prop"><i class="fa fa-check"></i><b>9.2.1</b> Standard error for a proportion</a></li>
<li class="chapter" data-level="9.2.2" data-path="estproportions.html"><a href="estproportions.html#confint_prop"><i class="fa fa-check"></i><b>9.2.2</b> Confidence interval for a proportion</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="binomdist.html"><a href="binomdist.html"><i class="fa fa-check"></i><b>9.3</b> Binomial distribution</a></li>
<li class="chapter" data-level="9.4" data-path="binom_test.html"><a href="binom_test.html"><i class="fa fa-check"></i><b>9.4</b> Binomial test</a></li>
<li class="chapter" data-level="9.5" data-path="prophypconf.html"><a href="prophypconf.html"><i class="fa fa-check"></i><b>9.5</b> Confidence interval approach to hypothesis testing</a></li>
<li class="chapter" data-level="9.6" data-path="GOF_test.html"><a href="GOF_test.html"><i class="fa fa-check"></i><b>9.6</b> Goodness-of-fit tests</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="two_cat.html"><a href="two_cat.html"><i class="fa fa-check"></i><b>10</b> Analyzing associations between two categorical variables</a>
<ul>
<li class="chapter" data-level="10.1" data-path="twocat_packages_data.html"><a href="twocat_packages_data.html"><i class="fa fa-check"></i><b>10.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="10.2" data-path="fishertest.html"><a href="fishertest.html"><i class="fa fa-check"></i><b>10.2</b> Fisher’s Exact Test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="fishertest.html"><a href="fishertest.html#fisher_hyp"><i class="fa fa-check"></i><b>10.2.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="10.2.2" data-path="fishertest.html"><a href="fishertest.html#show_cont_table"><i class="fa fa-check"></i><b>10.2.2</b> Display a contingency table</a></li>
<li class="chapter" data-level="10.2.3" data-path="fishertest.html"><a href="fishertest.html#show_mosaic"><i class="fa fa-check"></i><b>10.2.3</b> Display a mosaic plot</a></li>
<li class="chapter" data-level="10.2.4" data-path="fishertest.html"><a href="fishertest.html#do_fisher"><i class="fa fa-check"></i><b>10.2.4</b> Conduct the Fisher’s Exact Test</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="odds.html"><a href="odds.html"><i class="fa fa-check"></i><b>10.3</b> Estimate the Odds of getting sick</a></li>
<li class="chapter" data-level="10.4" data-path="oddsratio.html"><a href="oddsratio.html"><i class="fa fa-check"></i><b>10.4</b> Estimate the odds ratio</a></li>
<li class="chapter" data-level="10.5" data-path="chisquare.html"><a href="chisquare.html"><i class="fa fa-check"></i><b>10.5</b> <span class="math inline">\(\chi\)</span><sup>2</sup> Contingency Test</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="chisquare.html"><a href="chisquare.html#chihyp"><i class="fa fa-check"></i><b>10.5.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="10.5.2" data-path="chisquare.html"><a href="chisquare.html#showwormcont"><i class="fa fa-check"></i><b>10.5.2</b> Display the contingency table</a></li>
<li class="chapter" data-level="10.5.3" data-path="chisquare.html"><a href="chisquare.html#mosaicworm"><i class="fa fa-check"></i><b>10.5.3</b> Visualize a mosaic plot</a></li>
<li class="chapter" data-level="10.5.4" data-path="chisquare.html"><a href="chisquare.html#checkchiassum"><i class="fa fa-check"></i><b>10.5.4</b> Check the assumptions</a></li>
<li class="chapter" data-level="10.5.5" data-path="chisquare.html"><a href="chisquare.html#chiresults"><i class="fa fa-check"></i><b>10.5.5</b> Get the results of the test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="single_numeric.html"><a href="single_numeric.html"><i class="fa fa-check"></i><b>11</b> Analyzing a single numerical variable</a>
<ul>
<li class="chapter" data-level="11.1" data-path="singlenum_packages_data.html"><a href="singlenum_packages_data.html"><i class="fa fa-check"></i><b>11.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="11.2" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html"><i class="fa fa-check"></i><b>11.2</b> One-sample <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_hyp"><i class="fa fa-check"></i><b>11.2.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="11.2.2" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_assumptions"><i class="fa fa-check"></i><b>11.2.2</b> Assumptions of one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="11.2.3" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_graph"><i class="fa fa-check"></i><b>11.2.3</b> A graph to accompany a one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="11.2.4" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_test"><i class="fa fa-check"></i><b>11.2.4</b> Conduct the one-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="11.2.5" data-path="onesamp_t_test.html"><a href="onesamp_t_test.html#onesamp_conclude"><i class="fa fa-check"></i><b>11.2.5</b> Concluding statement for the one-sample <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="t_confidence.html"><a href="t_confidence.html"><i class="fa fa-check"></i><b>11.3</b> Confidence intervals for <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="t_confidence.html"><a href="t_confidence.html#conf_precision"><i class="fa fa-check"></i><b>11.3.1</b> Confidence interval as a measure of precision for an estimate</a></li>
<li class="chapter" data-level="11.3.2" data-path="t_confidence.html"><a href="t_confidence.html#conf_hyp"><i class="fa fa-check"></i><b>11.3.2</b> Confidence interval approach to hypothesis testing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="compare_two_means.html"><a href="compare_two_means.html"><i class="fa fa-check"></i><b>12</b> Comparing means among two groups</a>
<ul>
<li class="chapter" data-level="12.1" data-path="twomean_packages_data.html"><a href="twomean_packages_data.html"><i class="fa fa-check"></i><b>12.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="12.2" data-path="paired-t-test.html"><a href="paired-t-test.html"><i class="fa fa-check"></i><b>12.2</b> Paired <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="paired-t-test.html"><a href="paired-t-test.html#calc_diffs"><i class="fa fa-check"></i><b>12.2.1</b> Calculate differences</a></li>
<li class="chapter" data-level="12.2.2" data-path="paired-t-test.html"><a href="paired-t-test.html#paired_Htest"><i class="fa fa-check"></i><b>12.2.2</b> Hypothesis statement</a></li>
<li class="chapter" data-level="12.2.3" data-path="paired-t-test.html"><a href="paired-t-test.html#graph_paried"><i class="fa fa-check"></i><b>12.2.3</b> A graph to accompany a paired <em>t</em>-test</a></li>
<li class="chapter" data-level="12.2.4" data-path="paired-t-test.html"><a href="paired-t-test.html#assump_paried"><i class="fa fa-check"></i><b>12.2.4</b> Assumptions of the paired <em>t</em>-test</a></li>
<li class="chapter" data-level="12.2.5" data-path="paired-t-test.html"><a href="paired-t-test.html#conduct_paired"><i class="fa fa-check"></i><b>12.2.5</b> Conduct the test</a></li>
<li class="chapter" data-level="12.2.6" data-path="paired-t-test.html"><a href="paired-t-test.html#concl_paired"><i class="fa fa-check"></i><b>12.2.6</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html"><i class="fa fa-check"></i><b>12.3</b> Two sample <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#twosamp_hyp"><i class="fa fa-check"></i><b>12.3.1</b> Hypothesis statement</a></li>
<li class="chapter" data-level="12.3.2" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#stats_2samp"><i class="fa fa-check"></i><b>12.3.2</b> A table of descriptive statistics</a></li>
<li class="chapter" data-level="12.3.3" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#graph_2samp"><i class="fa fa-check"></i><b>12.3.3</b> A graph to accompany a 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="12.3.4" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#twosamp_assump"><i class="fa fa-check"></i><b>12.3.4</b> Assumptions of the 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="12.3.5" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#conduct_2samptest"><i class="fa fa-check"></i><b>12.3.5</b> Conduct the 2-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="12.3.6" data-path="twosamp_ttest.html"><a href="twosamp_ttest.html#concl_2samp"><i class="fa fa-check"></i><b>12.3.6</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="assumpbad_2samp.html"><a href="assumpbad_2samp.html"><i class="fa fa-check"></i><b>12.4</b> When assumptions aren’t met</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="compare_three_more_means.html"><a href="compare_three_more_means.html"><i class="fa fa-check"></i><b>13</b> Comparing means among more than two groups</a>
<ul>
<li class="chapter" data-level="13.1" data-path="anova_packages_data.html"><a href="anova_packages_data.html"><i class="fa fa-check"></i><b>13.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="13.2" data-path="do_the_anova.html"><a href="do_the_anova.html"><i class="fa fa-check"></i><b>13.2</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_hyps"><i class="fa fa-check"></i><b>13.2.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="13.2.2" data-path="do_the_anova.html"><a href="do_the_anova.html#stats_anova"><i class="fa fa-check"></i><b>13.2.2</b> A table of descriptive statistics</a></li>
<li class="chapter" data-level="13.2.3" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_graph1"><i class="fa fa-check"></i><b>13.2.3</b> Visualize the data</a></li>
<li class="chapter" data-level="13.2.4" data-path="do_the_anova.html"><a href="do_the_anova.html#assump_anova"><i class="fa fa-check"></i><b>13.2.4</b> Assumptions of ANOVA</a></li>
<li class="chapter" data-level="13.2.5" data-path="do_the_anova.html"><a href="do_the_anova.html#do_anova1"><i class="fa fa-check"></i><b>13.2.5</b> Conduct the ANOVA test</a></li>
<li class="chapter" data-level="13.2.6" data-path="do_the_anova.html"><a href="do_the_anova.html#createanovatable"><i class="fa fa-check"></i><b>13.2.6</b> Generate nice ANOVA table</a></li>
<li class="chapter" data-level="13.2.7" data-path="do_the_anova.html"><a href="do_the_anova.html#calculate-r2-for-the-anova"><i class="fa fa-check"></i><b>13.2.7</b> Calculate <span class="math inline">\(R^2\)</span> for the ANOVA</a></li>
<li class="chapter" data-level="13.2.8" data-path="do_the_anova.html"><a href="do_the_anova.html#tukey"><i class="fa fa-check"></i><b>13.2.8</b> Tukey-Kramer post-hoc test</a></li>
<li class="chapter" data-level="13.2.9" data-path="do_the_anova.html"><a href="do_the_anova.html#vis_tukey"><i class="fa fa-check"></i><b>13.2.9</b> Visualizing post-hoc test results</a></li>
<li class="chapter" data-level="13.2.10" data-path="do_the_anova.html"><a href="do_the_anova.html#anova_conclusion"><i class="fa fa-check"></i><b>13.2.10</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="assumpbad_anova.html"><a href="assumpbad_anova.html"><i class="fa fa-check"></i><b>13.3</b> When assumptions aren’t met</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="two_num.html"><a href="two_num.html"><i class="fa fa-check"></i><b>14</b> Analyzing associations between two numerical variables</a>
<ul>
<li class="chapter" data-level="14.1" data-path="twonum_packages_data.html"><a href="twonum_packages_data.html"><i class="fa fa-check"></i><b>14.1</b> Load packages and import data</a></li>
<li class="chapter" data-level="14.2" data-path="pearson.html"><a href="pearson.html"><i class="fa fa-check"></i><b>14.2</b> Pearson correlation analysis</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="pearson.html"><a href="pearson.html#pearson_hyp"><i class="fa fa-check"></i><b>14.2.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="14.2.2" data-path="pearson.html"><a href="pearson.html#see_corr"><i class="fa fa-check"></i><b>14.2.2</b> Visualize the data</a></li>
<li class="chapter" data-level="14.2.3" data-path="pearson.html"><a href="pearson.html#corr_assumptions"><i class="fa fa-check"></i><b>14.2.3</b> Assumptions of correlation analysis</a></li>
<li class="chapter" data-level="14.2.4" data-path="pearson.html"><a href="pearson.html#do_corr"><i class="fa fa-check"></i><b>14.2.4</b> Conduct the correlation analysis</a></li>
<li class="chapter" data-level="14.2.5" data-path="pearson.html"><a href="pearson.html#concl_corr"><i class="fa fa-check"></i><b>14.2.5</b> Concluding statement</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="rankcorr.html"><a href="rankcorr.html"><i class="fa fa-check"></i><b>14.3</b> Rank correlation (Spearman’s correlation)</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="rankcorr.html"><a href="rankcorr.html#hypothesis-statements"><i class="fa fa-check"></i><b>14.3.1</b> Hypothesis statements</a></li>
<li class="chapter" data-level="14.3.2" data-path="rankcorr.html"><a href="rankcorr.html#spearman_hyp"><i class="fa fa-check"></i><b>14.3.2</b> Visualize the data</a></li>
<li class="chapter" data-level="14.3.3" data-path="rankcorr.html"><a href="rankcorr.html#assum_spear"><i class="fa fa-check"></i><b>14.3.3</b> Assumptions of Spearman rank correlation</a></li>
<li class="chapter" data-level="14.3.4" data-path="rankcorr.html"><a href="rankcorr.html#conduct_spearman"><i class="fa fa-check"></i><b>14.3.4</b> Conduct the test</a></li>
<li class="chapter" data-level="14.3.5" data-path="rankcorr.html"><a href="rankcorr.html#spear_conclude"><i class="fa fa-check"></i><b>14.3.5</b> Concluding statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="creating-tables-in-r-markdown.html"><a href="creating-tables-in-r-markdown.html"><i class="fa fa-check"></i>Creating tables in R Markdown</a>
<ul>
<li class="chapter" data-level="14.4" data-path="tables_packages.html"><a href="tables_packages.html"><i class="fa fa-check"></i><b>14.4</b> Load packages and import data</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="tables_packages.html"><a href="tables_packages.html#skim_tables"><i class="fa fa-check"></i><b>14.4.1</b> Formatting output from the <code>skimr</code> package</a></li>
<li class="chapter" data-level="14.4.2" data-path="tables_packages.html"><a href="tables_packages.html#stats_nicetable"><i class="fa fa-check"></i><b>14.4.2</b> A nicely formatted table of descriptive statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="checking-assumptions-and-data-transformations.html"><a href="checking-assumptions-and-data-transformations.html"><i class="fa fa-check"></i>Checking assumptions and data transformations</a>
<ul>
<li class="chapter" data-level="14.5" data-path="assumptions_packages_data.html"><a href="assumptions_packages_data.html"><i class="fa fa-check"></i><b>14.5</b> Load packages and import data</a></li>
<li class="chapter" data-level="14.6" data-path="checknorm_assum.html"><a href="checknorm_assum.html"><i class="fa fa-check"></i><b>14.6</b> Checking the normality assumption</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="checknorm_assum.html"><a href="checknorm_assum.html#quantile_plots"><i class="fa fa-check"></i><b>14.6.1</b> Normal quantile plots</a></li>
<li class="chapter" data-level="14.6.2" data-path="checknorm_assum.html"><a href="checknorm_assum.html#shapirottest"><i class="fa fa-check"></i><b>14.6.2</b> Shapiro-Wilk test for normality</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="levenetest.html"><a href="levenetest.html"><i class="fa fa-check"></i><b>14.7</b> Checking the equal-variance assumption</a></li>
<li class="chapter" data-level="14.8" data-path="transform.html"><a href="transform.html"><i class="fa fa-check"></i><b>14.8</b> Data transformations</a>
<ul>
<li class="chapter" data-level="14.8.1" data-path="transform.html"><a href="transform.html#log_transform"><i class="fa fa-check"></i><b>14.8.1</b> Log-transform</a></li>
<li class="chapter" data-level="14.8.2" data-path="transform.html"><a href="transform.html#zeroes"><i class="fa fa-check"></i><b>14.8.2</b> Dealing with zeroes</a></li>
<li class="chapter" data-level="14.8.3" data-path="transform.html"><a href="transform.html#logbases"><i class="fa fa-check"></i><b>14.8.3</b> Log bases</a></li>
<li class="chapter" data-level="14.8.4" data-path="transform.html"><a href="transform.html#back_transform"><i class="fa fa-check"></i><b>14.8.4</b> Back-transforming log data</a></li>
<li class="chapter" data-level="14.8.5" data-path="transform.html"><a href="transform.html#logit_transform"><i class="fa fa-check"></i><b>14.8.5</b> Logit transform</a></li>
<li class="chapter" data-level="14.8.6" data-path="transform.html"><a href="transform.html#logit_back"><i class="fa fa-check"></i><b>14.8.6</b> Back-transforming logit data</a></li>
<li class="chapter" data-level="14.8.7" data-path="transform.html"><a href="transform.html#when_back"><i class="fa fa-check"></i><b>14.8.7</b> When to back-transform?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="visual-markdown-editor.html"><a href="visual-markdown-editor.html"><i class="fa fa-check"></i>Visual Markdown Editor</a>
<ul>
<li class="chapter" data-level="" data-path="a-more-familiar-editing-environment.html"><a href="a-more-familiar-editing-environment.html"><i class="fa fa-check"></i>A more familiar editing environment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="common-errors-and-their-solutions.html"><a href="common-errors-and-their-solutions.html"><i class="fa fa-check"></i>Common errors and their solutions</a>
<ul>
<li class="chapter" data-level="" data-path="google-can-help.html"><a href="google-can-help.html"><i class="fa fa-check"></i>Google can help</a></li>
<li class="chapter" data-level="" data-path="rtools-required-during-install.html"><a href="rtools-required-during-install.html"><i class="fa fa-check"></i>Rtools required during install</a></li>
<li class="chapter" data-level="" data-path="could-not-find-function.html"><a href="could-not-find-function.html"><i class="fa fa-check"></i>Could not find function</a></li>
<li class="chapter" data-level="" data-path="there-is-no-package.html"><a href="there-is-no-package.html"><i class="fa fa-check"></i>There is no package</a></li>
<li class="chapter" data-level="" data-path="trying-to-use-cran-without-setting-a-mirror.html"><a href="trying-to-use-cran-without-setting-a-mirror.html"><i class="fa fa-check"></i>Trying to use CRAN without setting a mirror</a></li>
<li class="chapter" data-level="" data-path="pdf-latex-is-not-found.html"><a href="pdf-latex-is-not-found.html"><i class="fa fa-check"></i>PDF Latex is not found</a></li>
<li class="chapter" data-level="" data-path="error-in-parse.html"><a href="error-in-parse.html"><i class="fa fa-check"></i>Error in parse</a></li>
<li class="chapter" data-level="" data-path="no-such-file-or-directory-exists.html"><a href="no-such-file-or-directory-exists.html"><i class="fa fa-check"></i>No such file or directory exists</a></li>
<li class="chapter" data-level="" data-path="messy-output-when-loading-packages.html"><a href="messy-output-when-loading-packages.html"><i class="fa fa-check"></i>Messy output when loading packages</a></li>
<li class="chapter" data-level="" data-path="unused-argument.html"><a href="unused-argument.html"><i class="fa fa-check"></i>Unused argument</a></li>
<li class="chapter" data-level="" data-path="object-not-found.html"><a href="object-not-found.html"><i class="fa fa-check"></i>Object not found</a></li>
<li class="chapter" data-level="" data-path="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html"><i class="fa fa-check"></i>Figure caption doesn’t show up below figure in knitted document</a></li>
<li class="chapter" data-level="" data-path="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html"><i class="fa fa-check"></i>Filename, directory name, or volume label syntax is incorrect</a></li>
<li class="chapter" data-level="" data-path="installing-packages-there-is-a-binary-version-available.html"><a href="installing-packages-there-is-a-binary-version-available.html"><i class="fa fa-check"></i>Installing packages: there is a binary version available</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="paired-t-test" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Paired <em>t</em>-test<a href="paired-t-test.html#paired-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll use the <code>blackbird</code> dataset for this example.</p>
<p>For 13 red-winged blackbirds, measurements of antibodies were taken before and after implantation with testosterone. Thus, the same bird was measured twice. Clearly, these measurements are not independent, hence the need for a <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Paired-t-test">“paired” <em>t</em>-test</a>.</p>
<p>Let’s first have a look at the <code>blackbird</code> dataset:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="paired-t-test.html#cb292-1" aria-hidden="true" tabindex="-1"></a>blackbird </span></code></pre></div>
<pre><code>## # A tibble: 26 × 3
##    blackbird time   Antibody
##        &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
##  1         1 Before    4.654
##  2         2 Before    3.912
##  3         3 Before    4.913
##  4         4 Before    4.500
##  5         5 Before    4.804
##  6         6 Before    4.883
##  7         7 Before    4.875
##  8         8 Before    4.779
##  9         9 Before    4.977
## 10        10 Before    4.868
## # … with 16 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>The data frame has 26 rows, and includes 3 variables, the first of which “blackbird” simply keeps track of the individual ID of blackbirds.</p>
<p>The response variable of interest, “Antibody” represents antibody production rate measured in units of natural logarithm (ln) 10^{-3} optical density per minute (ln[mOD/min]).</p>
<p>The factor variable <code>time</code> that has two levels: “After” and “Before”.</p>
<p>These data are stored in <strong>tidy format</strong>, which, as you’ve <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/tidy-data.html">learned</a>, is the ideal format for storing data.</p>
<p>Sometimes you may get data in <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Wide-format-data"><strong>wide format</strong></a>, in which case, for instance, we would have a column for the “Before” antibody measurements and another column for the “After” measurements.</p>
<p><strong>It is always preferable</strong> to work with <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Long-format-data">long-format</a> (tidy) data.</p>
<p>Consult the following <a href="http://www.cookbook-r.com/Manipulating_data/Converting_data_between_wide_and_long_format/">webpage</a> for instructions on using the <code>tidyr</code> package for converting between wide and long data formats.</p>
<p>With our data in the preferred long format, we can proceed with our hypothesis test, but because the hypothesis focuses on the <em>differences</em> in the paired measurements, we need to calculate those first!</p>
<div id="calc_diffs" class="section level3 hasAnchor" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Calculate differences<a href="paired-t-test.html#calc_diffs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s remind ourselves how the data are stored:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="paired-t-test.html#cb294-1" aria-hidden="true" tabindex="-1"></a>blackbird</span></code></pre></div>
<pre><code>## # A tibble: 26 × 3
##    blackbird time   Antibody
##        &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
##  1         1 Before    4.654
##  2         2 Before    3.912
##  3         3 Before    4.913
##  4         4 Before    4.500
##  5         5 Before    4.804
##  6         6 Before    4.883
##  7         7 Before    4.875
##  8         8 Before    4.779
##  9         9 Before    4.977
## 10        10 Before    4.868
## # … with 16 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>We’ll use, for the first time, the <code>pivot_wider</code> function from the <code>dplyr</code> package (which is loaded as part of the <code>tidyverse</code>).</p>
<p>The <code>pivot_wider</code> function essentially takes data stored in long format and converts it to wide format.</p>
<div class="note">
<p><strong>UPDATED November 15, 2021: </strong>
The following code requires that there be at least one variable in the tibble that provides a unique identifier for each individual. In the “blackbird” tibble, this variable is “blackbird”. I have added an argument “id_cols = blackbird” to the code below to underscore the need for this type of identifier variable. The code will not work if such a variable does not exist in the tibble.</p>
</div>
<p>Here’s the code, then we’ll explain after:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="paired-t-test.html#cb296-1" aria-hidden="true" tabindex="-1"></a>blackbird.diffs <span class="ot">&lt;-</span> blackbird <span class="sc">%&gt;%</span></span>
<span id="cb296-2"><a href="paired-t-test.html#cb296-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> blackbird, <span class="at">names_from =</span> time, <span class="at">values_from =</span> Antibody) <span class="sc">%&gt;%</span></span>
<span id="cb296-3"><a href="paired-t-test.html#cb296-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diffs =</span> After <span class="sc">-</span> Before)</span></code></pre></div>
<p>In the preceding chunk, we:</p>
<ul>
<li>create a new object “blackbird.diffs” to hold our data</li>
<li>the <code>pivot_wider</code> function takes the following arguments:
<ul>
<li>“id_cols = blackbird”, which tells the function which variable in the tibble is used to keep track of the unique individuals (here, the “blackbird” variable)</li>
<li>A categorical (grouping) variable “names_from” and creates new columns, one for each unique category</li>
<li>A “values_from” variable; thus, in our case, we get 2 new columns (because there are 2 categories to the “time” variable: Before and After), and the values placed in those columns are the corresponding values of “Antibody”.</li>
</ul></li>
<li>we then create a new variable “diff” that equals the values in the newly created “After” variable minus the values in the “Before” variable.</li>
</ul>
<div class="note">
<p><strong>TIP:</strong>
In the blackbird example we have “Before” and “After” measurements of a variable, and we calculated the <em>difference</em> as “<span class="math inline">\(After - Before\)</span>”, as this is a logical way to do it. It doesn’t really matter which direction you calculate the difference, but just be aware that you need to make clear how it was calculated, so that your interpretation is correct.</p>
</div>
<p>Let’s have a look at the result:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="paired-t-test.html#cb297-1" aria-hidden="true" tabindex="-1"></a>blackbird.diffs</span></code></pre></div>
<pre><code>## # A tibble: 13 × 4
##    blackbird Before After    diffs
##        &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1         1  4.654 4.443 -0.2113 
##  2         2  3.912 4.304  0.3920 
##  3         3  4.913 4.977  0.06408
##  4         4  4.500 4.454 -0.04546
##  5         5  4.804 4.997  0.1932 
##  6         6  4.883 4.997  0.1144 
##  7         7  4.875 5.011  0.1354 
##  8         8  4.779 4.956  0.1767 
##  9         9  4.977 5.017  0.04055
## 10        10  4.868 4.727 -0.1401 
## 11        11  4.754 4.771  0.01709
## 12        12  4.700 4.595 -0.1054 
## 13        13  4.927 5.011  0.08338</code></pre>
<p>We can see that some of the <code>diffs</code> values are negative, and some are positive. These would of course be switched in sign if we had calculated the differences as “<span class="math inline">\(Before - After\)</span>”.</p>
<p>In any case, this is the new tibble and variable “diffs” that we’ll use for our hypothesis test!</p>
</div>
<div id="paired_Htest" class="section level3 hasAnchor" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> Hypothesis statement<a href="paired-t-test.html#paired_Htest" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The hypotheses for this paired <em>t</em>-test focus on the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Mean">mean</a> of the <em>differences</em> between the paired measurements, denoted by <span class="math inline">\(\mu_d\)</span>:</p>
<p>H<sub>0</sub>: The mean change in antibody production after testosterone implants was zero (<span class="math inline">\(\mu_d = 0\)</span>).<br />
H<sub>A</sub>: The mean change in antibody production after testosterone implants was not zero (<span class="math inline">\(\mu_d \neq 0\)</span>).</p>
<p>Steps to a hypothesis test:</p>
<ul>
<li>We’ll use an <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Significance-level-($\alpha$)"><span class="math inline">\(\alpha\)</span> level</a> of 0.05.<br />
</li>
<li>It is a two-tailed <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Alternative-hypothesis">alternative hypothesis</a></li>
<li>We’ll visualize the data, and interpret the output</li>
<li>We’ll use a paired <em>t</em>-test test to test the null hypothesis, because we’re dealing with “before and after” measurements taken on the same individuals, and drawing inferences about a population mean <span class="math inline">\(\mu_d\)</span> using sample data<br />
</li>
<li>We’ll check the assumptions of the test (see below)</li>
<li>We’ll calculate our test statistic</li>
<li>We’ll calculate the <em>P</em>-value associated with our test statistic</li>
<li>We’ll calculate a 95% <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Confidence-interval">confidence interval</a> for the mean difference</li>
<li>We’ll provide a good concluding statement that includes a 95% confidence interval for the mean difference</li>
</ul>
</div>
<div id="graph_paried" class="section level3 hasAnchor" number="12.2.3">
<h3><span class="header-section-number">12.2.3</span> A graph to accompany a paired <em>t</em>-test<a href="paired-t-test.html#graph_paried" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The best way to visualize the data for a paired <em>t</em>-test is to create a <strong>histogram</strong> of the calculated <em>differences</em> between the paired observations.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="paired-t-test.html#cb299-1" aria-hidden="true" tabindex="-1"></a>blackbird.diffs <span class="sc">%&gt;%</span> </span>
<span id="cb299-2"><a href="paired-t-test.html#cb299-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> diffs)) <span class="sc">+</span></span>
<span id="cb299-3"><a href="paired-t-test.html#cb299-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">boundary =</span> <span class="sc">-</span><span class="fl">0.3</span>, </span>
<span id="cb299-4"><a href="paired-t-test.html#cb299-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightgrey&quot;</span>,) <span class="sc">+</span></span>
<span id="cb299-5"><a href="paired-t-test.html#cb299-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Difference in antibody production rate (after - before) (ln[mOD/min]) 10^-3&quot;</span>) <span class="sc">+</span></span>
<span id="cb299-6"><a href="paired-t-test.html#cb299-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb299-7"><a href="paired-t-test.html#cb299-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-81"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-81-1.png" alt="Histogram of the differences in antibody production rate before and after the testosterone treatment" width="384" />
<p class="caption">
Figure 12.1: Histogram of the differences in antibody production rate before and after the testosterone treatment
</p>
</div>
<p>With such a small sample size (13), the histogram is not particularly informative. But we do see most observations are just above zero.</p>
<p><strong>OPTIONAL</strong></p>
<p>Another optional but nice way to visualize paired data is using a paired plot.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="paired-t-test.html#cb300-1" aria-hidden="true" tabindex="-1"></a>blackbird <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="paired-t-test.html#cb300-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> Antibody)) <span class="sc">+</span></span>
<span id="cb300-3"><a href="paired-t-test.html#cb300-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb300-4"><a href="paired-t-test.html#cb300-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> blackbird), <span class="at">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb300-5"><a href="paired-t-test.html#cb300-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-82"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-82-1.png" alt="Paired plot of antibody production rate before and after the testosterone treatment" width="384" />
<p class="caption">
Figure 12.2: Paired plot of antibody production rate before and after the testosterone treatment
</p>
</div>
<p><strong>OPTIONAL</strong></p>
<p>Notice that the “After” group is plotted on the left, which is a bit counter-intuitive. We could optionally change that by changing how R recognizes the “order” of the “time” variable:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="paired-t-test.html#cb301-1" aria-hidden="true" tabindex="-1"></a>blackbird<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">ordered</span>(blackbird<span class="sc">$</span>time, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Before&quot;</span>, <span class="st">&quot;After&quot;</span>))</span></code></pre></div>
<p>Then repeat the code above to create the paired plot.</p>
</div>
<div id="assump_paried" class="section level3 hasAnchor" number="12.2.4">
<h3><span class="header-section-number">12.2.4</span> Assumptions of the paired <em>t</em>-test<a href="paired-t-test.html#assump_paried" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Assumptions">assumptions</a> of the paired <em>t</em>-test are the same as the assumptions for the one-sample <em>t</em>-test, except they pertain to the <em>differences</em>:</p>
<ul>
<li>the sampling units are randomly sampled from the population</li>
<li>the <em>differences</em> have a normal distribution in the population (each group of measurements need not be normally distributed)</li>
</ul>
<p>As instructed in the <a href="checknorm_assum.html#checknorm_assum">checking assumptions</a> tutorial, we should use a normal quantile plot to visually check the normal distribution assumption.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="paired-t-test.html#cb302-1" aria-hidden="true" tabindex="-1"></a>blackbird.diffs <span class="sc">%&gt;%</span></span>
<span id="cb302-2"><a href="paired-t-test.html#cb302-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> diffs)) <span class="sc">+</span></span>
<span id="cb302-3"><a href="paired-t-test.html#cb302-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb302-4"><a href="paired-t-test.html#cb302-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb302-5"><a href="paired-t-test.html#cb302-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Normal quantile&quot;</span>) <span class="sc">+</span></span>
<span id="cb302-6"><a href="paired-t-test.html#cb302-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Antibody production (ln[mOD/min]) 10^-3&quot;</span>) <span class="sc">+</span></span>
<span id="cb302-7"><a href="paired-t-test.html#cb302-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-84"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-84-1.png" alt="Normal quantile plot of the differences in antibody production rate before and after the testosterone treatment (ln[mOD/min]) 10^-3." width="384" />
<p class="caption">
Figure 12.3: Normal quantile plot of the differences in antibody production rate before and after the testosterone treatment (ln[mOD/min]) 10^-3.
</p>
</div>
<p>We see that most of the lines are close to the line, with one point near the top right that is a bit off…</p>
<p>A reasonable statement would be:</p>
<blockquote>
<p>“The normal quantile plot shows that the data generally fall close to the line (except perhaps the highest value), indicating that the normality assumption is reasonably met.”</p>
</blockquote>
<p>But if you’re feeling uncertain, we can follow this with a <strong>Shapiro-Wilk Normality Test</strong>, which tests the null hypothesis that the data are sampled from a normal distribution.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="paired-t-test.html#cb303-1" aria-hidden="true" tabindex="-1"></a>shapiro.result <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(blackbird.diffs<span class="sc">$</span>diffs)</span>
<span id="cb303-2"><a href="paired-t-test.html#cb303-2" aria-hidden="true" tabindex="-1"></a>shapiro.result.tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(shapiro.result)</span>
<span id="cb303-3"><a href="paired-t-test.html#cb303-3" aria-hidden="true" tabindex="-1"></a>shapiro.result.tidy</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   statistic p.value method                     
##       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                      
## 1    0.9781  0.9688 Shapiro-Wilk normality test</code></pre>
<p>Given that the <em>P</em>-value is large (and much greater than 0.05), there is no reason to reject the null hypothesis. Thus, our normality assumption is met.</p>
<p>When testing the normality assumption using the Shapiro-Wilk test, there is no need to conduct all the steps associated with a hypothesis test. Simply report the results of the test (the test statistic value and the associated <em>P</em>-value).</p>
<p>For instance:</p>
<blockquote>
<p>“A Shapiro-Wilk test revealed no evidence against the assumption that the data are drawn from a normal distribution (<em>W</em> = 0.98, <em>P</em>-value = 0.969).”</p>
</blockquote>
</div>
<div id="conduct_paired" class="section level3 hasAnchor" number="12.2.5">
<h3><span class="header-section-number">12.2.5</span> Conduct the test<a href="paired-t-test.html#conduct_paired" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can conduct a <strong>paired t-test</strong> in two different ways:</p>
<ul>
<li><p>conduct a one-sample <em>t</em>-test on the <em>differences</em> using the <code>t.test</code> function and methods you learned in a <a href="onesamp_t_test.html#onesamp_t_test">previous tutorial</a>.</p></li>
<li><p>conduct a paired <em>t</em>-test using the <code>t.test</code> function and the argument <code>paired = TRUE</code>.</p></li>
</ul>
<p><strong>(1) One-sample <em>t</em>-test on the differences</strong></p>
<p>Let’s proceed with the test as we’ve <a href="onesamp_t_test.html#onesamp_t_test">previously learned</a>.</p>
<p>Here we make sure to set the null hypothesized value of “mu” to zero in the argument for the <code>t.test</code> function:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="paired-t-test.html#cb305-1" aria-hidden="true" tabindex="-1"></a>blackbird.ttest <span class="ot">&lt;-</span> blackbird.diffs <span class="sc">%&gt;%</span></span>
<span id="cb305-2"><a href="paired-t-test.html#cb305-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(diffs) <span class="sc">%&gt;%</span></span>
<span id="cb305-3"><a href="paired-t-test.html#cb305-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(<span class="at">mu =</span> <span class="dv">0</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<p>Now have a look at the result:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="paired-t-test.html#cb306-1" aria-hidden="true" tabindex="-1"></a>blackbird.ttest</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  .
## t = 1.2435, df = 12, p-value = 0.2374
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.04134676  0.15128638
## sample estimates:
##  mean of x 
## 0.05496981</code></pre>
<p>The observed <em>P</em>-value for our test is larger than our <span class="math inline">\(\alpha\)</span> level of 0.05. We therefore fail to reject the null hypothesis.</p>
<div class="note">
<p><strong>NOTE (Added Nov. 16, 2021):</strong>
The values of <em>t</em> and of the lower and upper confidence limits may be reversed in sign, if you conducted your calculation of differences in the alternative way. Specifically, you may get <em>t</em> = -1.2434925, and confidence limits of -0.1512864 and 0.0413468. This is totally fine!</p>
</div>
<p><strong>(2) Paired <em>t</em>-test</strong></p>
<p>Here we use a method that relies on the data being stored in tidy (long) format, and assuming the order of the observations for each pair is correct. For instance, this is the case for our “blackbird” tibble. Specifically, birds 1 through 13 are ordered the same within each of the “After” and “Before” groups. This is crucial for this implementation of the paired <em>t</em>-test.</p>
<p>Here’s the code for running a paired <em>t</em>-test on tidy (long) format data:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="paired-t-test.html#cb308-1" aria-hidden="true" tabindex="-1"></a>blackbird.paired.ttest <span class="ot">&lt;-</span> blackbird <span class="sc">%&gt;%</span> </span>
<span id="cb308-2"><a href="paired-t-test.html#cb308-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(Antibody <span class="sc">~</span> time, <span class="at">data =</span> ., <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<p>Here’s an explanation:</p>
<ul>
<li>we create a new object “blackbird.paried.ttest” to store our results in</li>
<li>we run the <code>t.test</code> function with the arguments as follows:
<ul>
<li>we use a formula syntax to specify Y ~ X, like we did when learning the <a href="levenetest.html#levenetest">Levene’s Test of equal variance</a>; In this case, we have our numerical response variable (Y) “Antibody”, then the “~” symbol, then the explanatory categorical variable (X) “time”.</li>
<li><strong>NEW</strong>: we have an argument “data = .”, which tells the <code>t.test</code> function that whatever data was passed to it from the preceding line is what will be used</li>
<li>we have the “paired = TRUE” argument, telling the function that this is a paired design</li>
<li>finally we use “conf.level = 0.95” which corresponds to an <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul></li>
</ul>
<p>Let’s look at the result:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="paired-t-test.html#cb309-1" aria-hidden="true" tabindex="-1"></a>blackbird.paired.ttest</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Antibody by time
## t = 1.2435, df = 12, p-value = 0.2374
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -0.04134676  0.15128638
## sample estimates:
## mean difference 
##      0.05496981</code></pre>
<p>The output is identical to what we got when we applied a 1-sample <em>t</em>-test on the differences!</p>
<div class="note">
<p><strong>NOTE (Added Nov. 16, 2021):</strong>
The values of <em>t</em> and of the lower and upper confidence limits may be reversed in sign, if you conducted your calculation of differences in the alternative way. Specifically, you may get <em>t</em> = -1.2434925, and confidence limits of -0.1512864 and 0.0413468. This is totally fine!</p>
</div>
</div>
<div id="concl_paired" class="section level3 hasAnchor" number="12.2.6">
<h3><span class="header-section-number">12.2.6</span> Concluding statement<a href="paired-t-test.html#concl_paired" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here’s an example of a reasonable concluding statement, and this can apply for either of the two methods used above (note that in either case we call the test a “paired <em>t</em>-test, even if we used the one-sample <em>t</em>-test on the differences):</p>
<blockquote>
<p>We have no reason to reject the null hypothesis that the mean change in antibody production after testosterone implants was zero (paired <em>t</em>-test; <em>t</em> = 1.24; df = 12; <em>P</em> = 0.237; 95% confidence interval for the difference: -0.041 <span class="math inline">\(&lt; \mu_d &lt;\)</span> 0.151).</p>
</blockquote>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="twomean_packages_data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="twosamp_ttest.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202.pdf", "BIOL202.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
