<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>16.3 Two sample t-test | Tutorials for BIOL202: Introduction to Biostatistics</title>
  <meta name="description" content="All tutorials associated with BIOL202" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="16.3 Two sample t-test | Tutorials for BIOL202: Introduction to Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="All tutorials associated with BIOL202" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="16.3 Two sample t-test | Tutorials for BIOL202: Introduction to Biostatistics" />
  
  <meta name="twitter:description" content="All tutorials associated with BIOL202" />
  

<meta name="author" content="Jason Pither" />


<meta name="date" content="2022-09-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="paired-t-test.html"/>
<link rel="next" href="assumpbad-2samp.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DVMYRT2ND2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DVMYRT2ND2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOL202 Tutorials</a></li>

<li class="divider"></li>
<li><a href="#part-preface" id="toc-part-preface">(PART*) Preface</a></li>
<li><a href="index.html#welcome" id="toc-welcome">Welcome</a>
<ul>
<li><a href="author.html#author" id="toc-author">Author</a></li>
<li><a href="acknowledgments.html#acknowledgments" id="toc-acknowledgments">Acknowledgments</a></li>
<li><a href="copyright.html#copyright" id="toc-copyright">Copyright</a></li>
<li><a href="ubco-biology-open-materials.html#ubco-biology-open-materials" id="toc-ubco-biology-open-materials">UBCO Biology open materials</a></li>
</ul></li>
<li><a href="#part-getting-started-with-r-rstudio-r-markdown" id="toc-part-getting-started-with-r-rstudio-r-markdown">(PART*) Getting started with R, RStudio &amp; R Markdown</a></li>
<li><a href="what-is-R.html#what_is_R" id="toc-what_is_R"><span class="toc-section-number">1</span> What are R and RStudio?</a></li>
<li><a href="install-R-Rstudio.html#install_R_Rstudio" id="toc-install_R_Rstudio"><span class="toc-section-number">2</span> Installing R and RStudio</a></li>
<li><a href="start-r.html#start_r" id="toc-start_r"><span class="toc-section-number">3</span> Start using R &amp; RStudio</a>
<ul>
<li><a href="Rstudio-interface.html#Rstudio_interface" id="toc-Rstudio_interface"><span class="toc-section-number">3.1</span> The RStudio Interface</a></li>
<li><a href="coding-basics.html#coding_basics" id="toc-coding_basics"><span class="toc-section-number">3.2</span> Coding basics</a></li>
</ul></li>
<li><a href="packages.html#packages" id="toc-packages"><span class="toc-section-number">4</span> R packages</a>
<ul>
<li><a href="package-install.html#package_install" id="toc-package_install"><span class="toc-section-number">4.1</span> Package installation</a></li>
<li><a href="package-load.html#package_load" id="toc-package_load"><span class="toc-section-number">4.2</span> Package loading</a></li>
</ul></li>
<li><a href="intro-markdown.html#intro_markdown" id="toc-intro_markdown"><span class="toc-section-number">5</span> Intro to R Markdown</a>
<ul>
<li><a href="lit-programming.html#lit_programming" id="toc-lit_programming"><span class="toc-section-number">5.1</span> Literate programming with R Markdown</a></li>
<li><a href="veryify-knit.html#veryify_knit" id="toc-veryify_knit"><span class="toc-section-number">5.2</span> Making sure R Markdown knits to PDF</a></li>
</ul></li>
<li><a href="r-resources.html#r_resources" id="toc-r_resources"><span class="toc-section-number">6</span> Extra resources</a>
<ul>
<li><a href="online-resources.html#online_resources" id="toc-online_resources"><span class="toc-section-number">6.1</span> R Resources Online</a></li>
<li><a href="rmd-graphing.html#rmd_graphing" id="toc-rmd_graphing"><span class="toc-section-number">6.2</span> Setting up R Markdown for graphing</a></li>
<li><a href="example-answer.html#example_answer" id="toc-example_answer"><span class="toc-section-number">6.3</span> Example question / answer</a></li>
<li><a href="knit-assign.html#knit_assign" id="toc-knit_assign"><span class="toc-section-number">6.4</span> Knitting your assignment to PDF</a></li>
<li><a href="submit-rmd.html#submit_rmd" id="toc-submit_rmd"><span class="toc-section-number">6.5</span> Submit your assignment</a></li>
</ul></li>
<li><a href="data-import.html#data_import" id="toc-data_import"><span class="toc-section-number">7</span> Preparing and importing Tidy Data</a>
<ul>
<li><a href="tidy-data.html#tidy_data" id="toc-tidy_data"><span class="toc-section-number">7.1</span> Tidy data</a></li>
<li><a href="import-csv-url.html#import_csv_url" id="toc-import_csv_url"><span class="toc-section-number">7.2</span> Import a CSV file from a website</a></li>
<li><a href="create-csv-local.html#create_csv_local" id="toc-create_csv_local"><span class="toc-section-number">7.3</span> Create a CSV file</a></li>
<li><a href="import-csv-local.html#import_csv_local" id="toc-import_csv_local"><span class="toc-section-number">7.4</span> Import a local CSV file</a></li>
<li><a href="data-overview.html#data_overview" id="toc-data_overview"><span class="toc-section-number">7.5</span> Get an overview of a dataset</a></li>
<li><a href="tutorial-practice-activities.html#tutorial-practice-activities" id="toc-tutorial-practice-activities"><span class="toc-section-number">7.6</span> Tutorial practice activities</a></li>
</ul></li>
<li><a href="#part-visualizing-and-describing-data" id="toc-part-visualizing-and-describing-data">(PART*) Visualizing and Describing Data</a></li>
<li><a href="vis-variable.html#vis_variable" id="toc-vis_variable"><span class="toc-section-number">8</span> Visualizing a single variable</a>
<ul>
<li><a href="vis-packages-data.html#vis_packages_data" id="toc-vis_packages_data"><span class="toc-section-number">8.1</span> Load packages and import data</a></li>
<li><a href="vis-data-overview.html#vis_data_overview" id="toc-vis_data_overview"><span class="toc-section-number">8.2</span> Get an overview of the data</a></li>
<li><a href="vis-cat-freq-table.html#vis_cat_freq_table" id="toc-vis_cat_freq_table"><span class="toc-section-number">8.3</span> Create a frequency table</a></li>
<li><a href="vis-cat-barchart.html#vis_cat_barchart" id="toc-vis_cat_barchart"><span class="toc-section-number">8.4</span> Create a bar graph</a></li>
<li><a href="vis-histogram.html#vis_histogram" id="toc-vis_histogram"><span class="toc-section-number">8.5</span> Create a histogram</a></li>
<li><a href="vis-describe-hist.html#vis_describe_hist" id="toc-vis_describe_hist"><span class="toc-section-number">8.6</span> Describing a histogram</a></li>
</ul></li>
<li><a href="vis-describe.html#vis_describe" id="toc-vis_describe"><span class="toc-section-number">9</span> Describing a single variable</a>
<ul>
<li><a href="desc-packages-data.html#desc_packages_data" id="toc-desc_packages_data"><span class="toc-section-number">9.1</span> Load packages and import data</a></li>
<li><a href="desc-cat-Var.html#desc_cat_Var" id="toc-desc_cat_Var"><span class="toc-section-number">9.2</span> Describing a categorical variable</a></li>
<li><a href="desc-numeric-var.html#desc_numeric_var" id="toc-desc_numeric_var"><span class="toc-section-number">9.3</span> Describing a numerical variable</a>
<ul>
<li><a href="desc-numeric-var.html#median_IQR" id="toc-median_IQR"><span class="toc-section-number">9.3.1</span> Calculating the median &amp; IQR</a></li>
<li><a href="desc-numeric-var.html#mean_sd" id="toc-mean_sd"><span class="toc-section-number">9.3.2</span> Calculating the mean &amp; standard deviation</a></li>
</ul></li>
<li><a href="desc-numeric-var-cat.html#desc_numeric_var_cat" id="toc-desc_numeric_var_cat"><span class="toc-section-number">9.4</span> Describing a numerical variable grouped by a categorical variable</a></li>
</ul></li>
<li><a href="vis-twovar.html#vis_twovar" id="toc-vis_twovar"><span class="toc-section-number">10</span> Visualizing associations between two variables</a>
<ul>
<li><a href="vis2-packages-data.html#vis2_packages_data" id="toc-vis2_packages_data"><span class="toc-section-number">10.1</span> Load packages and import data</a></li>
<li><a href="vis2-2cat.html#vis2_2cat" id="toc-vis2_2cat"><span class="toc-section-number">10.2</span> Visualizing association between two categorical variables</a>
<ul>
<li><a href="vis2-2cat.html#vis2_cont_table" id="toc-vis2_cont_table"><span class="toc-section-number">10.2.1</span> Constructing a contingency table</a></li>
<li><a href="vis2-2cat.html#grouped_bar_graphs" id="toc-grouped_bar_graphs"><span class="toc-section-number">10.2.2</span> Constructing a grouped bar graph</a></li>
<li><a href="vis2-2cat.html#mosaic_plot" id="toc-mosaic_plot"><span class="toc-section-number">10.2.3</span> Constructing a mosaic plot</a></li>
<li><a href="vis2-2cat.html#interpret_mosaic" id="toc-interpret_mosaic"><span class="toc-section-number">10.2.4</span> Interpreting mosaic plots</a></li>
</ul></li>
<li><a href="two-numeric.html#two_numeric" id="toc-two_numeric"><span class="toc-section-number">10.3</span> Visualizing association between two numeric variables</a>
<ul>
<li><a href="two-numeric.html#interpret_scatter" id="toc-interpret_scatter"><span class="toc-section-number">10.3.1</span> Interpreting and describing a scatterplot</a></li>
</ul></li>
<li><a href="numeric-vs-cat.html#numeric_vs_cat" id="toc-numeric_vs_cat"><span class="toc-section-number">10.4</span> Visualizing association between a numeric and a categorical variable</a>
<ul>
<li><a href="numeric-vs-cat.html#stripchart" id="toc-stripchart"><span class="toc-section-number">10.4.1</span> Create a stripchart</a></li>
<li><a href="numeric-vs-cat.html#violinplot" id="toc-violinplot"><span class="toc-section-number">10.4.2</span> Create a violin plot</a></li>
<li><a href="numeric-vs-cat.html#boxplots" id="toc-boxplots"><span class="toc-section-number">10.4.3</span> Creating a boxplot</a></li>
<li><a href="numeric-vs-cat.html#bestplot" id="toc-bestplot"><span class="toc-section-number">10.4.4</span> Combining violin and boxplots</a></li>
<li><a href="numeric-vs-cat.html#interp_violin" id="toc-interp_violin"><span class="toc-section-number">10.4.5</span> Interpreting stripcharts and boxplots</a></li>
</ul></li>
</ul></li>
<li><a href="#part-inferential-statistics" id="toc-part-inferential-statistics">(PART*) Inferential Statistics</a></li>
<li><a href="estimation.html#estimation" id="toc-estimation"><span class="toc-section-number">11</span> Sampling, Estimation, &amp; Uncertainty</a>
<ul>
<li><a href="estimation-packages-data.html#estimation_packages_data" id="toc-estimation_packages_data"><span class="toc-section-number">11.1</span> Load packages and import data</a></li>
<li><a href="sampling-functions.html#sampling_functions" id="toc-sampling_functions"><span class="toc-section-number">11.2</span> Functions for sampling</a>
<ul>
<li><a href="sampling-functions.html#setseed" id="toc-setseed"><span class="toc-section-number">11.2.1</span> Setting the “seed” for random sampling</a></li>
</ul></li>
<li><a href="sampling-error.html#sampling_error" id="toc-sampling_error"><span class="toc-section-number">11.3</span> Sampling error</a></li>
<li><a href="sampdistmean.html#sampdistmean" id="toc-sampdistmean"><span class="toc-section-number">11.4</span> Sampling distribution of the mean</a>
<ul>
<li><a href="sampdistmean.html#hist_samdist" id="toc-hist_samdist"><span class="toc-section-number">11.4.1</span> Visualize the sampling distribution</a></li>
</ul></li>
<li><a href="sem-page.html#sem_page" id="toc-sem_page"><span class="toc-section-number">11.5</span> Standard error of the mean</a></li>
<li><a href="confint-rough.html#confint_rough" id="toc-confint_rough"><span class="toc-section-number">11.6</span> Rule of thumb 95% confidence interval</a></li>
</ul></li>
<li><a href="hypothesis.html#hypothesis" id="toc-hypothesis"><span class="toc-section-number">12</span> Hypothesis testing</a>
<ul>
<li><a href="hyp-packages-data.html#hyp_packages_data" id="toc-hyp_packages_data"><span class="toc-section-number">12.1</span> Load packages and import data</a></li>
<li><a href="hyp-steps.html#hyp_steps" id="toc-hyp_steps"><span class="toc-section-number">12.2</span> Steps to hypothesis testing</a></li>
<li><a href="hyp-example.html#hyp_example" id="toc-hyp_example"><span class="toc-section-number">12.3</span> An hypothesis test example</a>
<ul>
<li><a href="hyp-example.html#follow_hyp_steps" id="toc-follow_hyp_steps"><span class="toc-section-number">12.3.1</span> Following the steps to hypothesis testing</a></li>
<li><a href="hyp-example.html#sim_null" id="toc-sim_null"><span class="toc-section-number">12.3.2</span> Simulating a “null distribution”</a></li>
<li><a href="hyp-example.html#calc_p" id="toc-calc_p"><span class="toc-section-number">12.3.3</span> Calculating the <em>P</em>-value</a></li>
<li><a href="hyp-example.html#concluding_statement" id="toc-concluding_statement"><span class="toc-section-number">12.3.4</span> Writing a concluding statement</a></li>
</ul></li>
</ul></li>
<li><a href="single-cat.html#single_cat" id="toc-single_cat"><span class="toc-section-number">13</span> Analyzing a single categorical variable</a>
<ul>
<li><a href="singcat-packages-data.html#singcat_packages_data" id="toc-singcat_packages_data"><span class="toc-section-number">13.1</span> Load packages and import data</a></li>
<li><a href="estproportions.html#estproportions" id="toc-estproportions"><span class="toc-section-number">13.2</span> Estimating proportions</a>
<ul>
<li><a href="estproportions.html#sterr_prop" id="toc-sterr_prop"><span class="toc-section-number">13.2.1</span> Standard error for a proportion</a></li>
<li><a href="estproportions.html#confint_prop" id="toc-confint_prop"><span class="toc-section-number">13.2.2</span> Confidence interval for a proportion</a></li>
</ul></li>
<li><a href="binomdist.html#binomdist" id="toc-binomdist"><span class="toc-section-number">13.3</span> Binomial distribution</a></li>
<li><a href="binom-test.html#binom_test" id="toc-binom_test"><span class="toc-section-number">13.4</span> Binomial test</a></li>
<li><a href="prophypconf.html#prophypconf" id="toc-prophypconf"><span class="toc-section-number">13.5</span> Confidence interval approach to hypothesis testing</a></li>
<li><a href="GOF-test.html#GOF_test" id="toc-GOF_test"><span class="toc-section-number">13.6</span> Goodness-of-fit tests</a></li>
</ul></li>
<li><a href="two-cat.html#two_cat" id="toc-two_cat"><span class="toc-section-number">14</span> Analyzing associations between two categorical variables</a>
<ul>
<li><a href="twocat-packages-data.html#twocat_packages_data" id="toc-twocat_packages_data"><span class="toc-section-number">14.1</span> Load packages and import data</a></li>
<li><a href="fishertest.html#fishertest" id="toc-fishertest"><span class="toc-section-number">14.2</span> Fisher’s Exact Test</a>
<ul>
<li><a href="fishertest.html#fisher_hyp" id="toc-fisher_hyp"><span class="toc-section-number">14.2.1</span> Hypothesis statement</a></li>
<li><a href="fishertest.html#show_cont_table" id="toc-show_cont_table"><span class="toc-section-number">14.2.2</span> Display a contingency table</a></li>
<li><a href="fishertest.html#show_mosaic" id="toc-show_mosaic"><span class="toc-section-number">14.2.3</span> Display a mosaic plot</a></li>
<li><a href="fishertest.html#do_fisher" id="toc-do_fisher"><span class="toc-section-number">14.2.4</span> Conduct the Fisher’s Exact Test</a></li>
</ul></li>
<li><a href="odds.html#odds" id="toc-odds"><span class="toc-section-number">14.3</span> Estimate the Odds of getting sick</a></li>
<li><a href="oddsratio.html#oddsratio" id="toc-oddsratio"><span class="toc-section-number">14.4</span> Estimate the odds ratio</a></li>
<li><a href="chisquare.html#chisquare" id="toc-chisquare"><span class="toc-section-number">14.5</span> <span class="math inline">\(\chi\)</span><sup>2</sup> Contingency Test</a>
<ul>
<li><a href="chisquare.html#chihyp" id="toc-chihyp"><span class="toc-section-number">14.5.1</span> Hypothesis statement</a></li>
<li><a href="chisquare.html#showwormcont" id="toc-showwormcont"><span class="toc-section-number">14.5.2</span> Display the contingency table</a></li>
<li><a href="chisquare.html#mosaicworm" id="toc-mosaicworm"><span class="toc-section-number">14.5.3</span> Visualize a mosaic plot</a></li>
<li><a href="chisquare.html#checkchiassum" id="toc-checkchiassum"><span class="toc-section-number">14.5.4</span> Check the assumptions</a></li>
<li><a href="chisquare.html#chiresults" id="toc-chiresults"><span class="toc-section-number">14.5.5</span> Get the results of the test</a></li>
</ul></li>
</ul></li>
<li><a href="single-numeric.html#single_numeric" id="toc-single_numeric"><span class="toc-section-number">15</span> Analyzing a single numerical variable</a>
<ul>
<li><a href="singlenum-packages-data.html#singlenum_packages_data" id="toc-singlenum_packages_data"><span class="toc-section-number">15.1</span> Load packages and import data</a></li>
<li><a href="onesamp-t-test.html#onesamp_t_test" id="toc-onesamp_t_test"><span class="toc-section-number">15.2</span> One-sample <em>t</em>-test</a>
<ul>
<li><a href="onesamp-t-test.html#onesamp_hyp" id="toc-onesamp_hyp"><span class="toc-section-number">15.2.1</span> Hypothesis statement</a></li>
<li><a href="onesamp-t-test.html#onesamp_assumptions" id="toc-onesamp_assumptions"><span class="toc-section-number">15.2.2</span> Assumptions of one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_graph" id="toc-onesamp_graph"><span class="toc-section-number">15.2.3</span> A graph to accompany a one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_test" id="toc-onesamp_test"><span class="toc-section-number">15.2.4</span> Conduct the one-sample <em>t</em>-test</a></li>
<li><a href="onesamp-t-test.html#onesamp_conclude" id="toc-onesamp_conclude"><span class="toc-section-number">15.2.5</span> Concluding statement for the one-sample <em>t</em>-test</a></li>
</ul></li>
<li><a href="t-confidence.html#t_confidence" id="toc-t_confidence"><span class="toc-section-number">15.3</span> Confidence intervals for <span class="math inline">\(\mu\)</span></a>
<ul>
<li><a href="t-confidence.html#conf_precision" id="toc-conf_precision"><span class="toc-section-number">15.3.1</span> Confidence interval as a measure of precision for an estimate</a></li>
<li><a href="t-confidence.html#conf_hyp" id="toc-conf_hyp"><span class="toc-section-number">15.3.2</span> Confidence interval approach to hypothesis testing</a></li>
</ul></li>
</ul></li>
<li><a href="compare-two-means.html#compare_two_means" id="toc-compare_two_means"><span class="toc-section-number">16</span> Comparing means among two groups</a>
<ul>
<li><a href="twomean-packages-data.html#twomean_packages_data" id="toc-twomean_packages_data"><span class="toc-section-number">16.1</span> Load packages and import data</a></li>
<li><a href="paired-t-test.html#paired-t-test" id="toc-paired-t-test"><span class="toc-section-number">16.2</span> Paired <em>t</em>-test</a>
<ul>
<li><a href="paired-t-test.html#calc_diffs" id="toc-calc_diffs"><span class="toc-section-number">16.2.1</span> Calculate differences</a></li>
<li><a href="paired-t-test.html#paired_Htest" id="toc-paired_Htest"><span class="toc-section-number">16.2.2</span> Hypothesis statement</a></li>
<li><a href="paired-t-test.html#graph_paried" id="toc-graph_paried"><span class="toc-section-number">16.2.3</span> A graph to accompany a paired <em>t</em>-test</a></li>
<li><a href="paired-t-test.html#assump_paried" id="toc-assump_paried"><span class="toc-section-number">16.2.4</span> Assumptions of the paired <em>t</em>-test</a></li>
<li><a href="paired-t-test.html#conduct_paired" id="toc-conduct_paired"><span class="toc-section-number">16.2.5</span> Conduct the test</a></li>
<li><a href="paired-t-test.html#concl_paired" id="toc-concl_paired"><span class="toc-section-number">16.2.6</span> Concluding statement</a></li>
</ul></li>
<li><a href="twosamp-ttest.html#twosamp_ttest" id="toc-twosamp_ttest"><span class="toc-section-number">16.3</span> Two sample <em>t</em>-test</a>
<ul>
<li><a href="twosamp-ttest.html#twosamp_hyp" id="toc-twosamp_hyp"><span class="toc-section-number">16.3.1</span> Hypothesis statement</a></li>
<li><a href="twosamp-ttest.html#stats_2samp" id="toc-stats_2samp"><span class="toc-section-number">16.3.2</span> A table of descriptive statistics</a></li>
<li><a href="twosamp-ttest.html#graph_2samp" id="toc-graph_2samp"><span class="toc-section-number">16.3.3</span> A graph to accompany a 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#twosamp_assump" id="toc-twosamp_assump"><span class="toc-section-number">16.3.4</span> Assumptions of the 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#conduct_2samptest" id="toc-conduct_2samptest"><span class="toc-section-number">16.3.5</span> Conduct the 2-sample <em>t</em>-test</a></li>
<li><a href="twosamp-ttest.html#concl_2samp" id="toc-concl_2samp"><span class="toc-section-number">16.3.6</span> Concluding statement</a></li>
</ul></li>
<li><a href="assumpbad-2samp.html#assumpbad_2samp" id="toc-assumpbad_2samp"><span class="toc-section-number">16.4</span> When assumptions aren’t met</a></li>
</ul></li>
<li><a href="compare-three-more-means.html#compare_three_more_means" id="toc-compare_three_more_means"><span class="toc-section-number">17</span> Comparing means among more than two groups</a>
<ul>
<li><a href="anova-packages-data.html#anova_packages_data" id="toc-anova_packages_data"><span class="toc-section-number">17.1</span> Load packages and import data</a></li>
<li><a href="do-the-anova.html#do_the_anova" id="toc-do_the_anova"><span class="toc-section-number">17.2</span> Analysis of variance</a>
<ul>
<li><a href="do-the-anova.html#anova_hyps" id="toc-anova_hyps"><span class="toc-section-number">17.2.1</span> Hypothesis statements</a></li>
<li><a href="do-the-anova.html#stats_anova" id="toc-stats_anova"><span class="toc-section-number">17.2.2</span> A table of descriptive statistics</a></li>
<li><a href="do-the-anova.html#anova_graph1" id="toc-anova_graph1"><span class="toc-section-number">17.2.3</span> Visualize the data</a></li>
<li><a href="do-the-anova.html#assump_anova" id="toc-assump_anova"><span class="toc-section-number">17.2.4</span> Assumptions of ANOVA</a></li>
<li><a href="do-the-anova.html#do_anova1" id="toc-do_anova1"><span class="toc-section-number">17.2.5</span> Conduct the ANOVA test</a></li>
<li><a href="do-the-anova.html#createanovatable" id="toc-createanovatable"><span class="toc-section-number">17.2.6</span> Generate nice ANOVA table</a></li>
<li><a href="do-the-anova.html#calculate-r2-for-the-anova" id="toc-calculate-r2-for-the-anova"><span class="toc-section-number">17.2.7</span> Calculate <span class="math inline">\(R^2\)</span> for the ANOVA</a></li>
<li><a href="do-the-anova.html#tukey" id="toc-tukey"><span class="toc-section-number">17.2.8</span> Tukey-Kramer post-hoc test</a></li>
<li><a href="do-the-anova.html#vis_tukey" id="toc-vis_tukey"><span class="toc-section-number">17.2.9</span> Visualizing post-hoc test results</a></li>
<li><a href="do-the-anova.html#anova_conclusion" id="toc-anova_conclusion"><span class="toc-section-number">17.2.10</span> Concluding statement</a></li>
</ul></li>
<li><a href="assumpbad-anova.html#assumpbad_anova" id="toc-assumpbad_anova"><span class="toc-section-number">17.3</span> When assumptions aren’t met</a></li>
</ul></li>
<li><a href="two-num.html#two_num" id="toc-two_num"><span class="toc-section-number">18</span> Analyzing associations between two numerical variables</a>
<ul>
<li><a href="twonum-packages-data.html#twonum_packages_data" id="toc-twonum_packages_data"><span class="toc-section-number">18.1</span> Load packages and import data</a></li>
<li><a href="pearson.html#pearson" id="toc-pearson"><span class="toc-section-number">18.2</span> Pearson correlation analysis</a>
<ul>
<li><a href="pearson.html#pearson_hyp" id="toc-pearson_hyp"><span class="toc-section-number">18.2.1</span> Hypothesis statements</a></li>
<li><a href="pearson.html#see_corr" id="toc-see_corr"><span class="toc-section-number">18.2.2</span> Visualize the data</a></li>
<li><a href="pearson.html#corr_assumptions" id="toc-corr_assumptions"><span class="toc-section-number">18.2.3</span> Assumptions of correlation analysis</a></li>
<li><a href="pearson.html#do_corr" id="toc-do_corr"><span class="toc-section-number">18.2.4</span> Conduct the correlation analysis</a></li>
<li><a href="pearson.html#concl_corr" id="toc-concl_corr"><span class="toc-section-number">18.2.5</span> Concluding statement</a></li>
</ul></li>
<li><a href="rankcorr.html#rankcorr" id="toc-rankcorr"><span class="toc-section-number">18.3</span> Rank correlation (Spearman’s correlation)</a>
<ul>
<li><a href="rankcorr.html#hypothesis-statements" id="toc-hypothesis-statements"><span class="toc-section-number">18.3.1</span> Hypothesis statements</a></li>
<li><a href="rankcorr.html#spearman_hyp" id="toc-spearman_hyp"><span class="toc-section-number">18.3.2</span> Visualize the data</a></li>
<li><a href="rankcorr.html#assum_spear" id="toc-assum_spear"><span class="toc-section-number">18.3.3</span> Assumptions of Spearman rank correlation</a></li>
<li><a href="rankcorr.html#conduct_spearman" id="toc-conduct_spearman"><span class="toc-section-number">18.3.4</span> Conduct the test</a></li>
<li><a href="rankcorr.html#spear_conclude" id="toc-spear_conclude"><span class="toc-section-number">18.3.5</span> Concluding statement</a></li>
</ul></li>
</ul></li>
<li><a href="creating-tables-in-r-markdown.html#creating-tables-in-r-markdown" id="toc-creating-tables-in-r-markdown">Creating tables in R Markdown</a>
<ul>
<li><a href="tables-packages.html#tables_packages" id="toc-tables_packages"><span class="toc-section-number">18.4</span> Load packages and import data</a>
<ul>
<li><a href="tables-packages.html#skim_tables" id="toc-skim_tables"><span class="toc-section-number">18.4.1</span> Formatting output from the <code>skimr</code> package</a></li>
<li><a href="tables-packages.html#stats_nicetable" id="toc-stats_nicetable"><span class="toc-section-number">18.4.2</span> A nicely formatted table of descriptive statistics</a></li>
</ul></li>
</ul></li>
<li><a href="checking-assumptions-and-data-transformations.html#checking-assumptions-and-data-transformations" id="toc-checking-assumptions-and-data-transformations">Checking assumptions and data transformations</a>
<ul>
<li><a href="assumptions-packages-data.html#assumptions_packages_data" id="toc-assumptions_packages_data"><span class="toc-section-number">18.5</span> Load packages and import data</a></li>
<li><a href="checknorm-assum.html#checknorm_assum" id="toc-checknorm_assum"><span class="toc-section-number">18.6</span> Checking the normality assumption</a>
<ul>
<li><a href="checknorm-assum.html#quantile_plots" id="toc-quantile_plots"><span class="toc-section-number">18.6.1</span> Normal quantile plots</a></li>
<li><a href="checknorm-assum.html#shapirottest" id="toc-shapirottest"><span class="toc-section-number">18.6.2</span> Shapiro-Wilk test for normality</a></li>
</ul></li>
<li><a href="levenetest.html#levenetest" id="toc-levenetest"><span class="toc-section-number">18.7</span> Checking the equal-variance assumption</a></li>
<li><a href="transform.html#transform" id="toc-transform"><span class="toc-section-number">18.8</span> Data transformations</a>
<ul>
<li><a href="transform.html#log_transform" id="toc-log_transform"><span class="toc-section-number">18.8.1</span> Log-transform</a></li>
<li><a href="transform.html#zeroes" id="toc-zeroes"><span class="toc-section-number">18.8.2</span> Dealing with zeroes</a></li>
<li><a href="transform.html#logbases" id="toc-logbases"><span class="toc-section-number">18.8.3</span> Log bases</a></li>
<li><a href="transform.html#back_transform" id="toc-back_transform"><span class="toc-section-number">18.8.4</span> Back-transforming log data</a></li>
<li><a href="transform.html#logit_transform" id="toc-logit_transform"><span class="toc-section-number">18.8.5</span> Logit transform</a></li>
<li><a href="transform.html#logit_back" id="toc-logit_back"><span class="toc-section-number">18.8.6</span> Back-transforming logit data</a></li>
<li><a href="transform.html#when_back" id="toc-when_back"><span class="toc-section-number">18.8.7</span> When to back-transform?</a></li>
</ul></li>
</ul></li>
<li><a href="visual-markdown-editor.html#visual-markdown-editor" id="toc-visual-markdown-editor">Visual Markdown Editor</a>
<ul>
<li><a href="a-more-familiar-editing-environment.html#a-more-familiar-editing-environment" id="toc-a-more-familiar-editing-environment">A more familiar editing environment</a></li>
</ul></li>
<li><a href="common-errors-and-their-solutions.html#common-errors-and-their-solutions" id="toc-common-errors-and-their-solutions">Common errors and their solutions</a>
<ul>
<li><a href="google-can-help.html#google-can-help" id="toc-google-can-help">Google can help</a></li>
<li><a href="rtools-required-during-install.html#rtools-required-during-install" id="toc-rtools-required-during-install">Rtools required during install</a></li>
<li><a href="could-not-find-function.html#could-not-find-function" id="toc-could-not-find-function">Could not find function</a></li>
<li><a href="there-is-no-package.html#there-is-no-package" id="toc-there-is-no-package">There is no package</a></li>
<li><a href="trying-to-use-cran-without-setting-a-mirror.html#trying-to-use-cran-without-setting-a-mirror" id="toc-trying-to-use-cran-without-setting-a-mirror">Trying to use CRAN without setting a mirror</a></li>
<li><a href="pdf-latex-is-not-found.html#pdf-latex-is-not-found" id="toc-pdf-latex-is-not-found">PDF Latex is not found</a></li>
<li><a href="error-in-parse.html#error-in-parse" id="toc-error-in-parse">Error in parse</a></li>
<li><a href="no-such-file-or-directory-exists.html#no-such-file-or-directory-exists" id="toc-no-such-file-or-directory-exists">No such file or directory exists</a></li>
<li><a href="messy-output-when-loading-packages.html#messy-output-when-loading-packages" id="toc-messy-output-when-loading-packages">Messy output when loading packages</a></li>
<li><a href="unused-argument.html#unused-argument" id="toc-unused-argument">Unused argument</a></li>
<li><a href="object-not-found.html#object-not-found" id="toc-object-not-found">Object not found</a></li>
<li><a href="figure-caption-doesnt-show-up-below-figure-in-knitted-document.html#figure-caption-doesnt-show-up-below-figure-in-knitted-document" id="toc-figure-caption-doesnt-show-up-below-figure-in-knitted-document">Figure caption doesn’t show up below figure in knitted document</a></li>
<li><a href="filename-directory-name-or-volume-label-syntax-is-incorrect.html#filename-directory-name-or-volume-label-syntax-is-incorrect" id="toc-filename-directory-name-or-volume-label-syntax-is-incorrect">Filename, directory name, or volume label syntax is incorrect</a></li>
<li><a href="installing-packages-there-is-a-binary-version-available.html#installing-packages-there-is-a-binary-version-available" id="toc-installing-packages-there-is-a-binary-version-available">Installing packages: there is a binary version available</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tutorials for BIOL202: Introduction to Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="twosamp_ttest" class="section level2" number="16.3">
<h2><span class="header-section-number">16.3</span> Two sample <em>t</em>-test</h2>
<p>Have a look at the <code>students</code> dataset:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="twosamp-ttest.html#cb304-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb304-2"><a href="twosamp-ttest.html#cb304-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim_without_charts</span>()</span></code></pre></div>
<table style="width: auto;" class="table table-condensed">
<caption>
<span id="tab:unnamed-chunk-85">Table 16.1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
154
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Dominant_hand
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Dominant_foot
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Dominant_eye
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
height_cm
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
171.97
</td>
<td style="text-align:right;">
10.03
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
165.00
</td>
<td style="text-align:right;">
171.48
</td>
<td style="text-align:right;">
180.0
</td>
<td style="text-align:right;">
210.8
</td>
</tr>
<tr>
<td style="text-align:left;">
head_circum_cm
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
56.04
</td>
<td style="text-align:right;">
6.41
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
55.52
</td>
<td style="text-align:right;">
57.00
</td>
<td style="text-align:right;">
58.5
</td>
<td style="text-align:right;">
63.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Number_of_siblings
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
6.0
</td>
</tr>
</tbody>
</table>
<p>These data include measurements taken on 154 students in BIOL202 a few years ago.</p>
<p>We’ll use the “height” and “Dominant_eye” variables for this section.</p>
<p><strong>OPTIONAL</strong></p>
<p>Note that the categories in the <code>Dominant_eye</code> variable are “l” and “r”, denoting “left” and “right”.</p>
<p>We can use the <code>unique</code> function to tell us all unique values of a categorical variable:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="twosamp-ttest.html#cb305-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span> </span>
<span id="cb305-2"><a href="twosamp-ttest.html#cb305-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Dominant_eye) <span class="sc">%&gt;%</span></span>
<span id="cb305-3"><a href="twosamp-ttest.html#cb305-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 1
##   Dominant_eye
##   &lt;chr&gt;       
## 1 r           
## 2 l</code></pre>
<p>Let’s change these to be more informative, “Left” and “Right”.</p>
<p>We can do this with the <code>recode_factor</code> function from the <code>dplyr</code> package (part of the <code>tidyverse</code>), in conjunction with the familiar <code>mutate</code> function used to create a new variable (though here we’re just over-writing an existing variable):</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="twosamp-ttest.html#cb307-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> students <span class="sc">%&gt;%</span></span>
<span id="cb307-2"><a href="twosamp-ttest.html#cb307-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Dominant_eye =</span> <span class="fu">recode_factor</span>(Dominant_eye, <span class="at">r =</span> <span class="st">&quot;Right&quot;</span>, <span class="at">l =</span> <span class="st">&quot;Left&quot;</span>))</span></code></pre></div>
<div id="twosamp_hyp" class="section level3" number="16.3.1">
<h3><span class="header-section-number">16.3.1</span> Hypothesis statement</h3>
<p>H<sub>0</sub>: Mean height is the same among students with left dominant eyes and right dominant eyes (<span class="math inline">\(\mu_L = \mu_R\)</span>).<br />
H<sub>A</sub>: Mean height is not the same among students with left dominant eyes and right dominant eyes (<span class="math inline">\(\mu_L \ne \mu_R\)</span>).</p>
<p>Steps to a hypothesis test:</p>
<ul>
<li>We’ll use an <span class="math inline">\(\alpha\)</span> level of 0.05.<br />
</li>
<li>It is a two-tailed <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Alternative-hypothesis">alternative hypothesis</a></li>
<li>We’ll provide a table of <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Descriptive-statistics">descriptive statistics</a> for each group</li>
<li>We’ll visualize the data, and interpret the output</li>
<li>We’ll use a <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Two-sample-t-test">2-sample <em>t</em>-test</a> to test the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Null-hypothesis">null hypothesis</a>, because we’re dealing with numerical measurements taken on independent within two independent groups, and drawing inferences about population means <span class="math inline">\(\mu\)</span> using sample data<br />
</li>
<li>We’ll check the assumptions of the test (see below)</li>
<li>We’ll calculate our test statistic</li>
<li>We’ll calculate the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#P-value"><em>P</em>-value</a> associated with our test statistic</li>
<li>We’ll calculate a 95% confidence interval for the difference (<span class="math inline">\(\mu_L - \mu_R\)</span>)</li>
<li>We’ll provide a good concluding statement that includes a 95% confidence interval for the mean difference (<span class="math inline">\(\mu_L - \mu_R\)</span>)</li>
</ul>
</div>
<div id="stats_2samp" class="section level3" number="16.3.2">
<h3><span class="header-section-number">16.3.2</span> A table of descriptive statistics</h3>
<p>When we are analyzing a numeric response variable in relation to a categorical variable with two or more categories, it’s good practice to provide a table of summary (or “descriptive”) statistics (including confidence intervals for the mean) for the numeric variable grouped by the categories.</p>
<p>In a previous <a href="desc-numeric-var-cat.html#desc_numeric_var_cat">tutorial</a> we learned how to calculate descriptive statistics for a numeric variable grouped by a categorical variable. In another <a href="t-confidence.html#conf_precision">tutorial</a> we also learned how to calculate confidence intervals for a numeric variable.</p>
<p>We’ve also learned that the <code>t.test</code> function returns a confidence interval for us.</p>
<p>Let’s use all these skills to generate a table of summary statistics for the “height_cm” variable, grouped by “Dominant_eye”:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="twosamp-ttest.html#cb308-1" aria-hidden="true" tabindex="-1"></a>height.stats <span class="ot">&lt;-</span> students <span class="sc">%&gt;%</span></span>
<span id="cb308-2"><a href="twosamp-ttest.html#cb308-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Dominant_eye) <span class="sc">%&gt;%</span></span>
<span id="cb308-3"><a href="twosamp-ttest.html#cb308-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb308-4"><a href="twosamp-ttest.html#cb308-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count =</span> <span class="fu">n</span>() <span class="sc">-</span> naniar<span class="sc">::</span><span class="fu">n_miss</span>(height_cm),</span>
<span id="cb308-5"><a href="twosamp-ttest.html#cb308-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count_NA =</span> naniar<span class="sc">::</span><span class="fu">n_miss</span>(height_cm), </span>
<span id="cb308-6"><a href="twosamp-ttest.html#cb308-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(height_cm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb308-7"><a href="twosamp-ttest.html#cb308-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(height_cm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb308-8"><a href="twosamp-ttest.html#cb308-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">SEM =</span> SD<span class="sc">/</span><span class="fu">sqrt</span>(Count),</span>
<span id="cb308-9"><a href="twosamp-ttest.html#cb308-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Low_95_CL =</span> <span class="fu">t.test</span>(height_cm, <span class="at">conf.level =</span> <span class="fl">0.95</span>)<span class="sc">$</span>conf.int[<span class="dv">1</span>],</span>
<span id="cb308-10"><a href="twosamp-ttest.html#cb308-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Up_95_CL =</span> <span class="fu">t.test</span>(height_cm, <span class="at">conf.level =</span> <span class="fl">0.95</span>)<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb308-11"><a href="twosamp-ttest.html#cb308-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>The only unfamiliar code in the preceding chunk is the last two lines:</p>
<ul>
<li>we use the <code>t.test</code> function to calculate the lower and upper confidence limits. Specifically:
<ul>
<li>after the closing parenthesis to the <code>t.test</code> function, we include “$conf.int[1]”, and this simply extracts the first value (lower limit) of the calculated confidence limits from the <code>t.test</code> output</li>
<li>we do the same for the upper confidence limit, but this time we include “$conf.int[2]”</li>
</ul></li>
</ul>
<p>Now let’s have a look at the table, using the <code>kable</code> function to produce a nice table.</p>
<p><strong>NOTE</strong> here I am rotating the table so that it fits on the page. To do this, use the <code>t</code> function as follows:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="twosamp-ttest.html#cb309-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">t</span>(height.stats), <span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<tbody>
<tr>
<td style="text-align:left;">
Dominant_eye
</td>
<td style="text-align:left;">
Right
</td>
<td style="text-align:left;">
Left
</td>
</tr>
<tr>
<td style="text-align:left;">
Count
</td>
<td style="text-align:left;">
106
</td>
<td style="text-align:left;">
48
</td>
</tr>
<tr>
<td style="text-align:left;">
Count_NA
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Mean
</td>
<td style="text-align:left;">
172.8368
</td>
<td style="text-align:left;">
170.0598
</td>
</tr>
<tr>
<td style="text-align:left;">
SD
</td>
<td style="text-align:left;">
10.397638
</td>
<td style="text-align:left;">
8.964659
</td>
</tr>
<tr>
<td style="text-align:left;">
SEM
</td>
<td style="text-align:left;">
1.009908
</td>
<td style="text-align:left;">
1.293937
</td>
</tr>
<tr>
<td style="text-align:left;">
Low_95_CL
</td>
<td style="text-align:left;">
170.8343
</td>
<td style="text-align:left;">
167.4567
</td>
</tr>
<tr>
<td style="text-align:left;">
Up_95_CL
</td>
<td style="text-align:left;">
174.8393
</td>
<td style="text-align:left;">
172.6629
</td>
</tr>
</tbody>
</table>
<p>It is best to <strong>NOT rotate the table</strong>, but it is fine to do so if your table goes off the page!</p>
<p>We’ll learn a better way to get around this later.</p>
</div>
<div id="graph_2samp" class="section level3" number="16.3.3">
<h3><span class="header-section-number">16.3.3</span> A graph to accompany a 2-sample <em>t</em>-test</h3>
<p>We learned in an earlier <a href="numeric-vs-cat.html#numeric_vs_cat">tutorial</a> that we can use a stripchart, violin plot, or boxplot to visualize the association between a numerical response variable and a categorical explanatory variable. Better yet, we can do the <a href="numeric-vs-cat.html#bestplot">combined violin &amp; boxplot</a>.</p>
<p>Here we want to visualize height in relation to dominant eye (Left or Right). We can use the information provided in our descriptive stats table to get the sample sizes for the groups (which we need to report in the figure heading).</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="twosamp-ttest.html#cb310-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span> </span>
<span id="cb310-2"><a href="twosamp-ttest.html#cb310-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Dominant_eye, <span class="at">y =</span> height_cm)) <span class="sc">+</span></span>
<span id="cb310-3"><a href="twosamp-ttest.html#cb310-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb310-4"><a href="twosamp-ttest.html#cb310-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb310-5"><a href="twosamp-ttest.html#cb310-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">width =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb310-6"><a href="twosamp-ttest.html#cb310-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Dominant eye&quot;</span>) <span class="sc">+</span></span>
<span id="cb310-7"><a href="twosamp-ttest.html#cb310-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Height (cm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb310-8"><a href="twosamp-ttest.html#cb310-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-88"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-88-1.png" alt="Violin and boxplot of the heights of students with right (n = 106) and left (n = 48) dominant eyes.  Boxes delimit the first to third quartiles, bold lines represent the group medians, and whiskers extend to 1.5 times the IQR. Points beyond whiskers are extreme observations." width="288" />
<p class="caption">
Figure 16.4: Violin and boxplot of the heights of students with right (n = 106) and left (n = 48) dominant eyes. Boxes delimit the first to third quartiles, bold lines represent the group medians, and whiskers extend to 1.5 times the IQR. Points beyond whiskers are extreme observations.
</p>
</div>
<p><strong>Interpretation</strong></p>
<blockquote>
<p>We can see in the preceding figure that heights are generally similar between students with left dominant eyes and those with right dominant eyes. However, it appears that the spread of the heights is greater among students with right dominant eyes. We will need to be careful about the equal-variance assumption for the 2-sample <em>t</em>-test.</p>
</blockquote>
</div>
<div id="twosamp_assump" class="section level3" number="16.3.4">
<h3><span class="header-section-number">16.3.4</span> Assumptions of the 2-sample <em>t</em>-test</h3>
<p>The <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Assumptions">assumptions</a> of the 2-sample <em>t</em>-test are as follows:</p>
<ul>
<li>each of the two samples is a random sample from its population</li>
<li>the numerical variable is normally distributed in each population</li>
<li>the <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Variance">variance</a> (and thus <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Standard-deviation">standard deviation</a>) of the numerical variable is the same in both populations</li>
</ul>
<p><strong>Test for normality</strong></p>
<p>Now let’s check the normality assumption by plotting a normal quantile plot for each group.</p>
<p>We’ll introduce the <code>facet_grid</code> function that enables plotting of side-by-side panels according to a grouping variable.</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="twosamp-ttest.html#cb311-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb311-2"><a href="twosamp-ttest.html#cb311-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> height_cm)) <span class="sc">+</span></span>
<span id="cb311-3"><a href="twosamp-ttest.html#cb311-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb311-4"><a href="twosamp-ttest.html#cb311-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb311-5"><a href="twosamp-ttest.html#cb311-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> Dominant_eye) <span class="sc">+</span></span>
<span id="cb311-6"><a href="twosamp-ttest.html#cb311-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Normal quantile&quot;</span>) <span class="sc">+</span></span>
<span id="cb311-7"><a href="twosamp-ttest.html#cb311-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Height (cm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb311-8"><a href="twosamp-ttest.html#cb311-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-89"></span>
<img src="BIOL202_files/figure-html/unnamed-chunk-89-1.png" alt="Normal quantile plots of height for students with right (n = 106) or left (n = 48) dominant eyes." width="480" />
<p class="caption">
Figure 16.5: Normal quantile plots of height for students with right (n = 106) or left (n = 48) dominant eyes.
</p>
</div>
<p>A reasonable statement would be:</p>
<blockquote>
<p>“The normal quantile plots show that student height is generally normally distributed for students with left or right dominant eyes. There is one observation among the right-dominant eye students that is a bit off the line.”</p>
</blockquote>
<p><strong>Test for equal variances</strong></p>
<p>Now we need to test the assumption of equal variance among the groups, using Levene’s Test as we learned in the <a href="levenetest.html#levenetest">checking assumptions</a> tutorial.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="twosamp-ttest.html#cb312-1" aria-hidden="true" tabindex="-1"></a>height.vartest <span class="ot">&lt;-</span> <span class="fu">leveneTest</span>(height_cm <span class="sc">~</span> Dominant_eye, <span class="at">data =</span> students)</span>
<span id="cb312-2"><a href="twosamp-ttest.html#cb312-2" aria-hidden="true" tabindex="-1"></a>height.vartest</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1   0.907 0.3424
##       152</code></pre>
<p>It uses a test statistic “F”, and we see here that the <em>P</em>-value associated with the test statistic is larger than 0.05, so we don’t reject the implied null hypothesis that the variances are equal.</p>
<p>We state “A Levene’s test showed no evidence against the assumption of equal variance (<em>F</em> = 0.91; <em>P</em>-value = 0.342).”</p>
<p>Thus, we’ll proceed with conducting the 2-sample <em>t</em>-test.</p>
</div>
<div id="conduct_2samptest" class="section level3" number="16.3.5">
<h3><span class="header-section-number">16.3.5</span> Conduct the 2-sample <em>t</em>-test</h3>
<p>We use the <code>t.test</code> function again for this test.</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="twosamp-ttest.html#cb314-1" aria-hidden="true" tabindex="-1"></a>height.ttest <span class="ot">&lt;-</span> students <span class="sc">%&gt;%</span></span>
<span id="cb314-2"><a href="twosamp-ttest.html#cb314-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(height_cm <span class="sc">~</span> Dominant_eye, </span>
<span id="cb314-3"><a href="twosamp-ttest.html#cb314-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> ., <span class="at">paired =</span> <span class="cn">FALSE</span>, </span>
<span id="cb314-4"><a href="twosamp-ttest.html#cb314-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<p>The only differences from the implementation used in the paired <em>t</em>-test are:</p>
<ul>
<li>we used “paired = FALSE”</li>
<li>we include the “var.equal = TRUE” argument</li>
</ul>
<p>We again include the argument “data = .”, which tells the <code>t.test</code> function that whatever data was passed to it from the preceding line is what will be used</p>
<p>We’ll learn a bit later what to due when the equal variance assumption is not met.</p>
<p>Let’s look at the result:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="twosamp-ttest.html#cb315-1" aria-hidden="true" tabindex="-1"></a>height.ttest</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  height_cm by Dominant_eye
## t = 1.6, df = 152, p-value = 0.1117
## alternative hypothesis: true difference in means between group Right and group Left is not equal to 0
## 95 percent confidence interval:
##  -0.6521529  6.2061545
## sample estimates:
## mean in group Right  mean in group Left 
##            172.8368            170.0598</code></pre>
<p>We see that the test produced a <em>P</em>-value greater than <span class="math inline">\(\alpha\)</span>, so we fail to reject the null hypothesis.</p>
<p>Note also that the output includes a <strong>confidence interval</strong> for the <em>difference</em> in group means. We need to include this in our concluding statement.</p>
</div>
<div id="concl_2samp" class="section level3" number="16.3.6">
<h3><span class="header-section-number">16.3.6</span> Concluding statement</h3>
<p>Here’s an example of a concluding statement:</p>
<blockquote>
<p>On average, students with left dominant eyes are similar in height to students with right dominant eyes (Figure 19.4) (2-sample <em>t</em>-test; <em>t</em> = 1.6; df = 152; <em>P</em>-value = 0.112; 95% confidence interval for the difference in height -0.652 <span class="math inline">\(&lt; \mu_d &lt;\)</span> 6.206).</p>
</blockquote>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="paired-t-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="assumpbad-2samp.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL202.pdf", "BIOL202.epub"],
"toc": {
"collapse": "section",
"scroll_highight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
